### ISSUE TITLE
[Translation Demand - Persian] Numbers x Metaverse														

### ISSUE THREAD

**Issue by Charles7021** [numbersprotocol/community-support#102]
**[Persian translators wanted!]** 

The article:
**[Numbers x Metaverse](https://medium.com/numbers-protocol/numbers-x-metaverse-d0811f5879a)**

Leave your translation in this issue comment to become our Tier 1 Ambassador!

--
- How to participate
> - Translate **at least 1 paragraph of the selected article**.
> - **The translation should be done as the Github issue comment.**
> - **Share the link of the comment in the local community and get at least 3 likes on Github**. If there is no community for your language existing yet, find your Web 3.0 friends to come here to help review your work and like the comment.
> - If there are two comments linked to the same paragraph and both collect 3 likes, the earlier one wins.
> - The translation needs to be fluent and factually correct and should not be copied directly from Google translate or similar apps (any attempt to copy-paste directly from Google Translate will result in your dismissal from the Ambassador Program).

- Rewards
> - `10 NUM` per paragraph per language
> - Bounty-based, the selected article will be announced when it gets 3 likes.
"

**Comment by hussein76091320** [comment]
**نامبرز   (Numbers) × متاورس (Metaverse)**

در سال گذشته گسترش و رضايت مندي NFT  ها ، توسط جعل و کلاه برداري پنهان شده است . 

بيش از 80 درصد از توکن هاي غير قابل تعويض (NFT) که به صورت رايگان در OpenSea ارائه مي شوند فيک، دزديده شده يا هرزنامه هستند. 

خود OpenSea پس از تغيير مسير در يک ويژگي محبوب در پلتفرم خود ، آمار تکان دهنده اي را فاش کرد. آن ها قبلا اجازه ايجاد NFT ها را با استفاده از "ضربه سازي تنبل(Lazy Minting)" ايجاد کنند. (يعني توکن هاي NFT «خارج از زنجيره» يا «خارج از بلاکچين» دز دسترس هستند و تنها يک بار يک بار توکن هاي غير قابل تعويض ذخيره مي شوند . NFT ها فروخته مي شوند ، به اين معني که هنرمند نيازي به پرداخت هيچ هزينه اي از قبل ندارد.  تا زماني که توکن غير قابل تعويض (NFT) فروخته نشود ،فروشندگان هزينه اي پرداخت نميکنند و به کلاهبرداران اجازه مي دهد اقلام دزديده شده را به اميد فروش آن ها به خريداران ناشناس ليست کنند. در حالي که ساير بازار ها همچنين اجازه "ضربه تنبل" را مي دهند ، محبوبيت OpenSea و سيستم بررسي ضعيف آن را به مکاني ايده آل براي کلاه برداران تبديل کرده است .تا به دنبال فرصت مناسب براي حمله باشند. 

براي جلوگيري از اين امر آن ها خط مشي خود را تغيير داده اند و تنها به حداکثر 5 مجموعه NFT با 50 مورد در هر مجموعه اجازه مي دهند . با اين حال ، اين مشکل را به طور کلي حل نميکند بلکه فقط حجم جعل و کلاه برداري و تقلب را به کمترين ميزان مي رساند.

ما انگشت خود را به سمت فضاي Web3/NFT نشانه نمي رويم ، زيرا به خوبي مي دانيم که در دنياي واقعي نيز اين اتفاق مي افتد. Frontier Economics  تخمين مي زند که ارزش جهاني جعل و دزدي دريايي نزديک 2.8 تريليون دلار در سال است و به دليل مشکلات زنجيره تامين ناشي از کوويد-19 تقاضا براي کالاهاي –تقلبي يا غير تقلبي- به شدت افزايش يافته است. 

تفاوت بين دنياي واقعي و فضاي NFT در اين است که ما زيرساختي براي احراز هويت اقلام ارزشمند داريم . اگر بخواهيد براي خريد رولکس به ساعت فروشي برويد ، گواهي اصالت کالا دارد ، اگر بخواهيد يک کيف دست دوز را بخريد ،با شماره سريال ،برچسب هاي برند يا برچسب هاي اصالت ارائه مي شود که نشان مي دهد شما خريده ايد يا فيک و تقلبي است .

**مشکل**
با NFT ها شروع شد ، هر چند ما اکنون در کل دنيا داراي چالش بسيار بزرگتري در مورد ايمني کاربر داريم و اين سوال را ايجاد مي کند **که چگونه اعتبار را به متاورس بياوريم ؟**

در ذهن ما هيچ شکي نيست که متاورس شاهد پذيرش عظيمي خواهد بود. Decentraland  که در حال حاضر بزرگترين پلتفرم است ، در حال حاضر داراي 300000 کاربر فعال ماهانه و 18000 کاربر روزانه است. اگرچه اين تعداد ممکن است زياد به نظر نرسد ، اما ما اين شانس را داريم که با اين مشکل اصالت مقابله کنيم و حجم تقلب و جعل را قبل از اين که تعداد کاربران بزرگتر شود به حداقل برسانيم. 

ما مي دانيم که نميتوانيم جلوي جعل را باهم بگبريم ، اما مي توانيم پروتکل هاي مناسبي را براي هشدار به کاربران در مورد اين که کدام اقلام واقعي و کدام تقلبي هستند، ايجاد کنيم. به اين ترتيب است که قدرت و کنترل را دوباره به دست کاربران مي سپاريم. 

**چگونه Numbers اين مشکل را حل ميکند **
**موتور جستجوي NFT**

موتورجستجوي NFT تصوير کاملي از NFT ها ارائه مي دهد تا کاربران بتوانند به روشي غير متمرکز راحت تر ببينند که چه چيزي خوب است و چه چيزي خوب نيست.

منظورم اين است که هميشه مي توان تاييد قرارداد را در OpenSea بررسي کرد ، اما اين تاييد «متمرکز» است که توسط OpenSea  کنترل مي شود. 

موتور جستجوي Numbers NFT در حال حاضر داراي 2 ويژگي است که هدف آن خنثي کردن تقلبي است که در صنعت مشاهده مي کنيم.
تشخيص چند توکن : براي کمک به کاربران در شناسايي تعداد نشانه هاي مرتبط با يک تصوير .

نشان web3.0  : براي کمک به کاربران براي بررسي اينکه آيا NFT به درستي در Web3.0 ذخيره شده است ، به عنوان مثال آيا فايل دارايي غيرمتمرکز است ، آيا ابر داده با مشخصات مطابقت دارد و غيره.

**خدمات سازماني **
ما همچنين با پلتفرم ها و بازار هاي مختلفي همکاري کرده ايم تا ويژگي هايي را براي رفع اين مشکل پياده سازي کنيم . 

**اسکن بازار : Featured × Numbers**
بايننس يک پلتفرم غير متمرکز NFT است که ابزارهايي را براي توليد ، فروش و نمايش آثار NFT در اختيار سازندگان قرار مي دهد . با اين حال ، به عنوان يک پلتفرم که هنوز اساسا "باز" است ، آن ها با کلاه برداري هاي زيادي در بازار مواجه شدند . مزاياي آسان و ارزان ساختن NFT ها با معايب آن نيز همراه است. همچنين کپي کردن NFT ها از پلتفرم هاي ديگر را براي بازيگران مشکوک آسان کرده است –معمولا NFT ها از اکوسيستم اتريوم مانند OpenSea.

پس از استفاده از روش هاي مختلف براي مقابله با اين مشکل ، مانند تسهيل گزارش کلاهبرداري ها براي جامعه ، آن ها مي دانستند که بايد بزرگتر شوند! اينجا جايي است که در يک شب جمعه معمولي ، در طي تماسي با Featured ايده يکپارچگي را رقم زد .

اسکن NFT زيرمجموعه اي از NFT ها را در 3 سطح تجزيه و تحليل مي کند :

1. اسکن اتريوم – اين اسکن به دنبال مواردي با همان CID در شبکه اتريوم مي گردد و صفحه اول يافته شده را به ما برميگرداند.

2. اسکن تصوير مشابه – اسکن از يک ماژول هوش مصنوعي براي جستجوي موارد مشابه در شبکه اتريوم استفاده مي کند و صفحه يافته شده مرتبط را برميگرداند. تفاوت اصلي بين اسکن اتريوم و اسکن تصوير مشابه اين است که اسکن اتريوم با CID محتوا مطابقت دارد، به اين معني که محتوا بايد دقيقا يکسان باشد.

3. گزارش جامعه – ويژگي بتا ورژن جديد. هنگامي که درخواست هاي جديدي وجود دارد آن ها را با اعضاي جامعه به اشتراک مي گذاريم و درخواست کمک مي کنيم. آن ها مي توانند موارد مشکوک را علامت گذاري کرده و نشاني اينترنتي را به عنوان مدرکي براي اثبات نقض حق کپي رايت (نسخه برداري) عکس ارائه دهند.

از طريق اين اسکن ها به اين نتيجه رسيديم که 97 درصد NFT هاي موجود در پلتفرم هاي Featured ، آثار هنري هستند که تازه خلق شده اند . ما از اين موضوع هيجان زده شديم، زيرا با ديدگاه مشخص مبني بر اينکه NFT ها براي همه هستند و نه فقط براي افراد ممتازي که مي توانند هزينه هاي بالاي گس را بپردازند، همخواني دارد .

همه NFT هايي که سه سطح اسکن را گذرانده اند اکنون در داراي يک علامت خاص در کنار عنوان خود هستند و اگر روي آن کليک کنيد، صفحه اي از Numbers Protocol باز مي شود که نتايج اسکن را ليست مي کند .

**تشخيص کلاه برداري API : NFTrade × Numbers**
در هفدهم دسامبر،Numbers  با NFTrade وارد همکاري شد تا باعث اعتبار بخشيدن به NFT ها شود. NFTrade دومين پلتفرم بزرگ NFT و اولين پلتفرم NFT بين زنجيره اي و چند بلاکچيني است. آن ها گردآورنده تمام بازار هاي NFT هستند و ميزبان چرخه حياط کامل NFT هستند و به هر کسي اجازه مي دهد تا به صورت يکپارچه NFT ها را در زنجيره هاي بلوکي مختلف ايجاد کند، بخرد، بفروشد، مبادله کند و فارم کند . 

ماموريت طولاني مدت Numbers  اين است که با کمک به نمايش گذاشتن رسانه هاي ديجيتالي ايجاد شده و انجام شده به شيوه اي غير متمرکز، تمرکز زدايي و تعامل Web3.0 را به خط مقدم برساند . از طريق کار کردن با NFTrade، NFT هاي منتشر شده توسط اين پلتفرم از طريق موتور جستجوي Web3.0 قابل جستجو خواهند بود و پوشش قراداد NFT ، موتور جستجوي Web3.0  را گسترش مي دهد.

**اپليکيشن بومي عکس Web3.0 : Capture App**

اپليکيشن Capture App هنوز تنها اپليکيشن دوربين بلاکچين در جهان است که به شما امکان مي دهد عکس هاي بومي Web3.0 ايجاد کنيد. اين ويژگي به کاربران اجازه مي دهد تا از هر عکسي که با استفاده از اپليکيشن گرفته شده است، يک NFT ايجاد کنند.

در حال حاضر مسائل زيادي در دنياي NFT وجود دارد بنابراين ما بايد راه حل هاي سازماني را براي پلتفرم هايي مانند NFTrade و Featured ارائه کنيم تا راه حل هايي براي افرادي که در Web2.0 عکس مي گيرند(بدون قابليت رديابي، بدون اثبات زنجيره اي ) ارائه دهد.
توکن هاي NFT منحصر به فرد هستند و در نوع خود بي نظير هستند، اما مي توانيد به تعداد دلخواه توکن NFT را از همان فايل ايجاد کنيد. اين بي معني است و مشکل دنياي Web2.0 را حل نمي کند.


به همين دليل است که برنامه Capture بسيار ارزشمند است. اين به همه کمک مي کند تا عکس هاي بومي Web3.0 قابل رديابي، با سوابق ثبت شده روي زنجيره ايجاد کنند و فايل ها به جاي سرور متمرکز در وب، غير متمرکز ذخيره شوند. 
اين عکس هاي بومي Web3.0  آن هايي هستند که واقعا در متاورس خواهند درخشيد زيرا قابل اعتماد و غير متمرکز هستند.

**درباره ي Numbers Protocol**
نامبرز (Numbers) در حال ايجاد يک شبکه عکس غير متمرکز براي ايجاد يک جامعه ، ارزش و اعتماد به رسانه هاي ديجيتال است.
نامبرز پروتکل (Numbers protocol) آن رسانه هاي تصويري ديجيتال را به عنوان دارايي بازتعريف ميکند وشاکله اصلي مجموعه اي از ابزارها براي ثبت و بازيابي تصاوير و ويدئو ها در شبکه Numbers است.

اين ها شامل :
**Capture App:** 
اولين دوربين بلاکچيني در جهان که کاربران به راحتي مي توانند در عکس ها را ثبت کنند و از کاربرد هاي Web3.0 استفاده کنند.
**Seal API (مهر و موم API):**
 توسعه دهندگان و شرکت ها مي توانند Numbers API را براي ثبت عکس ها و دسترسي به آدرس ها و گواهي هاي Web3.0 خود پياده سازي کنند.
**Certificates (گواهي ها):**
 گواهي هاي اصالت محتوا با منشا زنجيره اي.
 **Capture Club marketplace (بازار باشگاه Capture):**
 بازار بومي NFT که به توليد کنندگان عکس ها اجازه مي دهد آثارشان را بفروشند و يا استيک کنند.
**NFT Search Engine (موتور جستجوي NFT):** 

اولين موتور جست جوي NFT وب 3.0 که به کاربران کمک ميکند تاريخچه NFT ها را تاييد کنند و از کلاه برداري هاي بالقوه NFT جلوگيري کند.

نامبرز(Numbers) نشان دهنده خلوص و يکپارچگي رسانه هاي ديجيتال است و افراد را قادر مي سازد تا به طور انتقادي در مورد تعاملات بين تصاوير ما و دنياي اطراف ما فکر کنند . Numbers کدگذاري تصاوير بومي (از جمله تصاوير و ويدئوها) را براي ايجاد يک شبکه تصوير غير متمرکز در Web3.0 هدف قرار مي دهد .

**Comment by Zahra7613** [comment]
perfect

**Comment by Zahra7613** [comment]
very good
