### ISSUE TITLE
NFT Search - Create Broad, Similar, Exact Functionality  

### ISSUE THREAD

**Issue by willcoursen** [numbersprotocol/community-support#11]
It would be ideal to equip users with the ability to choose search criteria in order to educate them on what they are potentially going to buy (help to spot fakes) and understand the creative lifecycle evolution of an image, video, etc. 

IMO the broad or similar criteria would have to alow users to take snapshots of images (for example you cannot search on refineable because they are not PNGs, JPEGs)
![image](https://user-images.githubusercontent.com/17142178/146581845-e6850b78-5d3b-4030-9d11-adb0a6150230.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248721887204) by [Unito](https://www.unito.io)

**Comment by hr19990519** [comment]
是的 更多了解nft

**Comment by kennyhungQA** [comment]
This issue is no longer to be used; close it.
Currently, our NFT Search Engine is pivoting to a verification site.
