### ISSUE TITLE
Lazy minting creator error

### ISSUE THREAD

**Issue by web2hotel** [numbersprotocol/community-support#117]
**Describe the bug**
The creator field report the first collector's address instead of the artist's wallet.

**To Reproduce**
1. As an example download the pic of the sold token https://opensea.io/assets/0x495f947276749ce646f68ac8c248420045cb7b5e/76362692740077657979727001631053239549111897607345079925581875905041556045825
2. Upload on NFT Search
3. The response page already states the first collector Ethan1Elo... 0xa74d13042cb339adf749e4128dcb5f5f96645ba7 as creator 
4. By clicking S, NFT Scan page states the same error. 

**Expected behavior**
The creator field should give Tosca 0xa8d3c09ff20c1f8947e0ba3897a907c57945a401 as creator 
or, if not immediately possible, a warning for a correct data reading in case of lazy-minting.

**Select label**
please select label NFT Search Engine

**Additional context**
This behavior is probably due to the "lazy minting" feature introduced by Opensea and now possible on Rarible too. When the file is minted the moment of purchase.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248800189272) by [Unito](https://www.unito.io)

**Comment by kennyhungQA** [comment]
This issue is no longer to be used; close it.
Currently, our NFT Search Engine is pivoting to a verification site.
