### ISSUE TITLE
[Translation Demand in 12 Languages] New Wallet Page Landed In Capture App!

### ISSUE THREAD

**Issue by Charles7021** [numbersprotocol/community-support#119]
**[Translators Wanted!]** 

**The article:**
**[New Wallet Page Landed In Capture App!](https://medium.com/numbers-protocol/new-wallet-page-landed-in-capture-app-7407cc54438f)**

**Languages needed:** Japanese, Korean, Turkish, Vietnamese, Germany, Russian, Dutch, Norwegian, Indonesian, Polish, Persian, Spanish.

Become our Tier 1 Ambassador for #NUMARMY!

--
- How to participate:
> - Propose in comment in which language you would like to translate the article into, and we will open a new issue for you.
> - Translate **at least 1 paragraph of the selected article**.
> - **The translation should be done in the form of a comment for the issue**
> - **Share the link of the comment in the local community and get at least 3 likes on Github**. If there is no community for your language existing yet, find your Web 3.0 friends to come here to help review your work and like the comment.
> - If there are two comments linked to the same paragraph and both collect 3 likes, the earlier one wins.
> - The translation needs to be fluent and factually correct and should not be copied directly from Google translate or similar apps (any attempt to copy-paste directly from Google Translate will result in your dismissal from the Ambassador Program).

- Rewards
> - `10 NUM` per paragraph per language
> - Bounty-based, the selected article will be announced when it gets 3 likes.

**Comment by SNP0301** [comment]
Hi, I want to translate it into Korean.
I think I will translate from 'Q&A for Capture App’s March update' first.

**Comment by sofiayan0523** [comment]
Hi @SNP0301, sorry the tier 1 ambassador program has ended in May, the new program is on the way! Stay tuned!
