### ISSUE TITLE
Capture App: Implementing Dark Mode/Themes

### ISSUE THREAD

**Issue by KNctrl-alt** [numbersprotocol/community-support#12]
### Proposal:
1. Implement __dark mode__ for the app. 
2. Eventually add more __visual themes__ to choose from.

### Reason:
- Users don't have to strain their eyes during nighttime. 
- Also, the __dark mode__ can be a design choice for a lot of users.
- Adding more themes would bring customisability to the app by giving users the freedom to personalise it acccording to their unique personalities.

**Comment by tammyyang** [comment]
I believe the app already has dark mode implemented. It may be the settings of the system which affect it?

**Comment by KNctrl-alt** [comment]
- I am currently using **Android 7** so I cannot toggle system-wide dark mode (affecting every app in the system) because there is no such option (if you mean that by "settings of the system"). 

- A few moments ago, I tested in **Android 10** where system-wide dark mode is present, so it is possible to enable dark mode there. (but the app still had no option to do so).

So what I wanted was an option to toggle between dark/light modes from the app itself so that the older versions of the android phones (without system-wide settings) have that facility too.

**Comment by tammyyang** [comment]
@scott-dt  please confirm if this issue exists

**Comment by kennyhungQA** [comment]
Hi, @KNctrl-alt 
Thanks for your report.
In rebrand design Capture App, the dark mode is default, there is a better UI than before, you could try it.
