### ISSUE TITLE
Special Characters are not allowed

### ISSUE THREAD

**Issue by wiucha** [numbersprotocol/community-support#120]
#Hello I have an Issue with a telegram bot when I started him with python 3.10:

reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x1f310: special characters are not allowed
  in "settings.yml", position 518

#I want to add emojis in a message (example = message : | Hi 👍)

#I tried with: (example = message : | Hi "#x1f310") and the bot write the same as Hi "#x1f310".

#how can I solve this issue? Thanks you for your attention

**Comment by shc261392** [comment]
Could you provide the information:
- Which repository are you trying to use? (I think it might be [Telegram Archive Bot](https://github.com/numbersprotocol/telegram-archive-bot) but just to be safe please let me confirm again)
- What command did you use to setup/run the code?

**Comment by shc261392** [comment]
Sorry I don't think I can help because we don't own or maintain the repository you mentioned. Asking the repository author would be more helpful to you.
I'll close this issue for now since this is not within the scope of Numbers community support.

**Comment by wiucha** [comment]
How can I do it? He close issues from his script.
