### ISSUE TITLE
Correct portrait preview

### ISSUE THREAD

**Issue by web2hotel** [numbersprotocol/community-support#121]
The photos in their Capture Club page are badly cropped.

For example a photo taken in portrait mode is shown there without the above and bottom part.

The system should add vertical bars to portrait pics if CC has to show it in a 16:9 placeholder in that page. 

Also the previous page https://captureclub.cc/about shows strange previews but it's less important.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248716215523) by [Unito](https://www.unito.io)

**Comment by kennyhungQA** [comment]
CaptureClub is no longer supported. We welcome you to continue experiencing the seamless Web3 experience provided by Numbers Protocolo through [Capture Dashboard](https://dashboard.captureapp.xyz/). Close this issue.
