### ISSUE TITLE
After a capture, there's no feedback or preview of the same. The end result is shown only after refreshing and going back to the gallery.

### ISSUE THREAD

**Issue by MdRehan05** [numbersprotocol/community-support#125]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Capture App (please complete the following information):**

**Select label**
Based on the issue category, please select a label from General/Capture App/NFT Search Engine/CaptureClub

**Additional context**

**Comment by kennyhungQA** [comment]
Hi, @MdRehan05 

In new version of Capture App, you could preview the photo you take, and confirm it, then it will be registered on blockchain.
