### ISSUE TITLE
 [Need clarify] Add time mode

### ISSUE THREAD

**Issue by MdRehan05** [numbersprotocol/community-support#126]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248742183323) by [Unito](https://www.unito.io)

**Comment by kennyhungQA** [comment]
Hi, @MdRehan05 
Thanks a lot for leaving this issue.
Could you have more detail about these three features you want to have?

1. Different screen ratios
2. Time mode
3. Preview capture

Thanks a lot for your help again.

**Comment by kennyhungQA** [comment]
Hi, @MdRehan05 

Thanks a lot for leaving this issue. 
Regarding the time mode feature, could you please provide us with more details or clarify what specific aspect of the feature you would like to know more about? 
This will help us address your inquiry accurately.

We appreciate your patience and look forward to assisting you further.

Best regards,
Kenny Product Team

**Comment by kennyhungQA** [comment]
Hi, @MdRehan05 

Thanks a lot for leaving this feature request.
Regarding the time mode feature, could you please provide us with more details?
This will help us address your inquiry accurately.

We appreciate your patience and look forward to assisting you further.

Best regards,
Kenny 
Product Team

**Comment by ethanwu155** [comment]
Hi. Appreciate you taking the time to submit this request. Given the lack of details and clarification, we have decided to close this ticket. If you would like to see this issue addressed by our team, please resubmit this request with more details. Thanks!
