### ISSUE TITLE
Capture App crashes unexpectedly

### ISSUE THREAD

**Issue by tammyyang** [numbersprotocol/community-support#129]
**Describe the bug**
Capture App crashes unexpectedly

**To Reproduce**
1. Open Capture App
2. Wait for 3-5s until the main page is loaded
3. It crashes and go back to my mobile home screen

**Expected behavior**
Can use the App without any problem

**Screenshots**

https://user-images.githubusercontent.com/5687908/198185954-9377a3bb-f2e1-4c1c-96b6-24c97fe4f001.mp4

**Capture App (please complete the following information):**

**Select label**
Based on the issue category, please select a label from General/Capture App/NFT Search Engine/CaptureClub

**Additional context**
This is reported by the community member, @enjoybro143 in the captain channel

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248799811797) by [Unito](https://www.unito.io)

**Comment by enjoybro143** [comment]
All details is here from 2 users.

Thanks for your support ;)

**Comment by enjoybro143** [comment]
Hi team 

We are still facing crash problems in the capture app on All Android 12 Phones
