### ISSUE TITLE
Capture App: Introductory UI/UX for new users.

### ISSUE THREAD

**Issue by KNctrl-alt** [numbersprotocol/community-support#13]
### Proposal:

There should be well designed 'Welcome' slides for a user when the app is opened for the first time / is not logged in.
- It should provide an intro to the Capture App and its capabilities.
- It should include phrases like `the world's first blockchain camera`,  `mint nfts with just one click` and also about `offers` like `mint free NFTs till December 31st` etc. 

### Reason:
- Follows from the idea that _"First impression is the last impression"_
- There is a great chance that the user is new to decentralised software, web3.0 and may not be aware of these initiatives in general.
- This provides the user with the preliminary but exciting feel of this new revolution of authenticity in digital media. 
- The user should get a lot of the recent news relating to the app from the app itself without needing to go to other sources.

**Comment by tammyyang** [comment]
Scheduled in the next sprint.

**Comment by kennyhungQA** [comment]
Hi, @KNctrl-alt 
On rebrand version of capture app, there is a new tutorial page. It displays new features like collecting NFTs for users.
