### ISSUE TITLE
Capture App: Precautionary prompt for handling of wallet's private key

### ISSUE THREAD

**Issue by KNctrl-alt** [numbersprotocol/community-support#14]
### Proposal:

There should be a __cautionary prompt__ for users when they are copying the private key. The prompt should describe that private key is sensitive information and should be stored carefully. 

### Reason:

- For better security.
 
### User story:  
 
_A user didn't handle the copying of private keys with caution and stored the keys in plain text somewhere in device. It is later accessed by someone with malicious intent who proceeds to import that wallet as a non-custodial wallet, getting the funds in the wallet as a result_.

**Comment by web2hotel** [comment]
Also, a notification email should be delivered every time the private key is tapped.

**Comment by tammyyang** [comment]
This has been fixed in the 0.49.1
