### ISSUE TITLE
Capture App: Wallet should be separated from the Profile tab to a Wallet tab

### ISSUE THREAD

**Issue by KNctrl-alt** [numbersprotocol/community-support#15]
### Proposal:
 
The wallet credentials (wallet address and private key) to be placed in a __separate tab__ called `wallet` outside of `profile` tab in the menu.

### Reason:

- It will be a better choice to separate the _web2 credentials_ (email, phone number, password)  and _web3 credentials_ (wallet address, private key) in different tabs from the get-go so that later in a case where web2 credentials are no longer needed, it ( `profile` tab) can easily be removed without causing much confusion. It will also lead to user awarness of the decentralised nature of web3 from the very start.

___From a user experience perspective, the following user story can be considered:___

_A user receives notification that one of his capture NFT was sold in Capture Club. In order to check if the funds have arrived he is more likely to navigate to the `wallet` tab._

**Comment by web2hotel** [comment]
And the private key should be hided by default, in any tab.

**Comment by kennyhungQA** [comment]
Hi, @KNctrl-alt @web2hotel 
In the current version of Capture App, there is wallet page in the menu, it will show the user's wallet, and the private key is hidden by default.
Thanks for your report.
