### ISSUE TITLE
Capture App: Profile should retain the user privacy settings

### ISSUE THREAD

**Issue by ghost** [numbersprotocol/community-support#16]
### Proposal:

The privacy settings in the app should be retained when logging in and out of the profile.

### Reason:

User experience improves if the users don't have to set their preferred privacy settings every time they login to the app after a logout.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248806783949) by [Unito](https://www.unito.io)

**Comment by kennyhungQA** [comment]
Merge this issue in product backlog.
