### ISSUE TITLE
User experience 

### ISSUE THREAD

**Issue by Cryptonum** [numbersprotocol/community-support#164]
some points about capture App(user experience) :

1- I can't delete the picture has been taken.

2- there's no option to add effects on the photo

3- the App isn't smoothly move between window to another.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203373277823827) by [Unito](https://www.unito.io)

**Comment by scott-dt** [comment]
Thank you for your feedback regarding the Capture App user experience.

We have recently released an update that addresses several of the issues you mentioned. Please update your Capture App to the latest version and try it again. Specifically:

The update now allows you to delete pictures that have been taken.
While adding effects to photos is not yet available, we are actively working on this feature for a future release.
We have made improvements to ensure smoother transitions between windows within the app.
We appreciate your patience and support. Please try the updated version and let us know if you have any further feedback.
