### ISSUE TITLE
Add the word "Videos" to the brand bec people are thinking that NUM project & Capture app is only for "Photos"

### ISSUE THREAD

**Issue by sicnarf9999** [numbersprotocol/community-support#172]
Add the word "Videos" to the brand bec people are thinking that NUM project & Capture app is only for "Photos"

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203423984134938) by [Unito](https://www.unito.io)

**Comment by scott-dt** [comment]
Thank you for your valuable suggestion.

We have taken your feedback into consideration and made adjustments to our branding descriptions. The word "Videos" has been added to ensure it's clear that the NUM project and Capture App support both photos and videos.

We appreciate your input and support.
