### ISSUE TITLE
CAPTURE CLUB :: PROBLEMS WITH PUBLICATION FORM

### ISSUE THREAD

**Issue by JAVIERCE31** [numbersprotocol/community-support#182]
**Describe the bug**
I am a user of the CaptureClub website. I've been uploading my photos for a few weeks so I can sell them and I've also bought some from other users.

From the beginning I have had problems with the uploads, most of them do not end up being published even if the Fee has been charged to me. I have never managed to post more than 2 photos in a row, not even changing browsers, clearing cache, etc.

With this problem I will have lost about 100 $NUMS between all the failed attempts.

Now, I see that the number of Issue (1 - 100) is not working. No matter the number of copies indicated, only 1 copy is always published.

It would be interesting if they reviewed the upload form and added the corresponding validations to the input fields so that users know what errors are occurring.

Thank you very much for your attention. I await the news.

All the best.

**Expected behavior**
It would be interesting if they reviewed the upload form and added the corresponding validations to the input fields so that users know what errors are occurring.

**Screenshots**

**Select label**
CaptureClub

**Additional context**

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203443319948952) by [Unito](https://www.unito.io)

**Comment by JAVIERCE31** [comment]
Hello again,

I keep trying to post my photos, but now it's totally impossible. The process always stays on the same screen (attached screenshot) regardless of the browser you use or the time of day you carry out the process.

Of course, always charge the Fee!!

Please could you tell me what to do?

Awaiting your comments.

![Captura de pantalla_20221205_183900](https://user-images.githubusercontent.com/119164748/205705496-c59d77f7-a69c-48d9-8449-b4bcd8d04498.png)
![Captura de pantalla_20221205_184059](https://user-images.githubusercontent.com/119164748/205705501-adfc54cd-95ad-4230-abf6-abbfd8ddfc84.png)

**Comment by sofiayan0523** [comment]
hi @JAVIERCE31 

Thank you for your feedback. The dev team is migrating the CaptureClub to Capture App. Sorry for the inconvenience during the transition period.

According to the backend and on-chain records, 56 of your products have been successfully listed on CaptureClub, and the latest order was on Nov. 29, can you remember how many uploads failed to list and when the issue started?

Unfortunately, CaptureClub now can not let users check the listing process, but if you use Capture App to do the listing, you will be able to check the order in the app :)

**Comment by JAVIERCE31** [comment]
Hi @sofiayan0523 

The problem of uploading the photos comes almost from the beginning, I estimate that about 30 attempts were unsuccessful and charged.

But for the last 2 weeks, more or less, all the attempts have been unsuccessful, I estimate that about 10.

Sorry I can't give specific figures.

Thanks for your interest. I await news.

All the best.

**Comment by JAVIERCE31** [comment]
Hello again,

Hello again,

This is going from bad to worse. I have just uploaded 2 new photos, this time they have been uploaded, but they have not been assigned their NFT Token and are not showing in the public gallery.

https://captureclub.cc/asset?mid=bafybeie42ofq4uc4vju653zsawmteeoill3jaftdyilwowkuiydaq5ygve

![image](https://user-images.githubusercontent.com/119164748/206924357-ceb56dcc-71f6-45ee-865a-7b76fe513599.png)

https://authmedia.net/asset-profile?cid=bafybeie42ofq4uc4vju653zsawmteeoill3jaftdyilwowkuiydaq5ygve&token=mpK3XhqI8bKDFotx79UeuJNBFXHn-2Ks_9krA70DZmw

**I have been involved in your project from the beginning because I have believed in it. I have invested a significant capital and I have dedicated time to carefully select and publish my photos, but I am beginning to have many doubts.

It would be interesting for you to review the logs and traces of my connections and activity in captureclub.cc and identify all the NUMs that I have spent unsuccessfully on your service.**

I remain attentive to your comments.

All the best.

**Comment by sofiayan0523** [comment]
Hi @JAVIERCE31 ,
The dev team is checking on all orders you've made before. It may take some time. 
Please temporarily pause uploading until the issue has been checked :)

Apologize for the inconvenience during the migration period, we will make corresponding compensation after the order checking. And also improving the order status for the uploading feature in the upcoming developing process.

**Comment by sofiayan0523** [comment]
Hi @JAVIERCE31  
Sorry to keep you waiting, the issue has been fixed, and you can now try to upload your creations again :)
If the problem is still happening from your end, please pause the action and let us know.

We checked all your orders and found 38 failed listings during the migration period, we've sent 1500 NUM as compensation to your Capture account. Again, apologize for the inconvenience, and thank you for your support to the platform :)!

**Comment by JAVIERCE31** [comment]
> 
Thanks a lot!
I will try to reload and update the status.

I greatly appreciate your involvement.

Many thanks again.

**Comment by JAVIERCE31** [comment]
> 
Hello again,
It seems the same thing is still happening. When the Asset is created, the process freezes and it is necessary to refresh the page (after 30 minutes).
The file has been uploaded, but the Token is not assigned to it.

https://captureclub.cc/asset?mid=bafybeicqkij3ae3yb5cqhxeepk4nz23vswf3qkwqppyyeou64ggvkkka4y

![image](https://user-images.githubusercontent.com/119164748/208645802-65652bec-e77a-42f0-87fb-a73a7e114e4a.png)

Certificate: https://authmedia.net/asset-profile?cid=bafybeicqkij3ae3yb5cqhxeepk4nz23vswf3qkwqppyyeou64ggvkkka4y&token=sWFLcMKTNHoWjHq64n7iYKQYV4RwFSddJe2jgA_GrJs

Sincerely, Javier.

**Comment by sofiayan0523** [comment]
Hi @JAVIERCE31 
Do you have Capture App? If so, please log in Capture App with your Capture account, once your upload and mint process on CaptureClub is done, App will show a notification, and it will take around 10-15 mins to reflect on the store. Sorry since we're migrating CaptureClub and Capture App, it might be a bit inconvenient to see the process on CaptureClub.

And for your reference, to ensure the uniqueness, Numbers network only accepts images registered once, which means if the image has been uploaded and registered before, it can not be uploaded and registered again. 

If possible, please record the screen next time when you bump into the same problem, it will be very helpful for our dev team to reproduce the problem :)

**Comment by JAVIERCE31** [comment]
Hello,

I close this ticket because I see that there is no solution.

All the best.
