### ISSUE TITLE
Cannot mint and credits being depleted

### ISSUE THREAD

**Issue by ThePictureMan** [numbersprotocol/community-support#192]
3 issues:

1. I am unable to mint a photo to the blockchain through my creator gallery on the capture club website. I just get a never ending pickaxe pop up and credits are deducted from my account. 

2. Also, my credit balance only shows up on the capture app and not the capture club website. 

3. I tried to send funds to the capture app asset address through the ETH network from Coinbase wallet and although the address was correct to send to the ‘asset wallet’ in the Capture app my funds never arrived.

![305E4879-CB09-4AD5-9062-78EAE88C3EAE](https://user-images.githubusercontent.com/120120096/206497586-ce9365a8-8c8a-48c0-a62d-8102c8a59d12.jpeg)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203517200373598) by [Unito](https://www.unito.io)

**Comment by sofiayan0523** [comment]
hi @ThePictureMan 
Hi, thank you for reporting the issue, and sorry for the inconvenience caused. Since this may relate to the credits in your personal account and wallet, can you please help us fill out the [form](https://link.numbersprotocol.io/issue-report) so that I can provide you with further assistance? Thank you!

**Comment by scott-dt** [comment]
We are excited to inform you that the Capture Club team has undergone significant updates and has been rebranded as Capture Dashboard. You can now experience a smoother user experience on the new Capture Dashboard platform at https://dashboard.captureapp.xyz/. We look forward to you enjoying the updated features and services.
