### ISSUE TITLE
TOKEN BUYED  BY POOCOIN 

### ISSUE THREAD

**Issue by CavalierMax** [numbersprotocol/community-support#2]
good morning who can I talk to since I invested a lot and for your problem on the pool with poocoin I have not received practically anything? I invested in the listing 1.5 bnb and I received 0.67 tokens ..... The problem is that you put the liquidity too late and the tokens never arrived.

**Comment by ethanwu155** [comment]
This channel is to discuss issues related to the project itself. If you have any token related issues, please direct your inquiries to Telegram or Discord Channels. 

TG: https://t.me/numbersprotocol

Discord: https://discord.com/invite/KBtfEpxd3Z
