### ISSUE TITLE
Capture App: Captioning captures inside of app, and searching captures using text in captions [FR]

### ISSUE THREAD

**Issue by ghost** [numbersprotocol/community-support#23]
### Proposal
1. Enabling the users to have the opportunity to "caption" their captures within the Capture app.
2. Providing a search mechanism to search for captures using the text in the caption.

### Reason
* Captioning is provided with listed captures at the moment, however, it is not yet in the Capture app. 
* It provides an area to put one's ideas or thoughts together right after they capture a new media. 
* It can also help with the retrieval of media by searching the text of the caption. (through a search mechanism as given in the proposal)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248747775671) by [Unito](https://www.unito.io)

**Comment by tammyyang** [comment]
The caption feature will come in the next release. Will need a bit more time for the search mechanism.

**Comment by KNctrl-alt** [comment]
Thank you @tammyyang for the response. Glad to know that it is coming up. I was away for a while and I forgot about the bounty being over. Anyways, gonna check out the new issues.

**Comment by ethanwu155** [comment]
We are pleased to share that Captures can now have both a Headline and an Abstract (caption). Thank you for sharing your feature request. Let us know what you think and if you have any issues feel free to let us know.
