### ISSUE TITLE
Consider to set some equipments which link the numbers blockchain

### ISSUE THREAD

**Issue by Crypto0xAugust** [numbersprotocol/community-support#257]
Nowadays, more and more offline campaigns use NFT tickets to participate, which is a scenario to show Web3 things to Web2 users. I think that no matter GameFi or SocialFi, we are not going to replace them, but gradually educate them.For example,  Web3 users buy the NFT tickets at the same price and have more interests than their tickets (such as partner IP NFT, resale of ticket stubs, future rights and interests, etc.). So will they be willing to take the initiative to enter us. Of course, the premise of this is that buying and checking tickets is the same convenient as traditional mode. Therefore, the NFT platform should take into account the layout of terminals equipments, and to extend the Web3 brand to life. For us, we can deploy more equipment at the current event site to give tourists a one-stop serve "capture - minting - listing". This new Web3 experience will naturally enter the lives of people, and then we can extend to Disneyland, the scene of the E-sports competition, and so on.
----------------------
现在越来越多的线下活动使用 NFT门票 来参与，这是一种向 Web2 用户展现 Web3 的场景。我一直觉得无论是 GameFi 也好，SocialFi 一样，我们并不是要去取代他们，而是慢慢浸入他们。只有和 Web2 的用户处在同一个场景下，当我们 Web3 的用户用差不多的价钱买到的 NFT门票 比他们的门票拥有更多的Web3权益（比如联动的NFT、票根的再出售、未来权益等等），他们才会愿意主动走进我们。当然这的前提条件是，购票和验票的便捷程度要与Web2 差不多，因此相关的 NFT平台 应该考虑到线下终端的布局，比如在会场设有购票的设备、验票的设备以及打卡的设备，将品牌延伸到生活中。对我们来说，我们可以部署更多的设备在现在活动的现场，给游客一种感受一站式的“拍照-铸造-上架”的感觉，这种新的Web3体验就很自然的进入到普通人的生活中，之后我们可以延伸到迪士尼乐园、电竞比赛现场等等。

@tammyyang @sofiayan0523 

![AAAA 002](https://user-images.githubusercontent.com/99540388/224529639-02a8d455-785c-4974-9c5b-247674ec85ab.jpeg)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1204159907492634) by [Unito](https://www.unito.io)

**Comment by scott-dt** [comment]
Thank you for sharing your insights and suggestions regarding the integration of NFT tickets and the promotion of Web3 technologies.

While we appreciate the potential of such collaborations and the value they could bring, our current focus and goals do not align with this direction at the moment. However, we do not rule out the possibility of exploring such initiatives in the future as we continue to evolve and expand our platform.

Thank you for your understanding, and we appreciate your continued support and interest.
