### ISSUE TITLE
Report suspicious Transaction on the Blockchain 

### ISSUE THREAD

**Issue by Lasheron** [numbersprotocol/community-support#264]
It has come to our attention that a few members of our community have reported observing suspicious transactions on the blockchain. As a responsible and committed team, we take this matter seriously and are initiating a thorough investigation into these transactions. We encourage all members of our community to remain vigilant and report any similar observations. Rest assured, we are fully committed to ensuring the integrity and security of our platform, and we will leave no stone unturned in our efforts to address any potential issues.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1204357373260995) by [Unito](https://www.unito.io)

**Comment by PlzDontScamInvestors** [comment]
Hello

If the project is experiencing very low prices today, it is for one reason: There are a few wallets selling huge sums. Today 30,000,000 tokens have been released to 5 different addresses:

0x7af3be40f5778c44d24a4d8e73a7d8ed392c1dfe
    0x0a21e0a2d1307c91ff6dd15a712c52bd0eed8a88
       0x0a21e0a2d1307c91ff6dd15a712c52bd0eed8a88
        0x1c962a4d7cea63f23355f72e398782584c9e50b2
             0x23ffced28621fbbb29bf671eaf2cf57944985834

In the last few weeks, these same wallets have sold tens of millions of tokens on the market as you can see in the outgoing transactions of these wallets.

Who owns these addresses? Such quantities can alert investors to the reliability of the project. What is your answer?

**Comment by PlzDontScamInvestors** [comment]
i wish i can directly tag Tammy and Sofia, but it seems i'm not alowed to on the Telegram channel, contraty to the last months?

**Comment by tammyyang** [comment]
Hi,

The wallets you're referring to are distribution wallets as have been reported to platforms like Coingecko and Coinmarketcap. NUM tokens are minted monthly following tokenomics and are moved to the distribution wallets prior to being distributed. Transactions from these wallets don't necessarily imply that tokens have been sold.

In fact, the majority of tokens from these wallets have not been sold, except for a small portion (valued at around $20,000 USD) that went to private-sale investors in the last two months. Even so, most of the private-sale investors are still holding their tokens without selling.

It's important to remember that our community discourages accusations without substantial evidence. Based on your comments, I don't see any concrete proof supporting the claim that "tens of millions of tokens were sold". On the other hand, I have gathered evidence from our private-sale investors which suggests that no tokens have been sold on their part.

We greatly appreciate your vigilance and concern. It's this level of care that helps our community grow.
