### ISSUE TITLE
FAQ update request

### ISSUE THREAD

**Issue by tammyyang** [numbersprotocol/community-support#278]
Numbers FAQ page: https://docs.numbersprotocol.io/introduction/faq

Got questions about the Numbers Protocol? We want to hear from you! Ask anything, big or small, and help shape the future of our community FAQ. Your voice matters, and we're here to help. Submit your questions now!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1204439947633516) by [Unito](https://www.unito.io)

**Comment by bafu** [comment]
What is digital media provenance, and why is it important to me?

**Comment by vera-numbers** [comment]
Can I do the registration on behalf of my fav creators or artists ?

**Comment by bafu** [comment]
How can I know if a digital media provenance is trustworthy?

**Comment by bafu** [comment]
I find a fantastic creation! How can I get a license to use it properly?

**Comment by sultanmyrza** [comment]
Is numbers infrastructure ready for Justin Bieber effect?

[Instagram started with Django back in 2010 as their go to tech stack.](https://www.linkedin.com/pulse/instagram-scales-python-2-billion-daily-users-shrey-batra) 

In the early days of Instagram, whenever Justin Bieber posted content that received millions of likes, it caused a heavy load on Instagram's servers. This situation led to many problems, and memorizing Justin Bieber's user ID became a temporary requirement for Instagram Dev Ops Team. Every time he made a popular post, it turned into an operations emergency that required all hands on deck.

Regarding Numbers Protocol, if asset registrations were to skyrocket, would the Numbers infrastructure be able to handle the increased load?


>There was one problem: Justin Bieber. The sharding was done based on user. So one user’s data was stored on just one shard. So when Justin Bieber posted something and the entire world liked it…. that shard got very very busy :-) [Read more](https://reinout.vanrees.org/weblog/2016/11/04/instagram.html)

> Tobias: There were humorous insights, like the Justin Bieber effect. Originally they’d sharded their database by user ID, so everybody on the ops team had memorized his user ID to be prepared in case he posted anything. At that scale, maximizing the number of requests they can serve from a single server really matters. [Read more](https://www.caktusgroup.com/blog/2016/11/29/django-under-hood-2016-recap/).

**Comment by Cheerock** [comment]
Is Numbers blockchain environmental friendly? any act on sustainability?

**Comment by Cheerock** [comment]
What should I do when I notice someone else register my creations?

**Comment by Cheerock** [comment]
Does Numbers work with any regulation party to get the provenance more legit?

**Comment by Cheerock** [comment]
How do I ensure the eternal access to my asset & provenance data?

**Comment by sofiayan0523** [comment]
When I register my work on Numbers Blockchain, does it also cover the storage?
If so, after the registration, can I change the way of the storage?
and does the storage fee contain in the registration fee?

**Comment by sofiayan0523** [comment]
Can my registration info be shown on social media platforms?

**Comment by sofiayan0523** [comment]
How can I share my registration info if I want to claim the author is me?

**Comment by kennyhungQA** [comment]
What does the difference between an NFT collected from explore page & gift a capture?
