### ISSUE TITLE
[Community Review] New NUM Burning Formula

### ISSUE THREAD

**Issue by sofiayan0523** [numbersprotocol/community-support#283]
### Overview
In March, the Numbers community voted to amend the NUM token burning mechanism and adopt a _**transaction-based burn mechanism**_. Two months later, we are revisiting the topic again and calling upon the community to provide their input and expertise on the burn mechanism formula. As usual, the Numbers Protocol team will initiate the discussion with a preliminary proposal and justification. We want the community to feel comfortable offering their thoughts and feedback on the NUM burn formula topic, as it dramatically affects the NUM token and the Numbers network. 

### Proposal
When developing a transaction-based burn formula, we need to decide if we want to base burns on network fees or the number of transactions. When coming up with formulas, it is easy to get caught up in incorporating various metrics like projected quarterly growth and other adjustable metrics. For this first transaction-based burn formula, we favor adopting a more straightforward formula based on the number of transactions. The following is the proposed quarterly burn formula:

**_`N_burn = min(max(N_transactions, 6M), 25.5M)`_**

In summary:
- Quarterly transactions amount to less than 6M. We burn 6M
- Quarterly transaction amount to greater than 6M but less than 25.5M. We burn the amount based on the transactions
- Quarterly transactions greater than 25.5, we burn 25.5M

With these projected values, our burn projections will be the following:
- 25.5M burned per quarter => 5 years to achieve 50% of all NUM (500M)
- 6M per quarter => 20 years to achieve 50% of all NUM (500M)

Previous quarterly NUM burns have amounted to approximately 2M NUM burned per quarter. This ensures a minimum of 6M NUM is burned per quarter, a threefold increase from our original burn formula. If we manage to reach 25.5M transactions per quarter, it will be a **_20-fold increase from our original burn formula_**!

The concern now becomes, is it possible to achieve high enough transactions to make this burn formula feasible? With **_over 1 billion images_** being shared on social media daily, the volume of digital assets circulating online is immense. Our vision is to facilitate an internet with enhanced provenance, where every asset is registered and its origin is traceable. As the adoption of the Numbers platform increases, we anticipate a significant surge in transactions. Besides, the digital media evolution has created a need for a way to **_track content provenance and distinguish between human and AI-generated content_**. 

Numbers Protocol aims to fill the needs of modern digital media by providing solutions based on web 3.0 technology and principles. With serving all digital media as the goal, it is reasonable to assume that Numbers Blockchain can achieve high quarterly transaction volume on the level of established projects such as Ethereum, which has 1M daily transactions amounting to 30M transactions monthly as every asset registration will equate to a transaction. Transactions will also include in-network actions such as updated content history, NUM transfer, and NFT minting.

High transaction volume on the level of projects such as Ethereum is what all worthwhile blockchains should strive to achieve as it reflects the project's value. The team at Numbers firmly believes in our value to the digital media and web 3.0 space. Given how prevalent digital media is and how much is created daily, it is not far-fetched to think Numbers Protocol can achieve equivalent or greater transaction volume in the future to established projects like Ethereum if we achieve full adoption.

### **Call to Action!**
At the last community review, some users voiced their concern about the slow rate of burn NUM, and some even suggested raising the NUM to burn threshold to 20 times its current rate. While some also warn us of the instability that deflation will cause. We acknowledge both points and conduct extensive brainstorming on how to tackle this problem best. Today, we deliver the finished formula to the community, encompassing the community's desire to burn up to 20 times the original formula while maintaining the stability of our circulating token.

At Numbers Protocol, we firmly believe in the power of community participation and feedback. This topic is super important as it dramatically affects NUM token and the Numbers network. We are proud to have our community contribute in meaningful and impactful ways. Let us know what your thoughts and questions are. If you have your own insights and suggestions on the NUM token burn formula, we are all ears! 

### About [Numbers Protocol](https://numbersprotocol.io)
Numbers Protocol is a digital media library and indexing system that aims to provide a more transparent outlook on digital media. It starts with Numbers ID (Nid). Every piece of digital media registered with Numbers Protocol is given a unique identifier that can be called upon to access digital media files on decentralized storage and digital media information archived on the blockchain.

Powering Numbers Protocol is the [Numbers Blockchain](https://youtu.be/LPTddpjfvs4). Numbers Blockchain facilitates the core functions of Numbers Protocol, mainly the archiving of committed media history of Web3 assets. [Numbers Blockchain ](https://youtu.be/F-bGHIYwpRE) changes digital assets from untraceable and unverifiable entities into standalone entities capable of “speaking” for themselves through accessible and transparent records. Numbers Blockchain achieves this by generating a unique digital media identity, also known as the content ID in the Filecoin/IPFS ecosystem. Essential information such as on-creation metadata (location, timestamp, and other data regarding creation circumstances), creator information, asset changelogs, and licenses are stored on the blockchain to assure the integrity of the digital media.

Numbers Protocol and Numbers Blockchain works in tandem to allow users to own and control their assets through decentralized and blockchain-backed digital assets. 

### Understanding [NUM Token](https://num.numbersprotocol.io/)
NUM is the native protocol token for the Numbers Protocol Decentralized Photo Network and transacting token of Numbers Blockchain. As a utility token, NUM holders can utilize the token to pay network fees (gas) and services within the network. These services, which we refer to as Network Actions, include asset registration, listings onto in-network or out-of-network marketplaces, storage onto robust forms of decentralized storage, and much more. As the Numbers ecosystem develops, the number of Network Actions will increase and stretch into other areas, such as social media, news, gaming, and entertainment.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1204577611399740) by [Unito](https://www.unito.io)

**Comment by PlzDontScamInvestors** [comment]
Congrats to the team, that's a significant raise of the tokens burn. Last burn it was <1m next burn will be at least 6M. Now you guys need to communicate a lot about that. But glad to read that change.
