### ISSUE TITLE
Capture crashing

### ISSUE THREAD

**Issue by TylerDylan** [numbersprotocol/community-support#290]
I'm always frustrated when I try to take captures using the capture app

The capture app crashes anytime I try to take photos or click the central camera icon. It's really frustrating as I have to log into another device to take captures with my phone

I would love the team to look into this and improve compatibly of the capture app to all device as I've noticed it happens to most other devices too

I think the team could improve device compatibility and help resolve this by carrying out multiple device tests

Capture App

Overall, the app is a great app

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1204752205342797) by [Unito](https://www.unito.io)

**Comment by ethanwu155** [comment]
Hi @TylerDylan.

Thanks for sending the ticket! I would like to first apologies for the inconveniences you are experiencing with Capture App and understand the frustration you have with not being able to operate the camera. I will let you know that the team is aware of the camera issues and are working hard to resolve the stability issues.

Capture App's camera was created in-house (coded by ourselves). This allows us to have more custom behavior with the drawback of having some stability issues when it comes to certain phone models / devices. Our Devs and QA are working diligently to identify these issues and resolve them. We have already resolved some issues related to Oppo and Redmi devices. You should see these changes in the upcoming deployment of Capture App. 

It would be supper helpful if you can provide us with some details such as device, model, OS so we can try to test these locally and try to reproduce the issues.

Thanks for taking the time to fill out the support ticket.

**Comment by kennyhungQA** [comment]
Hi, @TylerDylan 

Thanks for your reporting.
The latest version 0.79.0 has been published, and it includes fixes for the camera crash issue.
We encourage you to update to [the latest version](https://link.numbersprotocol.io/CaptureApp).
If you encounter any further problems, please provide us with relevant information and details about the issue.
We appreciate your patience and understanding. Thank you once again for waiting.

Best
Kenny Product Team
