### ISSUE TITLE
Fun activity 

### ISSUE THREAD

**Issue by Defiareana** [numbersprotocol/community-support#291]

**Comment by ethanwu155** [comment]
Hi @Defiareana.

Thanks for leaving your suggestion. 

Incorporating some gamification aspects (such as the daily login rewards / weekly login rewards) is something that our team has discussed in the past. We agree that this can provides more casual users with a good incentive to utilize Capture App. 

Whether or not we will be adding this feature into Capture App requires some discussion. Currently our focus as a team is Generative-AI and ensuring existing tools like Capture App and any other future products are capable of registering assets in a diverse and of course reliable manner. That is why you will find a lot of recent updates are geared towards product stability.

That being said, it doesn't mean this feature will not see the light of day. If there is enough demand from the community and if it makes sense schedule-wise (doesn't conflict with current goal / direction) we may implement a feature like you describe.

As with any product feature or request, our team will add it to the product backlog and of course discuss internally where it fits in with our roadmap. If this item makes it into our future sprints we will definitely inform you and the community.

In the meantime, if you can provide some interesting ideas regarding gamificaiton / incentives that would be great!

Thanks again for your comment!
