### ISSUE TITLE
Photo upload

### ISSUE THREAD

**Issue by enjoybro143** [numbersprotocol/community-support#294]
Can't able to upload,  photos in capture app

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1204772996340448) by [Unito](https://www.unito.io)

**Comment by kennyhungQA** [comment]
Hi, @enjoybro143 

Thanks for sending the ticket! I would like to first apologies for the inconveniences you are experiencing with Capture App.

Our Devs and QA are working diligently to identify the issues of Capture App and resolve them. 
It would be super helpful if you can provide us with some details such as device, model, OS so we can try to test these locally and try to reproduce the issues.

Thanks for taking the time to fill out the support ticket.

Kenny Product Team
