### ISSUE TITLE
[FR] Local Versioning System for Unregistered Assets

### ISSUE THREAD

**Issue by letsdrivethefuture** [numbersprotocol/community-support#295]
**Expectation**

Users can chronicle their assets locally, and when ready, they can commit these changes to the blockchain.

As per the current design of the Nit tool, assets need to be registered on the blockchain to be made traceable and trustworthy. However, there might be instances where users have digital assets that they do not wish to register immediately on the blockchain due to cost considerations or other reasons. In such cases, implementing a local versioning system, similar to how Git allows changes to be tracked before they are pushed to a remote repository, could be beneficial. This would give users the flexibility to manage their digital assets while maintaining a certain degree of traceability. Users can chronicle their assets locally, and when ready, they can commit these changes to the blockchain.

**User story**

As a user, I want to be able to chronicle my assets locally, so that I can make changes and updates to them before committing those changes to the blockchain.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1204785127463694) by [Unito](https://www.unito.io)

**Comment by kennyhungQA** [comment]
Hi, @letsdrivethefuture 

Thanks for leaving your suggestion. 

Incorporating some gamification aspects (such as the daily login rewards / weekly login rewards) is something that our team has discussed in the past. We agree that this can provide more casual users with a good incentive to utilize Capture App. 

Whether or not we will be adding this feature into Nit requires some discussion. Our team will add it to the product backlog and of course discuss internally where it fits in with our roadmap. If this item makes it into our future sprints we will definitely inform you and the community.

Thanks again for your comment!
