### ISSUE TITLE
Bug capture camera app android

### ISSUE THREAD

**Issue by carlosfoces** [numbersprotocol/community-support#3]
Hello I have android phone lg g8s and I have a problem with caputure camera app from Numbers. When I going to use my camera roll on storage and upload to the app. In doing click and don load .y pictures and videos
![Capture+_2021-11-21-21-36-22](https://user-images.githubusercontent.com/40062122/142778080-257d5124-f009-4cb1-88d7-d802a94dba23.png)

**Comment by ethanwu155** [comment]
Hi. Thanks for your inquiry. Your question is a good one. By design, you actually cannot upload/import photos or videos to Capture APP because we cannot guarantee these photos are created by you.

This section of Capture APP are where purchased Captures or Captures sent from friends appear.
