### ISSUE TITLE
Edit your pictures from Capture App

### ISSUE THREAD

**Issue by Vandallo** [numbersprotocol/community-support#30]
One of the main problems that your app has is that it is not designed for authentic content creators.  The first thing you should think about is that if this app is designed to make photos and videos taken from the app, you should be able to edit them at least with the functionalities that any app on the market such as IG or Snapchat has.  I am also sure that your intention to publicize your app on IG could be done much better by using influencers oriented to specific targets.

I have been dedicating myself to this for many years, you have an incredible project but you must think like the user, not like entrepreneurs.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248746882717) by [Unito](https://www.unito.io)

**Comment by KNctrl-alt** [comment]
Hey @Vandallo, great suggestions, but the first part of your issue, i.e.,

>  you should be able to edit them at least with the functionalities that any app on the market such as IG or Snapchat has. 

which is concerned with features like editing and postprocessing was originally posted on #8. So to reduce redundancy it would be better to move the discussion there by _**_closing_**_ this issue first OR editing out that part to only have the second part left here (second part seems to be about the ongoing influencer bounty campaign).

**Comment by ethanwu155** [comment]
Hi. Thanks for your request. We get a lot of requests to add filters for Capture Cam, however its important to note that Capture Cam is not a social media or photo sharing application. It is primarily a tool for registering and creating on-chain history. As such it isn't within the products scope to provide filters or advance edit features. Currently Capture Cam does support black and white filters and photo cropping, however we do not envision adding any additional photo editing features unless there is a strong demand for it from the community or a shift in the products direction.

Apologies for the inconvenience and we appreciate your understanding. If you have any other issues or concerns, feel free to let us know.
