### ISSUE TITLE
Numbers Exchange 

### ISSUE THREAD

**Issue by ParamedicArt** [numbersprotocol/community-support#333]
ParamedicArt:
Binance exchange has experienced and is experiencing serious crises. Maybe one day it will disappear like FTX.

perhaps NUMBERS should be an exchange and the NUM token would be its own exchange's currency. like binance BNB. If Binance crashes, users will be moved to alternative secure exchanges

Just like every exchange has its own NFT market, it can thus integrate the capture application into it.

Numbers Exchange sounds great

NumEX

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1205492951805336) by [Unito](https://www.unito.io)

**Comment by scott-dt** [comment]
Hi ParamedicArt,

Thank you for your feedback and for sharing your thoughts with us. Having our own exchange does sound exciting! However, it also comes with its own set of challenges, and our current business model is quite different from that of an exchange.

We understand your concern about the risks associated with exchanges potentially going down. To mitigate the risk of a single point of failure, we are listed on multiple exchanges. Additionally, we are also on decentralized exchanges (DEX) like PancakeSwap and UniSwap, providing more options for our users.

Our team continuously monitors the crypto industry, so if any significant changes occur, we can quickly respond and implement countermeasures.

Once again, thank you for your concern and feedback. We truly appreciate it.
