### ISSUE TITLE
[Community Review] Migration of Liquidity to PancakeSwap V3

### ISSUE THREAD

**Issue by Steffdarz** [numbersprotocol/community-support#346]
Dear Numbers Community,

Due to unexpected market conditions recently, after several discussions with our advisor and experts in these fields, we are considering a strategic shift in our liquidity management. 

Originally we established liquidity on both Ethereum and BNB Chain to build a healthy ecosystem for NUM. After recent observation and analysis, we notice that while the majority of Liquidity Providers are settled on Ethereum Chain, most of our community holdings are concentrated on BNB Chain. In response to that we believe that this is a good time to consolidate our liquidity into a single DEX on the BNB Chain.

### Reasoning

- Accessibility : NUM Token liquidity is fragmented on Ethereum and BNB Chain network. Our user base is mainly on BNB Chain but a majority of the LP are on Ethereum. We bring the liquidity where our community is, to foster easy access to the token and all its advantages.
- Price Stability : By concentrating all DEX liquidity into a single platform, NUM will have a larger liquidity pool and in return will reduce volatility of the price. This is especially helpful in current market conditions to help lessen the effect of selling pressure.
- Lower Slippage : Higher liquidity in a single pool tends to result in lower slippage for traders

We are planning to pull out our current liquidity from Uniswap (Ethereum) and PancakeSwap (BNB Chain) V2 and consolidate all resources into PancakeSwap V3. Currently 68% of our DEX liquidity rests within PancakeSwap, also PancakeSwap V3 is the latest and most advanced version of PancakeSwap, and it offers a number of advantages including :

- Concentrated liquidity: Liquidity providers can choose to provide liquidity for a specific price range, rather than the entire price range of a trading pair. This allows liquidity providers to earn more fees with the same amount of capital, and it also makes it possible to create pools with higher capital efficiency.

- Multiple trading fee tiers: PancakeSwap V3 introduces four different trading fee tiers: 0.01%, 0.05%, 0.25%, and 1%. This gives traders more flexibility to choose the fee tier that best suits their needs.

### Community Involvement

We believe in the importance of community input and value the perspectives of our community members. Before implementing this change, we would like to gather your thoughts, concerns, and suggestions. If there’s another DeFi pool you think we should consider, feel free to drop your suggestion too. Your feedback is crucial in ensuring that our decisions align with the collective interests of the Numbers community. 

Following this community review, we will carefully assess the feedback received and make a decision that aligns with the best interests of the Numbers community.

We appreciate your ongoing support and look forward to your active participation in this important decision-making process.

Thank you for being a valued member of the Numbers community.

### Schedule
- Community Review : 10th October - 24th October 2023.
- This migration is planned to start at November 2023.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1205688625635730) by [Unito](https://www.unito.io)

**Comment by kai0908** [comment]
That's would be a great idea, I totally agree with your decision. Besides, I am concerning about the liquidity on Number Mainet as it is quite difficult to trade NUM tokens on its native blockchain. I hope Team wiil take a look into this situation and have a plan.

**Comment by Tommy-I-T** [comment]
The decision to focus on PancakeSwap V3, which holds the majority of the current DEX liquidity, showcases a commitment to utilizing the most advanced version of the platform. The advantages offered by PancakeSwap V3, such as concentrated liquidity and multiple trading fee tiers, are appealing features that can benefit both liquidity providers and traders.
Great job from the team. 👏👏

**Comment by Steffdarz** [comment]
> That's would be a great idea, I totally agree with your decision. Besides, I am concerning about the liquidity on Number Mainet as it is quite difficult to trade NUM tokens on its native blockchain. I hope Team wiil take a look into this situation and have a plan.

Hi Kai, thanks for your input. For now you can trade Mainnet NUM on Gate.io and Lbank. We are exploring some other option too, we'll announce to the community when we have the concrete date, please don't worry.

Also do you have any suggestion on the pairing we should use, or perhaps other DEXes we can consider?

**Comment by kai0908** [comment]
I prefer using DEXes as it's quite complicated to trade on CEXes. I used to trade mainet NUM on XY Finance but it was really bad. I hope Number Mainet will be supported on some popular DEXes like Pancakeswap or Uniswap, etc.

**Comment by Karen5-hub** [comment]
I find DEXs much more user-friendly than CEXs. My past NUM trading on XY Finance left a lot to be desired. Hoping that Number Mainet can soon join popular DEXs like Pancakeswap or Uniswap for a smoother experience!

**Comment by Westpaiid** [comment]
This strategic shift seems well-considered given the changing market conditions. Focusing liquidity on the BNB Chain, where the community holdings are concentrated, can potentially benefit the ecosystem. It's important to adapt to the evolving crypto landscape for long-term success.

**Comment by fredlex** [comment]
This is notably a positive advancement and as always having the interest of the community at hand.  Migration of liquidity to pancake swap V3 will definitely have a positive impact in the stability of the $NUM token giving the community an easy access to the token. The merits using the decentralised exchange (Dex) Pancake swap V3 are really welcoming and I hope the team to Cary out proper risk assessment management as well and comfortably execute the migration plan..

**Comment by Amb-Wizhy** [comment]
The advantages like concentrated liquidity and multiple trading fee tiers offered by PancakeSwap V3, are appealing features that can benefit both liquidity providers and traders.
Great job from the team. 👏👏 This is a notable advancement.
Let's watch out for the stability of the $NUM token.

**Comment by Carina470** [comment]
The team's commendable work deserves applause for this significant advancement. It's important to keep an eye on the stability of the $NUM token in the future.
PancakeSwap V3 provides enticing benefits such as centralized liquidity and diverse trading fee structures, which can be advantageous for both liquidity providers and traders.

**Comment by Steffdarz** [comment]
Thanks for everyone's input on this topic. We will close this community review and post the recap once it's done!
