### ISSUE TITLE
Difference in Available Photos in Capture App and portal

### ISSUE THREAD

**Issue by Sudhakar111288** [numbersprotocol/community-support#35]
**Number of photos available in capture App is not reflected in Web portal**
I have total 4 pictures in capture App but in portal it shows only 3. 

**To Reproduce**

**Expected behavior**
Both areas it should show all captures available in App

**Screenshots**
![Screenshot_20220107-151241_Brave](https://user-images.githubusercontent.com/89873176/148526899-510581e6-2b4b-4e73-8659-5376442798a2.jpg)
![Screenshot_20220107-151332_Capture](https://user-images.githubusercontent.com/89873176/148526925-c7971f26-8b66-4b56-a954-b19767a0c109.jpg)

**Capture App (please complete the following information):**
 - Device: [ Samsung galaxy M31]
 - OS: [Android 3.1]
 - Browser [chrome]
 - Version [version-11]

**Select label**
Capture App/CaptureClub

**Additional context**

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248746454093) by [Unito](https://www.unito.io)

**Comment by subakteam** [comment]
I cant share my nft from app direct to IG strories, please fixed the share tool l, thanks 💙

**Comment by ethanwu155** [comment]
Hi. We apologize for the inconvenience. This issue has been resolved and you should be able to view your products properly. Appreciate your feedback and thanks for your time!
