### ISSUE TITLE
Update Capture Dashboard's "File Supported" text to include more various formats, and add file icons for non-image uploads

### ISSUE THREAD

**Issue by Steffdarz** [numbersprotocol/community-support#350]
**User story**

As a Capture Dashboard user, I want to see the "File supported text" changed to "Supported file types" to better reflect the fact that Capture Dashboard now supports uploading a variety of file types, not just text files.

**Expectation:**

Suggest new text: File types supported: JPG, PNG, GIF, MP4, PDF, PPT, and more various formats. Max size: 25 MB.

Since now it's possible to upload PDF, PPT, and other form of files in Capture Dashboard, suggest changing the "File supported text"

![image](https://github.com/numbersprotocol/community-support/assets/125893443/05f95607-0c15-4602-9d24-f57d015fa1bb)Also would be great if the upload box showed a file icon after any file that isn't images is uploaded, to improve user experience

![image](https://github.com/numbersprotocol/community-support/assets/125893443/2aa7f607-9627-4430-83fb-845539409580)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1205716525519907) by [Unito](https://www.unito.io)

**Comment by ethanwu155** [comment]
Hi @Steffdarz. Appreciate your feedback regarding Capture Dashboard. We have updated the text in the uploader page to include PDF, PPT and other files types. These changes are LIVE. Feel free to check them out and let us know your thoughts. Again thank you for using Capture Dashboard and letting us know your thoughts!
