### ISSUE TITLE
token的赋能 / Enrich token utilities

### ISSUE THREAD

**Issue by hr19990519** [numbersprotocol/community-support#36]
我看了token的白皮书，没有实质性的抵消手续费或者参与投票权等等

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248804367875) by [Unito](https://www.unito.io)

**Comment by bafu** [comment]
// help translate in English for both the title and the content of the suggestion

Hi @hr19990519, first of all, thanks for the input. The Numbers team has designed and is preparing to share more token utilities (including governance) with the community.

It's glad that you bring up this topic and the items you mentioned were included in the team discussion. Please feel free to share more about your opinions or suggestions, and let's discuss openly here. :+1:

**Comment by ethanwu155** [comment]
hi @hr19990519. appreciate you taking the time to share your request. We are pleased to inform you that we have added more token utility. 

we have NumbersDAO which allows users to vote on issues related to the Numbers Protocol Project. We also offer multiple staking sites including NUM-ETH, NUM-BSC, NUM Mainnet, NUM Mainnet Quadratic. Additionally, NUM is used to facilitate all Asset Registrations in Numbers Protocol and Numbers NFT minting. 

If you have any more opinions or suggestions on how to create more utility for NUM feel free to share with us. Thank you!
