### ISSUE TITLE
7th DAO Meeting Topic Discussion

### ISSUE THREAD

**Issue by Steffdarz** [numbersprotocol/community-support#362]
Dear Numbers DAO, I hope everyone is doing well. Soon we'll have another Numbers DAO meeting (est April 2024).

Up until now there has been misconception about Numbers DAO that only CAPTCH-A owner are eligible to be involved, but I'm here to remind everyone that it's not true. Everyone in the community is welcomed to be involved in numbers DAO. CAPTCH-A ownership is only a way to ensure your vote in the final stage, but in the early stage like Topic Discussion such as this one, everyone is free to share their suggestion on what topics they think would be good to be made into a DAO voting agenda.

So without further ado, let's all have a meaningful discussion

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1206588993989461) by [Unito](https://www.unito.io)

**Comment by Probiduc** [comment]
I suggest we discuss how to improve the Content Verifier application standard and process, as it is a key feature of Numbers Protocol and a responsibility of Numbers DAO.

**Comment by POkorji** [comment]
I suggest we use a theme that showcases why we are doing this, why they need to be involved in this as a community
So we should the theme >
"Numbers protocol and the future of digital provenance"

**Comment by DanielSamuel1** [comment]
Numbers And Governance Proposals

**Comment by emmerson121** [comment]
"Numbers Protocol: Gateway to Digital Media Provenance"

**Comment by Amb-Wizhy** [comment]
Improving Governance Processes for Better Community Engagement

**Comment by Amb-Wizhy** [comment]
Exploring New Voting Mechanisms to Enhance Decision-Making Efficiency

**Comment by Amb-Wizhy** [comment]
Analyzing Tokenomics: Strategies for Sustainable Growth

This topic could involve a deep dive into the economic principles underlying the Numbers protocol, examining token distribution models, inflationary/deflationary mechanisms, and proposing strategies to ensure long-term viability and value appreciation of the project's native token.

**Comment by emmerson121** [comment]
"Preserving the Future of Digital Media with AI"

**Comment by Carina470** [comment]
I suggest we use
Topic: Unveiling the Dark Side of Information: The Chilling Impact of Misinformation and the Vital Need for Provenance

**Comment by Jennifer104** [comment]
I suggest we discuss about how numbers protocol provides digital media provenance and why it is important.

**Comment by Karen5-hub** [comment]
I suggest we do this topic:


Should Numbers Protocol prioritize the integration of traceability features provided by A.V. Mapping over other development initiatives to combat piracy and ensure authenticity in the digital music industry?

**Comment by Confijoe** [comment]
How Numbers can be optimized to make its provenance features accessible to anyone

**Comment by martini900** [comment]
Wouldn't it be possible as a team to write to various mobile phone manufacturers to implement the ability to upload photos to the num blockchain in the core of the native camera application?  just exposing the core capture app to the native camera app like google lens for example?  only if someone wanted to sell a photo, it would be necessary to download the capture apk

**Comment by Yearner1** [comment]
Promotions is already okay for numbers Protocol, what we need is another tool, that can actually spot/identify , and tag AI as fake or real, in real time

**Comment by Steffdarz** [comment]
Seems like most of the suggestion leans to feature request / marketing suggestion 😅.

I will address some that may need more details :
_____________
@Probiduc 's & @Yearner1 
>I suggest we discuss how to improve the Content Verifier application standard and process, as it is a key feature of Numbers Protocol and a responsibility of Numbers DAO.

>Promotions is already okay for numbers Protocol, what we need is another tool, that can actually spot/identify , and tag AI as fake or real, in real time


Response to Probiduc : 
Currently our content verifier application is verify.numbersprotocol.io 
Do you have any suggestion in mind about the improvement? Do you mean also including

Response to Yearner : 
I get that your suggestion may overlap also with Probiduc's. While currently we have Capture eye (very easily applicable in real time, I have tried using it on a website), I understand it's limited to identify assets that were actually registered with Numbers Protocol. I assure you we are still working further on this, but it would be very helpful for us if you have any benchmark / example application we could learn from.
_____________

@Karen5-hub 's
>Should Numbers Protocol prioritize the integration of traceability features provided by A.V. Mapping over other development initiatives to combat piracy and ensure authenticity in the digital music industry?

Response to Karen : 
Don't worry, we got this covered. The integration with A.V. Mapping is finished, so any digital music registered with A.V. Mapping on Web3 is already utilizing Numbers Protocol's solution.

Unless you mean we need to prioritize it over other development, well I don't think the other communities would not be too happy about it 😅.
_____________

@martini900 
>Wouldn't it be possible as a team to write to various mobile phone manufacturers to implement the ability to upload photos to the num blockchain in the core of the native camera application? just exposing the core capture app to the native camera app like google lens for example? only if someone wanted to sell a photo, it would be necessary to download the capture apk.

Response to Martin : 
I have checked with everyone, I think we tried it previously, quoting from Vera, our COO :
"Working with equipment is always our goal. we could capture all data at the beginning. if community member has connection to intro. very welcome. 
We definitely tried this before."

So yes, we tried, and it's still a work in progress, but definitely very welcome if you could connect us with someone.
_____________

@Amb-Wizhy 
>Analyzing Tokenomics: Strategies for Sustainable Growth. This topic could involve a deep dive into the economic principles underlying the Numbers protocol, examining token distribution models, inflationary/deflationary mechanisms, and proposing strategies to ensure long-term viability and value appreciation of the project's native token.

Response to Amb-Wizhy : 
Yes! if you have anything about our Tokenomics you think we could improve, you're very welcome to sound out the idea. Currently I think we have already made 2 changes to the Tokenomics. We could live with the third.

Also @martini900 I remember you and Cryptoguy did mention something about Tokenomics in Ambassador group previously, is it all clear now or do you still have anything in mind that we could change about the Tokenomics?

_____________

@Amb-Wizhy & @DanielSamuel1 
Improving Governance Processes for Better Community Engagement - Numbers And Governance Proposals

Response to Amb-Wizhy & DanielSamuel1 : 
Please let me know if you guys have any improvement idea to our Governance process. Is it the platform we are using? (Github) or is there any other specific issue?
_____________

Response to the others : 
I'm so sorry I was unable to response to everyone personally, but from what I see, most of the replies lean more to feature requests. If I understand wrong, please correct me by replying to this posts. We welcome any feature requests, but it would be amazing if we could focus on the stuff our DAO could influence (Please refer to this : https://docs.numbersprotocol.io/introduction/numbersdao)

Nevertheless, really appreciate all your inputs. This thread will still be open for some time this week, please let me know if you have any more suggestion.

**Comment by fredlex** [comment]
Is there a possibility of extending $NUM token utility by onboarding or integrating with other projects that will adapt NUM as a primary token on their platform?

**Comment by Ahmadhasnain44** [comment]
I am new

**Comment by aznrice888** [comment]
not sure why i wasn't able to get a CAPTCH-A, been holding over 30k of $NUM for 2 years now, could someone address this please?

**Comment by Steffdarz** [comment]
@aznrice888 For non-whitelist user, you could get the Pebble CAPTCH-A
If you were looking for getting SNOW and above, you need to be whitelisted and one of the prerequisite of being whitelisted is being an active contributor to the project / community, or easier, just apply to our ambassador program : https://ambassador.numbersprotocol.io/
_____________________________________________

Thanks everyone for the suggestion, I think we have found a fitting topic for the next DAO meeting agenda. I will now close this thread, please stay tuned for more updates regarding our next DAO meeting

**Comment by Karen5-hub** [comment]
Hello 👋
