### ISSUE TITLE
Discussion on Crust Network vs Filecoin

### ISSUE THREAD

**Issue by doanthekhiem** [numbersprotocol/community-support#369]
Greetings,

I would like to discuss a potential issue regarding the integration of Crust Network. Recently, I conducted a comparative study between Filecoin and Crust.network, and the results suggest that Crust is highly regarded for its security and cost-effectiveness.

Specifically, Crust's advantages include:

Enhanced security mechanisms: Crust utilizes TEE and SGX technologies, which are considered more secure than Filecoin's methods.
Stronger decentralization: Crust's architecture promotes a more decentralized network compared to Filecoin.
Competitive pricing: Crust offers more affordable storage solutions than Filecoin.
Given these advantages, I would like to know the team's perspective on the following:

Overall assessment of Crust Network compared to Filecoin: What are the key strengths and weaknesses of each platform?
Feasibility of integrating Crust Network: Is it technically and strategically viable to integrate Crust into our current system?
Potential benefits of integrating Crust: What are the potential advantages and drawbacks of integrating Crust?
I believe that a thorough evaluation of Crust Network is crucial before making any decisions regarding its integration. I look forward to hearing your insights and opinions on this matter.

​
The issue is also created on [Asana](https://app.asana.com/0/1203248692432071/1206890082204431)

**Comment by Steffdarz** [comment]
Hi Khiem, thanks for your suggestion, I have taken a look at your points, and I have to say you nailed most of it. But let me clarify some points first :

- While both Filecoin and Crust use IPFS, there might be some technical differences that we need to take into account, especially on the specific storage method they use and how it will interact with our current infrastructure.

- Performance wise, both excel in their own category. Crust may be faster and suitable for high traffic dApps, but for a long term permanent storage, I believe Filecoin still have their edge. And considering one of the most used feature we're doing currently is archiving important event in the world, we may need a more dedicated permanent storage solution. However this doesn't rule out that we could utilize Crust for some of our dApps in the future.

- Yes, currently the pricing for Crust service is very competitive, and this is very enticing for me personally.

I have relayed this message to our tech team for a more detailed compatibility check. Once again, thanks for your suggestion!
