### ISSUE TITLE
[Announcement] Dev Bounty #1 Winners!

### ISSUE THREAD

**Issue by ethanwu155** [numbersprotocol/community-support#37]
### Congrats to our FIRST DEV BOUNTY Winners! 

**Numbers Protocol** is a project that will be built in collaboration with the community. We appreciate your feedback :)

Results can be found [here](https://github.com/numbersprotocol/community-support/wiki/12.-Bounty-Programs#dev-bounty-1-winners) in the Winners Section of Dev Bounty#1 Details.

If you are a winner please fill out the following [form](https://airtable.com/shrQqymUSV0hBtuG5) to claim you reward!

### Winner Award:
1) KNctrl-alt (31 votes)
2) willcoursen (10 votes)
3) web2hotel (6 votes)
4) AKT4UnMe (4 votes)
5) KDWJD (4 votes)

### Top Voted Issue:
[Issue - Vulnerability to spoofing of GPS location (Android)](https://github.com/numbersprotocol/community-support/issues/17) - 7 Votes by KNctrl-alt

### Top Voted Feature Request:
[Introductory UI/UX for new users.](https://github.com/numbersprotocol/community-support/issues/13) - 7 votes by KNctrl-alt

### Top Voted Comment

[Comment Link](https://github.com/numbersprotocol/community-support/issues/22#issuecomment-1001881411)

"Hey @AKT4UnMe, I would apologise if my comments came across as a disagreement to your suggestions or as if they are suited only to the marketplace or as if marketplace suggestions cannot be posted here. That's not what I meant. It's also not necessarily the case that the directory system would be too difficult of a task for the team to pursue. It is completely upto the team to choose a solution and go for it, since I am just a passionate community member like you and we are here to provide suggestions as we think are suitable.

What I wanted was that I start that conversation since we had a similar goal in our mind (to organise media files) so that we could talk more about if one is more feasible than the other for now. It could also be the case that both are seen as good options by the team. As I said, I would be happy if both are adopted.

However, I do think it would be better if you could take your time and be specific to any part of this ecosystem (or may be even group together parts for your suggestions) and mention it in your issue Title or the Body whenever you post your suggestions. That helps the team and others get exactly the point you want to be delivering.

tammyyang, ethanwu155 and their team have been so lenient and pushing for a community-friendly session in this Phase so no one has to be a programmer to be able to post issues. So you are very welcome to post your suggestions here. We can then discuss about solutions within ourselves and the team and let the team do their part. I think the team would be happier to listen to photographers like you and the issues you have with the products.

By the way, I have been more of a UI/UX enthusiast looking for improvements in the Capture App (hence my submissions about the app) and yet to give a good look at the Capture Club (I have some in my mind, need to narrow it down before I post). So I am really looking forward for your submissions." - 3 votes by KNctrl-alt

### Commenter Lottery
1) ChrisSvensson
2) Elixexe
3) nnnanji
4) arnabjyotiborual
5) vincent8535

**Comment by KNctrl-alt** [comment]
I want to verify that I have submitted the form a few days ago.

**Comment by sofiayan0523** [comment]
We still haven't got the reply from the winners below:

@willcoursen
@KDWJD
@nnnanji
@vincent8535
@ChrisSvensson

If you are a winner please fill out the following [form](https://airtable.com/shrQqymUSV0hBtuG5) to claim your reward!

The reward is open to claiming before **Jan 25** 23:59 UTC, if we didn't get applications from the winner, the reward will be revoked and added to the dev bounty reward pool for the next track. Grab your time!

**Comment by KDWJD** [comment]
Thanks for the email to pull me back in here! I just submitted the form!!

**Comment by nnnanji** [comment]
Thank you for informing me again!! I submitted the form ^^
