### ISSUE TITLE
[Capture APP] Upload Edited Photo with High Verification

### ISSUE THREAD

**Issue by ethanwu155** [numbersprotocol/community-support#4]
from @yodeys (via Discord Capture APP channel)

**Is your feature request related to a problem? Please describe.**
Would like to know whether photos will be allowed to be edited and still considered high verification level because my understanding is many photographers would like to be able to edit their photos first to get the best output. So not having a process that allows the photo to still be considered high verification would be an issue. 

**Describe the your user story**
Many photographers would like to be able to edit their photos first to get the best output. So not having a process that allows the photo to still be considered high verification would be an issue. 

**Describe the solution you'd like**
Would suggest a process that allows professional photographers to take photos using their own camera and then upload it onto photoshop to edit before minting it on the app but still retain high verification.

**Describe alternatives you've considered**
N/A

**Select label**
Capture APP

**Additional context**

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248807392577) by [Unito](https://www.unito.io)

**Comment by ethanwu155** [comment]
**yodeys** your right! we are aware of that professional photographers edit their photos as part of the flow. casual photographers also appreciate adding filters to give their photos an interesting look.

we can achieve high verification with edited Captures in the following way:

1) Metadata Injections based on C2PA Standard

2) Leveraging C2PA network to ensure content provenance remains intact

**Metadata Injections based on C2PA Standard**
One of the key features of all the assets in our network is that the metadata is injected directly into the asset itself. This means the photo itself has information embedded into it and the information travels with the photos as it is downloaded. It also means that any edits made the to the photo will also be tracked. In this case the photo will have multi-injections.

The Metadata is injected based on a standard called Coalition of Content Provenance & Authenticity which is also adopted by major platforms such as Adobe. 

**Leveraging C2PA network to ensure content provenance remains intact**
What we can do is we can leverage C2PA network to ensure the content provenance remains. Adobe's PhotoShop already supports C2PA injections. 

So a possible flow maybe (1) take a photo with Capture APP (2) import into Adobe PhotoShop (3) make edits. when complete generated multi-injection (4) reimport back into Capture APP via metadata verification

The final photo will have the following injection structure:

```
Final Capture
|===> Metadata from Capture APP
|=====> Metadata from PhotoShop Edits
```

We can also consider adding some in-app editing tools (filters and such) so that casual photo takers can adjust their photos directly in Capture APP. The multi-injection structure will also remain as well. See injection structure:

```
Final Capture
|====> Metadata from Capture APP on-creation
|======> Metadata from in-app filter
```

**Comment by ethanwu155** [comment]
from Gunny (via Discord)

Quite right, I don't think the professional photographer should get an advantage over the average user. The resources should be available to all without discrimination. If developments are made.

**Comment by AlexWashburn-PhotoEditor** [comment]
@Ethan

> **yodeys** your right! we are aware of that professional photographers edit their photos as part of the flow. casual photographers also appreciate adding filters to give their photos an interesting look.
> 
> we can achieve high verification with edited Captures in the following way:
> 
> 1. Metadata Injections based on C2PA Standard
> 2. Leveraging C2PA network to ensure content provenance remains intact
> 
> **Metadata Injections based on C2PA Standard** One of the key features of all the assets in our network is that the metadata is injected directly into the asset itself. This means the photo itself has information embedded into it and the information travels with the photos as it is downloaded. It also means that any edits made the to the photo will also be tracked. In this case the photo will have multi-injections.
> 
> The Metadata is injected based on a standard called Coalition of Content Provenance & Authenticity which is also adopted by major platforms such as Adobe.
> 
> **Leveraging C2PA network to ensure content provenance remains intact** What we can do is we can leverage C2PA network to ensure the content provenance remains. Adobe's PhotoShop already supports C2PA injections.
> 
> So a possible flow maybe (1) take a photo with Capture APP (2) import into Adobe PhotoShop (3) make edits. when complete generated multi-injection (4) reimport back into Capture APP via metadata verification
> 
> The final photo will have the following injection structure:
> 
> ```
> Final Capture
> |===> Metadata from Capture APP
> |=====> Metadata from PhotoShop Edits
> ```
> 
> We can also consider adding some in-app editing tools (filters and such) so that casual photo takers can adjust their photos directly in Capture APP. The multi-injection structure will also remain as well. See injection structure:
> 
> ```
> Final Capture
> |====> Metadata from Capture APP on-creation
> |======> Metadata from in-app filter
> ```

--------------

There are a number of ways you can do this but a workflow to keep in mind is that of professional photojournalists in the field. Many are photographing very low light or quick motion events that even the best camera phones and apps still struggle with. 

Speaking from a professional perspective that consumer level users would benefit from as well would be the app enabled natively in DSLR and Mirrorless camera. In a situation like a riot, fire or large political event photographers port photos from the DSLR or mirrorless cameras into the phone where they do a quick tone, add a caption and ftp the photo to their company's server. 

There is often not enough time to pull out a laptop for editing and wireless transfer can be so slow when cell networks are overloaded photographers are forced to minimize transfers. In situations like a presidential inauguration cameras are hard lined to send photos in real time to an editor offsite and the photographer does nothing in terms of editing at all. These are all high volume situations where the tech would be arguably most valuable.

**Comment by ethanwu155** [comment]
From Telegram (from B Wasim)

B Wasim, [Nov 30, 2021 at 10:23:56 AM]:
... I have been thinking about this more and think that not allowing upload of videos / pictures limits the use case. Think about people who take photographs or videos, edit them and then upload. That's most of the people. I think there should be a way to allow people to upload videos/pics and then some algorithm which ensures that video was created by you. May be making sure that only people that are allowed to upload are the ones which are "locked staking" reasonable amount of $NUM and penalizing them if they upload videos which are not made by them..

I understand that creating such an algorithm may not be an easy process and big companies like youtube are still struggling with this because there are so many variations.. But I think that not allowing uploads does limit the use case..

**Comment by ethanwu155** [comment]
> @Ethan
> 
> > **yodeys** your right! we are aware of that professional photographers edit their photos as part of the flow. casual photographers also appreciate adding filters to give their photos an interesting look.
> > we can achieve high verification with edited Captures in the following way:
> > 
> > 1. Metadata Injections based on C2PA Standard
> > 2. Leveraging C2PA network to ensure content provenance remains intact
> > 
> > **Metadata Injections based on C2PA Standard** One of the key features of all the assets in our network is that the metadata is injected directly into the asset itself. This means the photo itself has information embedded into it and the information travels with the photos as it is downloaded. It also means that any edits made the to the photo will also be tracked. In this case the photo will have multi-injections.
> > The Metadata is injected based on a standard called Coalition of Content Provenance & Authenticity which is also adopted by major platforms such as Adobe.
> > **Leveraging C2PA network to ensure content provenance remains intact** What we can do is we can leverage C2PA network to ensure the content provenance remains. Adobe's PhotoShop already supports C2PA injections.
> > So a possible flow maybe (1) take a photo with Capture APP (2) import into Adobe PhotoShop (3) make edits. when complete generated multi-injection (4) reimport back into Capture APP via metadata verification
> > The final photo will have the following injection structure:
> > ```
> > Final Capture
> > |===> Metadata from Capture APP
> > |=====> Metadata from PhotoShop Edits
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We can also consider adding some in-app editing tools (filters and such) so that casual photo takers can adjust their photos directly in Capture APP. The multi-injection structure will also remain as well. See injection structure:
> > ```
> > Final Capture
> > |====> Metadata from Capture APP on-creation
> > |======> Metadata from in-app filter
> > ```
> 
> There are a number of ways you can do this but a workflow to keep in mind is that of professional photojournalists in the field. Many are photographing very low light or quick motion events that even the best camera phones and apps still struggle with.
> 
> Speaking from a professional perspective that consumer level users would benefit from as well would be the app enabled natively in DSLR and Mirrorless camera. In a situation like a riot, fire or large political event photographers port photos from the DSLR or mirrorless cameras into the phone where they do a quick tone, add a caption and ftp the photo to their company's server.
> 
> There is often not enough time to pull out a laptop for editing and wireless transfer can be so slow when cell networks are overloaded photographers are forced to minimize transfers. In situations like a presidential inauguration cameras are hard lined to send photos in real time to an editor offsite and the photographer does nothing in terms of editing at all. These are all high volume situations where the tech would be arguably most valuable.

@AlexWashburn-PhotoEditor thanks so much for the insightful response. its very helpful to us to understand the process different processes. If I'm understanding correctly what you are sharing  is some professional photographers take photos with their DSLR, port the photo to an APP to do some quick edits, before sending it off to company servers. Is that correct.

So a flow like the following:

```
Take Photo with DSLR => Port to APP => Edit (tone + caption) => send to company server
```

**Comment by AlexWashburn-PhotoEditor** [comment]
> @AlexWashburn-PhotoEditor thanks so much for the insightful response. its very helpful to us to understand the process different processes. If I'm understanding correctly what you are sharing is some professional photographers take photos with their DSLR, port the photo to an APP to do some quick edits, before sending it off to company servers. Is that correct.
> 
> So a flow like the following:
> 
> ```
> Take Photo with DSLR => Port to APP => Edit (tone + caption) => send to company server
> ```
-----------------------

Hi Ethan, I am actually speaking about two separate kinds of workflow that would be popular during events where High Verification would be important. 

1) Camera / Phone / Send

Use Cases: Fast moving situations where a photographer must remain highly mobile. This would be used when news photographers are covering things like a riot, natural disaster, political event, etc... This method is gaining in popularity in journalism's web first ethos and an example where I think professional journalists may be most interested in High Verification.

Workflow: Take photo with DSLR or Mirrorless => port to App => Aesthetics Editing (tone / potentially re-size) => 2nd App (caption+other metadata such as a trans ref code) => Push to company server

*Note: from the company server various teams then push photos to social and add to live stories. Your tech could be really helpful in event reconstruction as well but thats just a side note. 

2) Camera / Editor / Send

Use Cases: High Volume Situations where a photographer isn't moving around as much. The Olympics and large sporting events would be an example but another example where verification is important would be Presidential inaugurations and political rallies. (I managed a team of photographers covering Biden's inauguration day.) Our team did not shoot tethered but larger companies AP/Reuters/Getty/NYT do and photographers are in place hours before the event starts. 

Workflow: Take photo with DSLR or Mirrorless => image moves through a physical cable (usually) to an editor waiting to *catch* => Photo Editor tones/captions (Photoshop / Lightroom / Photomechanic) and moves the photograph to the wire or to their company server 

*In this example a photographer might not physically sit down at a computer till long after the event is over.

I hope this is helpful but both illustrate how allowing verification to happen in camera at high profile events would be really important. In all of these situations it would not be unusual for a photographer to make 5,000 or more photos in a single day. 5,000 would actually be on the low end for some events. 

I am interested in working with your company to help assign photographers to events like these as part of testing and outreach.

**Comment by ethanwu155** [comment]
@AlexWashburn-PhotoEditor This is great feedback! Thanks so much for the clarification and the detailed use cases. We would definitely be interested in working together with you.

**Comment by kennyhungQA** [comment]
This issue is no longer to be used, close it.
Currently, the user can leverage [Capture Dashboard](https://dashboard.captureapp.xyz/) to upload their works.
