### ISSUE TITLE
[Translation demand - German] Numbers Protocol Asset & Deflationary Token Economy

### ISSUE THREAD

**Issue by sofiayan0523** [numbersprotocol/community-support#40]
Looking for German translators to translate [<Numbers Protocol Asset & Deflationary Token Economy>](https://medium.com/numbers-protocol/numbers-protocol-asset-deflationary-token-economy-aeb0336e3711)

Leave your translation in this issue comment to become our Tier 1 Ambassador!

--
- How to participate
> - Translate **at least one paragraph of the selected article**.
> - **The translation should be done as the Github issue comment.**
> - **Share the link of the comment in the local community and get at least 3 likes on Github**.
> - If there are two comments linked to the same paragraph and both collect 3 likes, the earlier one wins.
> - The translation needs to be fluent and factually correct and should not be copied directly from Google translate or similar apps (any attempt to copy-paste directly from Google Translate will result in your dismissal from the Ambassador Program).

- Rewards
> - `10 NUM` per paragraph per language
> - Bounty-based, the selected article will be announced every Friday

**Comment by lennartvanEeden** [comment]
Numbers Dezentrales Fotonetzwerk
Numbers baut ein dezentrales Fotonetzwerk auf, um Gemeinschaft, Wert und Vertrauen in digitale Medien zu schaffen. Das Numbers Protokoll definiert digitale visuelle Medien als Assets neu und ist das Rückgrat einer Reihe von Tools zum Registrieren und Abrufen von Bildern und Videos im Numbers Netzwerk. Dazu gehören:
Capture App: Die erste Blockchain-Kamera der Welt, mit der Nutzer einfach Fotos registrieren und Web 3.0-Anwendungen nutzen können.
Seal API: Entwickler und Unternehmen können Numbers API implementieren, um Fotos zu registrieren und auf ihre Web3.0-Adressen und Zertifikate zuzugreifen.
Zertifikate: Authentizitätszertifikate für Inhalte mit On-Chain-Provenance
CaptureClub-Marktplatz: Native NFT-Marktplatz, der es Foto-Generatoren ermöglicht, ihre Kreationen zu verkaufen und zu vermarkten.
NFT-Suchmaschine: Die erste Web 3.0 NFT-Suchmaschine, die Nutzern hilft, die Historie von NFTs zu überprüfen und potenziellen NFT-Betrug zu verhindern.
Numbers setzt sich für die Reinheit der digitalen Medien ein und ermöglicht es den Menschen, kritischer über die Wechselwirkungen zwischen unseren Bildern und der Welt um uns herum nachzudenken. Das Ziel von Numbers ist es, authentische Fotos (einschließlich Bilder und Videos) zu tokenisieren, um ein dezentrales Fotonetzwerk im Web 3.0 zu schaffen. Um dieses Ziel vollständig zu verwirklichen, führen wir eine deflationäre Token- und Asset-Ökonomie ein - ein System, das vierteljährlich ausgeführt wird, um die Servicegebühren zu bestimmen und die Anzahl der Token zu berechnen, die zurückgekauft und verbrannt werden müssen.

**Comment by sofiayan0523** [comment]
@lennartvanEeden the partial translation is approved and pushed to the main article with your name, please check here: https://hackmd.io/hkxEHYdOS6K3BV63wCKTyg?view#German

Thank you for your contribution, please [fill out the form](https://airtable.com/shrHsGWu0uN1r2sYj) to claim the reward :)

**Comment by sofiayan0523** [comment]
German translation still has some missing paragraphs, looking for ambassadors' help!

**Comment by lennartvanEeden** [comment]
Dear Team, 

I filled out the form and translated the Rest of the paragraphs for you :) was still a lot :p
Thank you for your answer and wish you a great weekend! 

Von meinem iPhone gesendet

**Comment by lennartvanEeden** [comment]
Hello Team, 
Did you receive the form? 

If you want you can send me regularly texts for German translation and I will do my job as a translator seriously and reliably for the German language for you. I will be glad to cooperate with you and wish you a nice weekend and a super future .

Greetings from Lennart.

**Comment by lennartvanEeden** [comment]
Von meinem iPhone gesendet

Anfang der weitergeleiteten Nachricht:
