### ISSUE TITLE
[Translation demand - Italian] Numbers Protocol Asset & Deflationary Token Economy

### ISSUE THREAD

**Issue by sofiayan0523** [numbersprotocol/community-support#41]
Looking for Italian translators to translate [<Numbers Protocol Asset & Deflationary Token Economy>](https://medium.com/numbers-protocol/numbers-protocol-asset-deflationary-token-economy-aeb0336e3711)

Leave your translation in this issue comment to become our Tier 1 Ambassador!

--
- How to participate
> - Translate **at least one paragraph of the selected article**.
> - **The translation should be done as the Github issue comment.**
> - **Share the link of the comment in the local community and get at least 3 likes on Github**.
> - If there are two comments linked to the same paragraph and both collect 3 likes, the earlier one wins.
> - The translation needs to be fluent and factually correct and should not be copied directly from Google translate or similar apps (any attempt to copy-paste directly from Google Translate will result in your dismissal from the Ambassador Program).

- Rewards
> - `10 NUM` per paragraph per language
> - Bounty-based, the selected article will be announced every Friday

**Comment by dmlausanne** [comment]
Numbers Protocol Asset & Deflationary Token Economy

13 Gennaio · 6 min di lettura

Traduzione: Cinese｜Coreano｜Giapponese

**Numbers Decentralized Photo Network**
Numbers sta costruendo una rete decentralizzata di fotografia con l'obiettivo di creare una comunità, valore e fiducia nei media digitali. Il suo protocollo Numbers ridefinisce il i media visivi digitali come asset ed è la spina dorsale di un insieme di strumenti per la registrazione e il recupero di immagini e video nella rete Numbers. Questa include:
- **Capture app**: la prima fotocamera blockchain al mondo che permette agli utenti di archiviare fotografie e utilizzare applicazioni del Web 3.0. 

- **Seal API**: Sviluppatori e aziende possono implementare l'API Numbers per archiviare fotografie ed accedere ai loro indirizzi e certificati Web 3.0.

- **Certificates**: certificati di autenticità on-chain di provenienza dei contenuti
-**CaptureClub Marketplace**: Marketplace di proprietà che permette ai generatori di contenuti di vendere e mettere in stake le loro creazioni.
- **NFT Search Engine**: il primo motore di ricerca NFT Web 3.0 che aiuta gli utenti a verificare la cronologia degli NFT e a prevenire potenziali frodi NFT. 

Numbers promuove la purezza dei media digitali e permette alle persone di pensare in modo più critico alle interazioni tra le immagini e il mondo che ci circonda. L'obiettivo di Numbers è quello di "tokenizzare" foto autentiche (immagini e video) in modo fa creare una rete di fotografie decentralizzata nel Web 3.0. Per realizzare in maniera completa questo obiettivo, stiamo introducendo un sistema, il Deflationary Token & Asset Economy, il quale, eseguito in maniera trimestrale, determina i costi di servizio e calcola il numero di token che verranno ricomprati ed in seguito bruciati. 

**Web 3.0 asset economy**

La transizione dal Web 2.0 al Web 3.0 porta un cambiamento radicale a come le sono viste e come il servizio delle fotografie opera. Nel Web 3.0, le risorse sono registrate e hanno un registro di proprietà chiaro. Questa distinzione permette alle risorse di acquisire un valore e introduce la nozione di "asset economy". Queste caratteristiche aprono inoltre le porte a un nuovo tipo di utilizzi delle fotografie nel Web 3.0. 

Avendo già creato strumenti e servizi che permettono agli utilizzatori di registrare le loro risorse nel Web 3.0, così come il token nativo, NUM, Numbers Photo Network è opportunamente attrezzato a supportare l'asset economy del Web 3.0.

La tabella seguente mostra il costo base per l'utilizzo della rete annunciato nel Q1 2022. La struttura dei costi di utilizzo è basata in NUM, e i canoni di rete sono adeguate in maniera trimestrale per assicurare agli utenti di poter sfruttare le azioni nella rete ad un prezzo stabile.

Costi di servizio aggiuntivi potranno essere annunciati in conformità alla roadmap e ai progressi a livello di sviluppo del progetto.

Sviluppatori e aziende possono inoltre approfittare dei servizi Numbers (Seal API) per registrare ed accedere a fotografie e recuperarne la provenienza, l'indirizzo Web 3.0 e i certificati. Simili ai servizi degli utenti, le tasse verranno adeguate in maniera trimestrale in modo da assicurare agli utenti API delle tasse stabili.  

**Le applicazioni di Ecosistema**

Scoprire le firme dei creatori, i registri di proprietà, gli storici delle transazioni e la provenienza dei contenuti di fotografie caricate su servizi Web 2.0 come Instagram o altre piattaforme social, vista la natura del web attuale, è difficile, se non impossibile.
All'interno della rete fotografica Web 3.0 decentralizzata di Numbers, queste informazioni sono facilmente accessibili grazie al protocollo Numbers. 

Protocollo nativo della rete Numbers, il Numbers Protocol sfrutta le ultime novità in campo Web 3.0 e in termini di tecnologia per il tracciamento dei contenuti, garantendo purezza e tracciabilità dei contenuti. Una volta che l'autenticità dei contenuti è assicurata, apre la via a terze parti in modo che forniscano servizi fotografici innovativi che aiutino gli utenti a navigare nel Web 3.0 con i le loro fotografie, registrazioni, monetizzazioni, ecc.

Questi servizi di terze parti vengono chiamate "applicazioni di ecosistema" e includono (ma non si limitano a) NFT marketplace, servizi di deposito Web 3.0, piattaforme social media e servizi di archiviazione di immagini/video. Anche se le applicazioni di sistema sono considerate "gratuite", vi sarà comunque sempre un pagamento base che sarà applicato quando gli utenti useranno le applicazioni di ecosistema nella rete Numbers.  

Qui di seguito le collaborazioni annunciate negli ultimi due mesi e che rappresentano i progressi in termini di adozione di Numbers Protocol.
![image](https://user-images.githubusercontent.com/97765630/149600280-d0f4307d-fa3d-4659-b8fb-2dd33defa014.png)

**Deflationary Token Economy**

Il valore generato dalle risorse registrate verrà utilizzato per ricomprare e "bruciare" i token NUM. Il numero di token che verranno bruciati sarà basato sul livello di adozione e il reddito del trimestre. Utilizzeremo il 20% del valore della rete per ricomprare NUM e bruciarli finché non ricompreremo il 50% di tutti i NUM (500MM). La prima ondata di "burn" è prevista per marzo. Il volume totale di NUM che verranno bruciati nel primo trimestre sarà basata sul volume totale di risorse registrate. 

N_ bruciati = N_nuove_risorse_registrate*R*20% 

La costante R rappresenta il valore di ogni nuova risorsa registrata ed è una funzione del tasso di adozione trimestrale, market cap, e prezzo di NUM.

I token bruciati verranno rimossi dalla fornitura in circolazione. 

Notiamo che la crescita delle risorse è simile alla crescita degli utenti attivi su Instagram. Come risultato, ci possiamo dunque basare sulla curva di crescita di Instagram come stima per la crescita futura delle registrazioni delle risorse sulla rete Numbers. 

![image](https://user-images.githubusercontent.com/97765630/149600231-05327406-a3f1-44e8-8940-edc181b2234f.png)

Nel grafico precedente, la linea grigia indica la crescita degli utenti Instagram attivi mensili dalla sua creazione in ottobre 2010 ad aprile 2017. La linea continua blu indica la crescita attuale delle risorse nella rete Numbers (dal lancio del servizio a dicembre 2021) mentre la linea tratteggiata blu rappresenta la crescita stimata della rete Numbers. 

La costante R per il Q1 2022 è fissata a 0.5. In conformità con le proiezioni, la stima dei token che verranno bruciati è di 

N_bruciati_Q1_2022 ~ 30M * 0.5 * 20% ~ 3M

Siccome sarà la prima volta che verranno bruciati dei token, la N_nuove_risorse_registrate sarà uguale al totale delle risorse presenti nella rete di Numbers Protocol (da dicembre 2020 a marzo 2022). 

**NUMBERSDAO**
Il focus verso la comunità e la decentralizzazione sono valori chiave di Numbers Protocol. Come riflesso dei nostri valori, abbiamo come obiettivo. attraverso una governance decentralizzata, di creare uno spazio trasparente e democratico per la nostra comunità. Stabilire una Decentralized Autonomous Organization (DAO) è il nostro primo passo verso la creazione di uno spazio aperto per noi nel quale poter ascoltare le voci e input della nostra comunità e un modo di conferire ai membri della DAO del potere decisionale per perseguire obiettivi comuni per il futuro della rete Numbers. 

La Community review e l' Asset & Deflationary Token Economy verranno lanciati domani (14 gennaio 2022) fino al 13 febbraio 2022. I commenti e i suggerimenti della community review verranno considerati per futuri possibili miglioramenti e verranno considerati preziosamente e votati dai NUMBERSDAO. 
Le regole di governance della NUMBERSDAO sono state approvate nella community review di dicembre. Ulteriori dettagli delle prime votazioni saranno fornite entro la fine di gennaio 2022. 

**A proposito di Numbers Protocol**
Numbers sta costruendo una rete decentralizzata di fotografia con l'obiettivo di creare una comunità, valore e fiducia nei media digitali. Il suo protocollo Numbers ridefinisce il i media visivi digitali come asset ed è la spina dorsale di un insieme di strumenti per la registrazione e il recupero di immagini e video nella rete Numbers - La Capture app, Seal API, e un sito di tracciamento - più il CaptureClub marketplace e un motore di ricerca di proprietà degli NFT. Numbers promuove la purezza dei media digitali e permette alle persone di pensare in modo più critico alle interazioni tra le immagini e il mondo che ci circonda.

**Comment by Zwi994** [comment]
Gran progetto

**Comment by sofiayan0523** [comment]
@dmlausanne the translation is approved and pushed to the main article with your name, please check here: https://hackmd.io/hkxEHYdOS6K3BV63wCKTyg?both#Italian

Thank you for your contribution, please [fill the form](https://airtable.com/shrHsGWu0uN1r2sYj) to claim the reward :)
