### ISSUE TITLE
[Translation demand - Turkish] Numbers Protocol Asset & Deflationary Token Economy

### ISSUE THREAD

**Issue by sofiayan0523** [numbersprotocol/community-support#42]
Looking for Turkish translators to translate [<Numbers Protocol Asset & Deflationary Token Economy>](https://medium.com/numbers-protocol/numbers-protocol-asset-deflationary-token-economy-aeb0336e3711)

Leave your translation in this issue comment to become our Tier 1 Ambassador!

--
- How to participate
> - Translate **at least one paragraph of the selected article**.
> - **The translation should be done as the Github issue comment.**
> - **Share the link of the comment in the local community and get at least 3 likes on Github**.
> - If there are two comments linked to the same paragraph and both collect 3 likes, the earlier one wins.
> - The translation needs to be fluent and factually correct and should not be copied directly from Google translate or similar apps (any attempt to copy-paste directly from Google Translate will result in your dismissal from the Ambassador Program).

- Rewards
> - `10 NUM` per paragraph per language
> - Bounty-based, the selected article will be announced every Friday

**Comment by Serfiraz46** [comment]
Numbers Merkeziyetsiz Fotoğraf Ağı
Numbers, dijital medyada topluluk, değer ve güven oluşturmak için merkeziyetsiz bir fotoğraf ağı oluşturuyor. Numbers Protocol, dijital görsel medyayı varlıklar olarak yeniden tanımlar ve Numbers ağındaki görüntüleri ve videoları kaydetmeye ve almaya yönelik bir takım araçların temel yapıtaşıdır. Bunlar şunları içerir: 
Yakalama uygulaması: Kullanıcıların kolayca fotoğraf kaydedebildiği ve Web 3.0 uygulamalarını kullanabildiği dünyadaki ilk blok zinciri kamerası.
Seal API: Geliştiriciler ve kuruluşlar, fotoğrafları kaydetmek ve Web3.0 adreslerine ve sertifikalarına erişmek için Numbers API'yi uygulayabilir.
Sertifikalar: ağ üzerinde kaynağa sahip içerik orijinalliği sertifikaları
CaptureClub pazarı: Fotoğraf üreticilerinin yarattıklarını satmalarına ve paylaştırmalarına olanak tanıyan yerel NFT pazarı.
NFT Arama Motoru: Kullanıcıların NFT'lerin geçmişini doğrulamasına ve olası NFT sahtekarlığını önlemesine yardımcı olan ilk Web 3.0 NFT arama motoru.
Numbers, dijital medyanın arılığını savunur ve insanların görüntülerimizle çevremizdeki dünya arasındaki etkileşimler hakkında daha eleştirel düşünmelerini sağlar. Numbers'ın amacı, Web 3.0'da merkeziyetsiz bir fotoğraf ağı oluşturmak için gerçek fotoğrafları (görüntüler ve videolar dahil) tokenize etmektir. Bu hedefi tam olarak gerçekleştirmek için, hizmet ücretlerini belirlemeye ve geri alınıp yakılacak token sayısını hesaplamaya yarayan, üç ayda bir yürütülen bir sistem olan Deflasyonist Token ve Varlık Ekonomisi sunuyoruz. 
Web 3.0 varlık ekonomisi
Web2.0'dan Web3.0'a geçiş, varlıkların nasıl görüntülendiği ve fotoğraf hizmetlerinin nasıl çalıştığı konusunda temel bir değişiklik getiriyor. Web3.0'da varlıklar kayıtlıdır ve net bir sahiplik kaydına sahiptir. Bu ayrım, varlıkların değer kazanmasına izin verir ve varlık ekonomisi kavramını ortaya çıkarır. Ayrıca Web3.0 alanında yeni tür fotoğraf hizmetleri için kapıyı açar. 
Kullanıcıları Web3.0'daki varlıkları kaydetmenin yanı sıra yerel bir ağ tokeni olan NUM ile donatmak için araçlar ve hizmetler zaten oluşturmuş olan Numbers Photo Network, Web3.0 varlık ekonomisini desteklemek için uygun bir biçimde donatılmıştır. 
Aşağıdaki tablo, 2022’nin ilk çeyreği için açıklanan ağın temel hizmet ücretlerini göstermektedir. Ücret yapısı NUM'a dayanmaktadır ve komisyonlar, kullanıcıların ağ eylemlerinden istikrarlı fiyatlarla yararlanabilmelerini sağlamak için üç ayda bir ayarlanacaktır. 
Yol haritasına ve geliştirme sürecine göre daha fazla esas hizmet bedeli açıklanabilir.
Geliştiriciler ve kuruluşlar ayrıca, fotoğrafları kaydetmek ve bunlara erişmek ve ayrıca zincir üzerindeki kaynağı, Web3.0 adreslerini ve sertifikaları almak için Numbers hizmetlerinden (Seal API) yararlanabilir. Kullanıcı hizmetlerine benzer şekilde, API kullanıcılarının sabit komisyonlara sahip olmalarını sağlamak için komisyonlar üç ayda bir ayarlanacaktır.
Ekosistem Uygulamaları
Instagram veya diğer sosyal medya platformları gibi Web2.0 hizmetlerine yüklenen fotoğrafların oluşturucu imzalarını, sahiplik kayıtlarını, aktarım geçmişini ve içerik kaynağını keşfetmek, mevcut webin doğası gereği imkansız değilse de zordur. Numbers merkezi olmayan Web3.0 fotoğraf ağı içinde, Numbers Protokolü sayesinde bu kayıtlar kolayca erişilebilir hale gelmiştir.
Numbers ağının yerel içerik protokolü olarak Numbers Protocol, içeriğin saflığını ve izlenebilirliğini sağlamak için en son Web3.0 ve içerik kaynak teknolojisinden yararlanır. İçeriğin orijinalliği garanti edildiğinde, 3. tarafların kayıt, para kazanma vb. aracılığıyla kullanıcıların Web3.0 alanında fotoğraf varlıklarıyla gezinmelerine yardımcı olmak için yenilikçi fotoğraf hizmetleri sunmanın yolunu açar.
NFT pazar yeri, Web3.0 depolama, sosyal medya platformları ve stok görüntü/video hizmetlerini içeren (ancak bunlarla sınırlı olmayan) bu üçüncü taraf hizmetleri Ekosistem Uygulamaları olarak adlandırıyoruz. Ekosistem uygulamaları açısından, ağın uzun süreli çalışmasını sağlamak için tahsil edilen toplam ödemelerin %0,5'i tahsil edilecektir. Ekosistem uygulaması "kullanımı ücretsiz" ise, kullanıcılar Ekosistem Uygulamasını Numbers ağında kullandıklarında yine de bir taban ödeme uygulanacaktır.
Numbers Protocol'ün benimsenmesinde kaydettiğimiz ilerlemeyi temsil eden son iki ayda duyurulan ortaklıkları burada bulabilirsiniz.
Deflasyonist Token Ekonomisi
Kayıtlı varlıklar tarafından oluşturulan değer, NUM jetonu geri almak ve yakım için kullanılacaktır. Yakılacak token sayısı, ağın benimsenmesine ve kaynağın gelirine göre belirlenecektir. Ağ değerinin %20'sini NUM'u geri almak için kullanacağız ve tüm NUM'un (500MM) %50'sini geri alana kadar onları yakacağız. İlk NUM jeton yakma işleminin Mart ayında yapılması planlanıyor. İlk çeyrekte yakılacak toplam NUM miktarı, toplam kayıtlı varlıklara bağlı olacaktır. 
N_yakım = N_yeni_kaydedilmiş_varlıklar * R * 20%
Sabit R, yeni kaydedilen her varlığın değerini temsil eder ve üç aylık benimseme oranı, piyasa değeri ve ayrıca NUM fiyatının bir fonksiyonudur.
Yakılan jetonlar dolaşımdaki arzdan kaldırılacaktır.
Mevcut varlık büyüme eğrisinin Instagram'ın aktif kullanıcılarının büyümesine benzer olduğunu fark ettik. Bunun bir sonucu olarak, Instagram'ın büyüme eğrisine Numbers ağındaki kayıtlı varlıkların gelecekteki büyümesinin bir tahmini olarak başvurabiliriz.
Yukarıdaki grafikte, gri çizgi, Ekim 2010'daki kuruluşundan Nisan 2017'ye kadar Instagram'ın aktif aylık kullanıcılarının büyümesini gösterir. Düz mavi çizgi, Numbers ağındaki (Hizmet Lansmanından Aralık 2021'e kadar) mevcut varlık büyümesini gösterirken, mavi noktalı çizgi, Numbers ağının öngörülen büyümesini temsil eder.

R sabiti# 2022'nin ilk çeyreği için 0,5 olarak belirlendi. Öngörülere göre, tahmini yakılan tokenler şöyle olacak
N_yakım_Q1_2022 ~ 30M * 0,5 * %20 ~ 3M
Belirteç yazma işlemini ilk kez gerçekleştirdiğimiz için N_yeni_kaydedilmiş_varliklar, Numbers Protocol ağında kayıtlı toplam varlıklara eşit olacaktır (Aralık 2020'den Mart 2022'ye kadar).
NUMBERSDAO
Topluluk odaklılık ve merkeziyetsizlik, Numbers Protocol'ün temel değerleridir. Değerlerimizin bir yansıması olarak, merkezi olmayan yönetişim yoluyla topluluğumuz için şeffaf ve demokratik bir alan yaratmayı umuyoruz. Bir Merkezi Olmayan Otonom Kuruluş (DAO) kurmak, topluluğumuzdan gelen sesleri ve girdileri duymamız için açık bir alan yaratmanın yanı sıra, DAO üyelerini Numbers ağının geleceği için ortak hedeflere ulaşmaları için karar verme yetkisiyle güçlendirmek için ilk adımımızdır.
Varlık ve Deflasyonist Token Ekonomi planının topluluk incelemesi yarın (14 Ocak 2022) başlayıp 13 Şubat 2022'ye kadar devam ediyor. Topluluk incelemesinden gelen geri bildirim ve öneriler, gelecekteki olası iyileştirmeler olarak değerlendirilecek ve NUMBERSDAO tarafından dikkatle değerlendirilecek ve oylanacak.
NUMBERSDAO'nun temel yönetişim kuralları, Aralık ayında topluluk incelemesinden geçmiştir. İlk anketin daha fazla ayrıntısı Ocak 2022'nin sonunda yayınlanacak.
Numbers Protokol Hakkında
Numbers, dijital medyada topluluk, değer ve güven oluşturmak için merkezi olmayan bir fotoğraf ağı oluşturuyor. Numbers Protocol, dijital görsel medyanın doğasını varlıklar olarak yeniden tanımlar ve Numbers ağı içinde yer alan (Capture uygulaması, Seal API ve Trace web sitesi) fotoğrafları ve videoları kaydetmeye ve almaya yönelik bir araç paketinin ve ayrıca CaptureClub pazarının ve bir tescilli NFT Arama Motorunun temel yapı taşıdır. Numbers, dijital medyanın saflığını savunur ve insanların görüntülerimizle çevremizdeki dünya arasındaki etkileşimler hakkında daha eleştirel düşünmelerini sağlar.

**Comment by sofiayan0523** [comment]
@Serfiraz46 the translation is approved and pushed to the main article with your name, please check here: https://hackmd.io/hkxEHYdOS6K3BV63wCKTyg?view#Turkish

Thank you for your contribution, please [fill out the form](https://airtable.com/shrHsGWu0uN1r2sYj) to claim the reward :)
