### ISSUE TITLE
[Translation demand - Chinese] : Mucha artwork NFT issued by HTC Vive Art are monitored by Numbers Protocol

### ISSUE THREAD

**Issue by sofiayan0523** [numbersprotocol/community-support#45]
Looking for Chinese translators to translate [Mucha artwork NFT issued by HTC Vive Art are monitored by Numbers Protocol](https://medium.com/numbers-protocol/mucha-artwork-nft-issued-by-htc-vive-art-are-monitored-by-numbers-protocol-e927a6e38550)

Leave your translation in this issue comment to become our Tier 1 Ambassador!

--

- How to participate
- > Translate at least one paragraph of the selected article.
- > The translation should be done as the Github issue comment.
- > Share the link of the comment in the local community and get at least 3 likes on Github.
- > If there are two comments linked to the same paragraph and both collect 3 likes, the earlier one wins.
- > The translation needs to be fluent and factually correct and should not be copied directly from Google translate or similar apps (any attempt to copy-paste directly from Google Translate will result in your dismissal from the Ambassador Program).

- Rewards
- > 10 NUM per paragraph per language
- > Bounty-based, the selected article will be announced every Friday

**Comment by jixieji2017** [comment]
## **Numbers Protocol正监控由HTC Vive Art发行的Mucha艺术NFT**


从内容本身开始，数字内容的信任需要一个全面的解决方案，从而延展到它所在的生态系统


![This is an image](https://miro.medium.com/max/1400/1*tH_u-nhKnx9qxlGBaExFmg.png)
                                                    _Numbers Protocol，记录的分类帐_


### **数字媒体是人们生活的重要组成部分，但存在着与版权、错误信息以及巨鲸控制相关的信任问题**

2021年是区块链年，随即带动了NFT的繁荣。在繁荣的最初几个月，NFT的炒作围绕着不可伪造的独特概念以及保证区块链所有权展开。许多人宣称 NFT 可以解决围绕数字内容、Web 3.0以及 元宇宙到来的所有问题。

尽管区块链是有前途的技术，但这一概念与事实相去甚远，因为 "复制粘贴 "的行为仍然存在。举个例子，一位NFT爱好者在Twitter上自豪地宣布他以高达157000美元的价格购买了一张CryptoPunk。他的推文收到了无数的回复，但同样的图片仅仅通过复制粘贴就可以免费获得。


### **数字内容的信任需要一个全面的解决方案，从内容本身开始，并延伸到它所处的生态系统**

**去中心化的照片网络和Web3搜索引擎**

Numbers Protocol是一个去中心化的图片网络，它结合了最新的Web3.0和内容证明技术，来解决数字内容领域的核心问题。
我们通过优先考虑内容本身来做到这一点。通过利用上下文元数据、数字签名、不可变的区块链记录以及加入C2PA，我们能够创建可验证的数字内容，最重要的是能够 "为自己发声"。

![image](https://user-images.githubusercontent.com/29139809/150051731-947e97a1-5c8f-4d92-bd3d-274c71550b7c.png)

为了让NFT世界更加真实，[我们在2021年12月发布了世界上第一个用于NFT的Web 3.0搜索引擎](https://cointelegraph.com/press-releases/numbers-protocol-announces-worlds-first-web-30-search-engine-for-nfts)。作为一个基于内容的搜索引擎，用户可以在不知道其代币地址或代币ID的情况下上传文件，并检索与NFT文件相关的资产历史和其他细节。目前，NFT搜索引擎支持8个主要市场，3个区块链网络，近30M资产和20K+智能合约，数据覆盖面每天都在增加。


### 我们相信，Web3.0搜索引擎及其基于内容的透明搜索结果，将带领我们进入一个更真实的互联网。

**监控、扫描和验证，带来更安全的生态系统**

同样的搜索引擎技术也可用于执行NFT资产监控、资产扫描和资产验证服务。

**资产监控**服务监控区块链网络上新产生的资产，如果发现潜在的盗窃行为，就会发送电子邮件。监测的资产是那些保存在元数据扩展中并在链上注册的资产。例如，一旦母合约被注册，出现在OpenSea上的ERC721和ERC1155代币的图像及其标准缩略图将被监控。

**资产扫描**在NFT世界中扫描，以找到有潜在侵犯版权的现有项目。

**资产验证**包括相似图像扫描和社区报告，以验证资产。类似图像扫描利用计算机视觉来寻找网络中的类似项目。社区报告是利用社区来标记可疑物品的验证。去中心化的一个核心要素是社区，以及投入时间和精力来保持其生态系统纯净的愿望。

这些服务不仅帮助NFT市场创造一个更干净的交易环境，而且还可能帮助创作者在数字世界中分享和授权他们的作品而感到更安全。


### **NFT是最终答案吗？也许还不是**

2021年12月，HTC的VIVE Arts与Mucha基金会合作发行NFT，并将其美丽、知名的艺术作品带到Web3.0空间和Metaverse。为了确保这些高质量的NFTs的完整性，Numbers Protocol被要求使用上述服务来监测Mucha基金会的NFTs。该系统成功地报告了对Mucha作品的潜在版权侵犯行为。在撰写本报告时，共有1个项目被资产监控器发现，7个项目被资产扫描器发现，还有几十个社区的可疑报告。

尽管不能直接用技术覆盖法律行动和知识产权许可，但Web3.0技术提供了检测侵权的手段，以便向有关方面（HTC VIVE Arts和OpenSea）提交报告并采取后续行动。此外，基于实质的真实性保证是以Numbers搜索引擎上标有 "购买前要小心 "的NFT的形式提供给客户的。

![image](https://user-images.githubusercontent.com/29139809/150053683-36c29ee9-f04d-4414-b742-6a07cc5a9d3c.png)


_通过点击CID栏旁边的Numbers图标，用户还可以查看带有更多细节的扫描结果_

![image](https://user-images.githubusercontent.com/29139809/150053659-7a780925-cf53-4cb0-a41e-6b3bd7f3a2f9.png)



### **带有NUM的Web 3.0，一个更具可信度的、更纯净的互联网**

NUM作为原生网络代币，在这个生态系统中也发挥着重要作用。

### **用户可以用NUM进行支付，以使用搜索引擎服务，NUM也可用于鼓励社区报告和发现潜在的欺诈项目。**

数字内容的信任需要一个全面的解决方案，从内容本身开始，延展到其所在的生态系统。通过扩大Numbers的生态系统并与越来越多的NFT服务整合，我们将能够把该技术应用于更广泛的数字内容行业。技术和创新的精神是对解决现实世界问题的渴望。

在Numbers，我们正在通过提供透明地访问数据的手段，来解决数字资产领域的斗争。虽然很多技术还处于起步阶段，但我们很自豪地分享，有了Number协议，就有可能建立一个更纯净、更值得信赖的互联网。

有兴趣查看真实Mucha艺术品的 Web 3.0 搜索结果吗？
请点击: https://nftsearch.site/?mid=bafybeibpsannhnmo3l2427igujkn3lckux2so5vkt7yypfdxqvytyurnfu

查看 HTC 上由 Mucha Foundation 发布的 ore Mucha 艺术品 NFT https://nft.vivearts.com/en_US/

**Comment by sofiayan0523** [comment]
@jixieji2017  the translation is approved and pushed to the main article with your name, please check here:https://hackmd.io/jm8TOiEIQE2h8g0rxv71lQ?view#Chinese

Thank you for your contribution, please [fill out the form](https://airtable.com/shrHsGWu0uN1r2sYj) to claim the reward :)
