### ISSUE TITLE
[Translation demand - Japanese] : Mucha artwork NFT issued by HTC Vive Art are monitored by Numbers Protocol

### ISSUE THREAD

**Issue by sofiayan0523** [numbersprotocol/community-support#46]
Looking for Japanese translators to translate [Mucha artwork NFT issued by HTC Vive Art are monitored by Numbers Protocol](https://medium.com/numbers-protocol/mucha-artwork-nft-issued-by-htc-vive-art-are-monitored-by-numbers-protocol-e927a6e38550)

Leave your translation in this issue comment to become our Tier 1 Ambassador!

--

- How to participate
- > Translate at least one paragraph of the selected article.
- > The translation should be done as the Github issue comment.
- > Share the link of the comment in the local community and get at least 3 likes on Github.
- > If there are two comments linked to the same paragraph and both collect 3 likes, the earlier one wins.
- > The translation needs to be fluent and factually correct and should not be copied directly from Google translate or similar apps (any attempt to copy-paste directly from Google Translate will result in your dismissal from the Ambassador Program).

- Rewards
- > 10 NUM per paragraph per language
- > Bounty-based, the selected article will be announced every Friday

**Comment by BabyChocopie** [comment]
翻訳した記事をMediumに載せました。よかったらlikeをお願いします！
I have posted translated article on Medium

https://link.medium.com/s0TuclciYmb

**Comment by sofiayan0523** [comment]
@BabyChocopie the translation is approved and pushed to the main article with your medium link, please check the [main article page](https://medium.com/numbers-protocol/mucha-artwork-nft-issued-by-htc-vive-art-are-monitored-by-numbers-protocol-e927a6e38550).

Thank you for your contribution, please [fill out the form](https://airtable.com/shrHsGWu0uN1r2sYj) to claim the reward :)
