### ISSUE TITLE
[Translation demand - Spanish] : Mucha artwork NFT issued by HTC Vive Art are monitored by Numbers Protocol

### ISSUE THREAD

**Issue by sofiayan0523** [numbersprotocol/community-support#47]
Looking for Spanish translators to translate [Mucha artwork NFT issued by HTC Vive Art are monitored by Numbers Protocol](https://medium.com/numbers-protocol/mucha-artwork-nft-issued-by-htc-vive-art-are-monitored-by-numbers-protocol-e927a6e38550)

Leave your translation in this issue comment to become our Tier 1 Ambassador!

--

- How to participate
- > Translate at least one paragraph of the selected article.
- > The translation should be done as the Github issue comment.
- > Share the link of the comment in the local community and get at least 3 likes on Github.
- > If there are two comments linked to the same paragraph and both collect 3 likes, the earlier one wins.
- > The translation needs to be fluent and factually correct and should not be copied directly from Google translate or similar apps (any attempt to copy-paste directly from Google Translate will result in your dismissal from the Ambassador Program).

- Rewards
- > 10 NUM per paragraph per language
- > Bounty-based, the selected article will be announced every Friday

**Comment by RafaVM89** [comment]
Las obras de arte NFT emitidas por HTC Vive Art están supervisadas por Numbers Protocol.

La confianza en los contenidos digitales requiere una solución integral que parta del propio contenido y se extienda al ecosistema en el que reside.

Los medios digitales son una parte importante de nuestras vidas, pero existen problemas de confianza relacionados con los derechos de autor, la desinformación y el control centralizado.

2021 fue el año del blockchain y con él llegó el boom del NFT. En los primeros meses del boom, el bombo y platillo en torno a los NFT era la propiedad garantizada por blockchain y la noción de que no fungible significaba único. Muchos proclamaron las NFT como la solución a todos los problemas que rodean a los contenidos digitales y la llegada del metaverso de la Web 3.0.

A pesar de ser una tecnología prometedora, esta noción está muy lejos de la realidad, ya que el comportamiento de "hacer clic con el botón derecho y guardar" sigue existiendo. Como ejemplo de esto, un entusiasta de la NFT anunció con orgullo su compra de un CryptoPunk por la friolera de 157.000 dólares en Twitter. Su anuncio recibió innumerables respuestas con la misma imagen adquirida de forma gratuita simplemente haciendo clic con el botón derecho y guardando.
La confianza en los contenidos digitales requiere una solución integral que parta del propio contenido y se extienda al ecosistema en el que reside.

**RED FOTOGRÁFICA DESCENTRALIZADA Y MOTOR DE BÚSQUEDA WEB3**

Numbers Protocol es una red fotográfica descentralizada que combina lo último en tecnología Web3.0 y de procedencia de contenidos para abordar los problemas fundamentales del espacio de los contenidos digitales.
Lo hacemos dando prioridad al propio contenido. Al aprovechar los metadatos contextuales, las firmas digitales, los registros inmutables de la cadena de bloques y las inyecciones C2PA, somos capaces de crear contenidos digitales que son verificables y, lo que es más importante, que pueden "hablar por sí mismos".

Con el fin de aportar una mayor autenticidad al espacio de las NFT, en diciembre de 2021 lanzamos el primer motor de búsqueda web 3.0 del mundo para las NFT. Como motor de búsqueda basado en el contenido, los usuarios pueden cargar un archivo sin conocer su dirección de token o su ID de token, y recuperar el historial de activos y otros detalles asociados al archivo NFT. Actualmente, el motor de búsqueda de NFT admite 8 mercados principales, 3 redes de blockchain, casi 30M de activos y más de 20K contratos inteligentes con una cobertura de datos que aumenta diariamente.

**SUPERVISAR, ESCANEAR Y VERIFICAR PARA CONSEGUIR ECOSISTEMAS MÁS SEGUROS**

La misma tecnología de motor de búsqueda también se puede utilizar para realizar los servicios NFT Asset Monitor, Asset Scan y Asset Verify.
**_El servicio Asset Monitor_** supervisa los activos recién generados en la red Blockchain y envía correos electrónicos de posibles robos si los descubre. Los activos supervisados son los que se guardan en la extensión de metadatos y se registran en la cadena. Por ejemplo, las imágenes de los tokens ERC721 y ERC1155 y su miniatura estándar que aparecen en OpenSea se monitorizarán una vez que se registre el contrato principal.

**_Asset Scan_** escanea a través del espacio NFT para encontrar elementos existentes con potenciales violaciones de derechos de autor.

**_Asset Verify_** incluye tanto escaneos de imágenes similares como informes de la comunidad para verificar los activos. La exploración de imágenes similares utiliza la visión por ordenador para buscar elementos similares en la red. Un informe de la comunidad es una verificación que aprovecha la comunidad para señalar los elementos sospechosos. Uno de los pilares de la descentralización es la comunidad y el deseo de invertir tiempo y esfuerzo en mantener limpio su ecosistema.
Estos servicios no sólo ayudan a los mercados de NFT a crear un entorno comercial más limpio, sino que también pueden ayudar a los creadores a sentirse más seguros a la hora de compartir y licenciar su trabajo en el mundo digital.

¿SON LOS NFT LA RESPUESTA DEFINITIVA? TAL VEZ TODAVÍA NO...

En diciembre de 2021, VIVE Arts de HTC colaboró con The Mucha Foundation para emitir NFT y llevar sus hermosas y conocidas obras de arte al espacio Web3.0 y al Metaverso. Para garantizar la integridad de estas NFT de alta calidad, se recurrió a Numbers Protocol para supervisar las NFT de The Mucha Foundation mediante los servicios mencionados anteriormente. El sistema denunció con éxito posibles infracciones de los derechos de autor de la obra de Mucha. En el momento de escribir este artículo, había un total de **1 elemento encontrado por Asset Monitor, 7 elementos detectados por Asset Scan, y docenas de informes sospechosos por parte de la comunidad.**

A pesar de no poder cubrir las acciones legales y las licencias de propiedad intelectual directamente con la tecnología, la tecnología Web3.0 proporciona los medios para detectar las infracciones, de modo que se puedan presentar informes a las partes correspondientes (HTC VIVE Arts y OpenSea) y se puedan llevar a cabo las acciones posteriores. Además, se ofrecen garantías de autenticidad basadas en el contenido a los clientes en forma de NFT marcadas con "Tenga cuidado antes de comprar" en el motor de búsqueda de Numbers.

**

> Web 3.0 con NUM, un Internet más limpio y de confianza

**

NUM, como tokens nativo de la red, también desempeña un papel importante en este ecosistema.

La confianza en los contenidos digitales requiere una solución integral que parta del propio contenido y se extienda al ecosistema en el que reside. Al ampliar el ecosistema de Numbers e integrarlo con más y más servicios de NFT, podremos aplicar la tecnología a la industria de contenidos digitales en general. El espíritu de la tecnología y la innovación es el deseo de resolver problemas del mundo real.

En Numbers, estamos abordando los problemas del espacio de los activos digitales proporcionando los medios para acceder de forma transparente a los datos. Aunque gran parte de la tecnología está en pañales, nos enorgullece compartir que con el protocolo de Numbers es posible construir un Internet más limpia y fiable.

¿Está interesado en ver el resultado de la búsqueda en la Web 3.0 de obras de arte reales de Mucha?
Vaya aquí: https://nftsearch.site/?mid=bafybeibpsannhnmo3l2427igujkn3lckux2so5vkt7yypfdxqvytyurnfu

Consulta los NFT de obras de arte de Mucha publicados por la Fundación Mucha en la plataforma HTC ViveArt: https://nft.vivearts.com/en_US/


**

> Acerca del protocolo Numbers

**

Numbers está construyendo una red fotográfica descentralizada para crear comunidad, valor y confianza en los medios digitales. Su Protocolo Numbers redefine la naturaleza de los medios visuales digitales como activos y es la columna vertebral de un conjunto de herramientas para registrar y recuperar fotos y vídeos en la red Numbers -la aplicación Capture, la API Seal y el sitio web Trace-, además del mercado CaptureClub y un motor de búsqueda NFT propio. Numbers defiende la pureza de los medios digitales y permite a la gente pensar de forma más crítica sobre las interacciones entre nuestras imágenes y el mundo que nos rodea.

**Comment by RafaVM89** [comment]
Hello, good morning,
I have been working on the translation for weeks and I would like to get some feedback from moderators. My English is not native but I am trying. They have not spoken in three weeks, every Friday I notice that still no one has spoken.

Best regards.

**Comment by sofiayan0523** [comment]
@RafaVM89  the translation is approved and pushed to the main article with your name, please check here: https://hackmd.io/hkxEHYdOS6K3BV63wCKTyg?both#Spanish
Thank you for your contribution, please [fill out the form](https://airtable.com/shrHsGWu0uN1r2sYj) to claim the reward :)
