### ISSUE TITLE
[Translation demand - French] : Mucha artwork NFT issued by HTC Vive Art are monitored by Numbers Protocol

### ISSUE THREAD

**Issue by sofiayan0523** [numbersprotocol/community-support#48]
Looking for French translators to translate Mucha artwork NFT issued by HTC Vive Art are monitored by Numbers Protocol

Leave your translation in this issue comment to become our Tier 1 Ambassador!

--

- How to participate
> - Translate at least one paragraph of the selected article.
> - The translation should be done as the Github issue comment.
> - Share the link of the comment in the local community and get at least 3 likes on Github.
> - If there are two comments linked to the same paragraph and both collect 3 likes, the earlier one wins.
> - The translation needs to be fluent and factually correct and should not be copied directly from Google translate or similar apps (any attempt to copy-paste directly from Google Translate will result in your dismissal from the Ambassador Program).

- Rewards

> - 10 NUM per paragraph per language
> - Bounty-based, the selected article will be announced every Friday

**Comment by Frenchland42580** [comment]
La confiance dans le contenu numérique exige une solution globale qui part du contenu lui-même et s'étend à l'écosystème dans lequel il réside.

Les médias numériques occupent une place importante dans nos vies, mais il existe des problèmes de confiance liés aux droits d'auteur, à la désinformation et au contrôle centralisé.
2021 a été l'année de la blockchain et, avec elle, du boom de la NFT. Au cours des premiers mois de ce boom, le battage médiatique autour des NFT reposait sur la propriété garantie par la blockchain et sur l'idée que non-fongible signifiait unique. Beaucoup ont proclamé que les NFT étaient la solution à tous les problèmes liés au contenu numérique et à l'arrivée du Web 3.0 dans le metaverse.
Bien qu'il s'agisse d'une technologie prometteuse, cette notion est loin de la vérité car le comportement "clic droit et sauvegarde" existe toujours. À titre d'exemple, un passionné de NFT a fièrement annoncé sur Twitter l'achat d'un CryptoPunk pour la somme astronomique de 157 000 dollars américains. Son annonce a reçu d'innombrables réponses avec la même image acquise gratuitement par simple clic droit et sauvegarde.
La confiance dans le contenu numérique exige une solution globale qui commence par le contenu lui-même et s'étend à l'écosystème dans lequel il réside.

**Réseau photo décentralisé et moteur de recherche Web3**

Numbers Protocol est un réseau photo décentralisé qui combine les dernières technologies du Web3.0 et de la traçabilité du contenu pour répondre aux problèmes fondamentaux de l'espace du contenu numérique.
Pour ce faire, nous donnons la priorité au contenu lui-même. En tirant parti des métadonnées contextuelles, des signatures numériques, des enregistrements blockchain immuables et des injections C2PA, nous sommes en mesure de créer un contenu numérique qui est vérifiable et, surtout, qui peut "parler de lui-même".
Afin d'apporter une meilleure authenticité à l'espace NFT, nous avons lancé le premier moteur de recherche Web 3.0 au monde pour les NFT en décembre 2021. En tant que moteur de recherche basé sur le contenu, les utilisateurs peuvent télécharger un fichier sans connaître son adresse ou son ID de jeton, et récupérer l'historique des actifs et d'autres détails associés au fichier NFT. Actuellement, le moteur de recherche NFT prend en charge 8 places de marché majeures, 3 réseaux de blockchain, près de 30 millions d'actifs et plus de 20 000 contrats intelligents, la couverture des données augmentant quotidiennement.

**Surveiller, scanner et vérifier pour rendre les écosystèmes plus sûrs**

La même technologie de moteur de recherche peut également être utilisée pour exécuter les services NFT Asset Monitor, Asset Scan et Asset Verify.

Le service **Asset Monitor** surveille les actifs nouvellement générés sur le réseau Blockchain et envoie des courriels pour signaler un vol potentiel s'il est découvert. Les actifs surveillés sont ceux conservés dans l'extension des métadonnées et enregistrés sur la chaîne. Par exemple, les images des jetons ERC721 et ERC1155 et leur vignette standard apparaissant sur OpenSea seront surveillées une fois que le contrat de référence sera enregistré.

**Asset Scan** scanne l'espace NFT pour trouver des éléments existants avec des violations potentielles de copyright.

**Asset Verify** comprend à la fois des scans d'images similaires et des rapports communautaires pour vérifier les actifs. Le balayage d'images similaires utilise la vision par ordinateur pour rechercher des éléments similaires dans le réseau. Un rapport communautaire est une vérification qui s'appuie sur la communauté pour signaler les éléments suspects. L'un des principes fondamentaux de la décentralisation est l'existence d'une communauté et la volonté d'investir du temps et des efforts pour maintenir son écosystème propre.

Ces services n'aident pas seulement les places de marché NFT à créer un environnement commercial plus propre, mais peuvent aussi aider les créateurs à se sentir plus en sécurité pour partager et obtenir des licences pour leurs œuvres dans le monde numérique.

**Le NFT est-il la réponse définitive ? Peut-être pas encore**

En décembre 2021, le VIVE Arts de HTC a collaboré avec la Fondation Mucha pour émettre des NFT et apporter ses magnifiques œuvres d'art bien connues dans l'espace Web3.0 et le Metaverse. Pour assurer l'intégrité de ces NFT de haute qualité, Numbers Protocol a été appelé à surveiller les NFT de la Fondation Mucha en utilisant les services mentionnés ci-dessus. Le système a signalé avec succès les violations potentielles du droit d'auteur de l'œuvre de Mucha. Au moment de la rédaction de cet article, il y avait au total 1 élément trouvé par Asset Monitor, 7 éléments détectés par Asset Scan, et des dizaines de rapports suspects par la communauté.
Bien qu'il ne soit pas possible de couvrir les actions en justice et les licences de propriété intellectuelle directement avec la technologie, la technologie Web3.0 fournit les moyens de détecter les infractions afin que les rapports puissent être déposés auprès des parties appropriées (HTC VIVE Arts et OpenSea) et que des actions ultérieures puissent avoir lieu. En outre, des garanties d'authenticité fondées sur la substance sont fournies aux clients sous la forme de NFT marqués de la mention "Soyez prudent avant d'acheter" sur le moteur de recherche Numbers.

En cliquant sur l'icône Numbers à côté de la colonne CID, les utilisateurs peuvent également afficher le résultat du scan avec plus de détails.

**Web 3.0 avec NUM, un Internet plus propre et plus fiable**

NUM, en tant que jetons de réseau natifs, joue également un rôle important dans cet écosystème.

La confiance dans le contenu numérique nécessite une solution complète qui part du contenu lui-même et s'étend à l'écosystème dans lequel il réside. En élargissant l'écosystème de Numbers et en l'intégrant à de plus en plus de services NFT, nous serons en mesure d'appliquer la technologie à l'ensemble du secteur du contenu numérique. L'éthique de la technologie et de l'innovation est le désir de résoudre les problèmes du monde réel.
Chez Numbers, nous nous attaquons aux difficultés de l'espace des actifs numériques en fournissant les moyens d'accéder aux données de manière transparente. Bien que la technologie n'en soit qu'à ses débuts, nous sommes fiers de partager le fait qu'avec le protocole Numbers, il est possible de construire un Internet plus propre et plus fiable.
Vous souhaitez voir le résultat de la recherche Web 3.0 d'une véritable œuvre d'art de Mucha ?

**Comment by sofiayan0523** [comment]
@Frenchland42580 the translation is approved and pushed to the main article with your name, please check here: https://hackmd.io/jm8TOiEIQE2h8g0rxv71lQ#French

Thank you for your contribution, please [fill out the form](https://airtable.com/shrHsGWu0uN1r2sYj) to claim the reward :)
