### ISSUE TITLE
[Translation demand - German] : Mucha artwork NFT issued by HTC Vive Art are monitored by Numbers Protocol

### ISSUE THREAD

**Issue by sofiayan0523** [numbersprotocol/community-support#49]
Looking for Germany translators to translate [Mucha artwork NFT issued by HTC Vive Art are monitored by Numbers Protocol](https://medium.com/numbers-protocol/mucha-artwork-nft-issued-by-htc-vive-art-are-monitored-by-numbers-protocol-e927a6e38550)

Leave your translation in this issue comment to become our Tier 1 Ambassador!

--

- How to participate
> - Translate at least one paragraph of the selected article.
> - The translation should be done as the Github issue comment.
> - Share the link of the comment in the local community and get at least 3 likes on Github.
> - If there are two comments linked to the same paragraph and both collect 3 likes, the earlier one wins.
> - The translation needs to be fluent and factually correct and should not be copied directly from Google translate or similar apps (any attempt to copy-paste directly from Google Translate will result in your dismissal from the Ambassador Program).

- Rewards
> - 10 NUM per paragraph per language
> - Bounty-based, the selected article will be announced every Friday

**Comment by lennartvanEeden** [comment]
Paragraph 2 : 

Der Übergang vom Web2.0 zum Web3.0 bringt einen grundlegenden Wandel in der Art und Weise mit sich, wie Assets betrachtet werden und wie Fotodienste funktionieren. Im Web3.0 werden Assets registriert und haben einen klaren Eigentumsnachweis. Diese Unterscheidung ermöglicht es, dass Assets einen Wert haben und führt den Begriff der Asset Economy ein. Sie öffnet auch die Tür für neue Arten von Fotodiensten im Web3.0-Raum.
Das Numbers Photo Network hat bereits Tools und Dienste entwickelt, die es den Nutzern ermöglichen, Assets im Web3.0 zu registrieren, und verfügt über einen eigenen Netzwerk-Token, NUM, der die Asset Economy im Web3.0 unterstützen kann.
Die folgende Tabelle zeigt die für das erste Quartal 2022 angekündigten Grundgebühren des Netzwerks. Die Gebührenstruktur basiert auf NUM, und die Gebühren werden vierteljährlich angepasst, um sicherzustellen, dass die Nutzer die Aktionen des Netzwerks zu stabilen Preisen nutzen können.
In Abhängigkeit von der Roadmap und dem Entwicklungsfortschritt können weitere Basisdienstgebühren angekündigt werden.
Entwickler und Unternehmen können auch Numbers-Dienste (Seal API) nutzen, um Fotos zu registrieren und darauf zuzugreifen sowie On-Chain-Provenienz, Web3.0-Adressen und Zertifikate abzurufen. Ähnlich wie bei den Nutzerdiensten werden die Gebühren vierteljährlich angepasst, um sicherzustellen, dass die API-Nutzer stabile Gebühren zahlen können.

**Comment by lennartvanEeden** [comment]
Rest : 

Überwachen, Scannen und Prüfen für ein sichereres Ökosystem
Die gleiche Suchmaschinentechnologie kann auch für die NFT-Dienste Asset Monitor, Asset Scan und Asset Verify verwendet werden.
Der Dienst Asset Monitor überwacht die neu erzeugten Vermögenswerte im Blockchain-Netzwerk und sendet bei Entdeckung eines potenziellen Diebstahls eine E-Mail. Die überwachten Vermögenswerte werden in der Metadatenerweiterung gespeichert und auf der Kette registriert. So werden beispielsweise Bilder von ERC721- und ERC1155-Token und deren Standard-Thumbnails, die auf OpenSea erscheinen, überwacht, sobald der übergeordnete Vertrag registriert ist.
Asset Scan durchsucht den NFT-Raum, um vorhandene Objekte mit potenziellen Urheberrechtsverletzungen zu finden.
Asset Verify umfasst sowohl Scans ähnlicher Bilder als auch Community-Berichte zur Überprüfung von Assets. Bei der Ähnlichkeitsprüfung wird mithilfe von Computer Vision nach ähnlichen Objekten im Netzwerk gesucht. Ein Community-Bericht ist eine Überprüfung, die die Community nutzt, um verdächtige Objekte zu markieren. Ein Kernpunkt der Dezentralisierung ist eine Gemeinschaft und der Wunsch, Zeit und Mühe zu investieren, um ihr Ökosystem sauber zu halten.
Diese Dienste tragen nicht nur dazu bei, dass NFT-Marktplätze eine sauberere Handelsumgebung schaffen, sondern können auch dazu beitragen, dass sich die Urheber sicherer fühlen, wenn sie ihre Arbeit in der digitalen Welt teilen und lizenzieren.
Ist NFT die endgültige Antwort? Vielleicht noch nicht
Im Dezember 2021 arbeitete HTCs VIVE Arts mit der Mucha Foundation zusammen, um NFTs auszugeben und ihre wunderschönen, bekannten Kunstwerke in den Web3.0-Raum und das Metaverse zu bringen. Um die Integrität dieser hochwertigen NFTs zu gewährleisten, wurde Numbers Protocol beauftragt, die NFTs der Mucha Foundation mit Hilfe der oben genannten Dienste zu überwachen. Das System meldete erfolgreich mögliche Urheberrechtsverletzungen an Muchas Werk. Zum Zeitpunkt der Erstellung dieses Berichts gab es insgesamt 1 von Asset Monitor gefundenes Objekt, 7 von Asset Scan entdeckte Objekte und Dutzende von verdächtigen Meldungen aus der Community.
Obwohl die Technologie nicht in der Lage ist, rechtliche Schritte und IP-Lizenzen direkt abzudecken, bietet die Web3.0-Technologie die Möglichkeit, Verstöße zu erkennen, so dass Berichte an die entsprechenden Parteien (HTC VIVE Arts und OpenSea) weitergeleitet werden können und anschließende Maßnahmen ergriffen werden können. Darüber hinaus werden den Kunden substanzbasierte Echtheitsgarantien in Form von gekennzeichneten NFTs mit der Aufschrift "Be Careful Before You Buy" (Vorsicht vor dem Kauf) in der Numbers-Suchmaschine geboten.
Durch Anklicken des Numbers-Symbols neben der CID-Spalte können die Nutzer auch das Scan-Ergebnis mit weiteren Details einsehen.

Web 3.0 mit NUM, ein saubereres Internet mit Vertrauen
NUM, der native Netzwerk-Token, spielt ebenfalls eine wichtige Rolle in diesem Ökosystem.
Die Benutzer können mit NUM bezahlen, um den Suchmaschinendienst zu nutzen, und NUM kann auch verwendet werden, um die Gemeinschaft zu ermutigen, potenzielle Betrugsobjekte zu melden und zu finden.
Das Vertrauen in digitale Inhalte erfordert eine umfassende Lösung, die bei den Inhalten selbst beginnt und sich auf das Ökosystem erstreckt, in dem sie sich befinden. Durch die Erweiterung des Ökosystems von Numbers und die Integration mit immer mehr NFT-Diensten werden wir in der Lage sein, die Technologie auf die gesamte Branche der digitalen Inhalte anzuwenden. Das Ethos von Technologie und Innovation ist der Wunsch, Probleme der realen Welt zu lösen.
Bei Numbers setzen wir uns mit den Problemen im Bereich der digitalen Inhalte auseinander, indem wir Mittel für einen transparenten Datenzugriff bereitstellen. Obwohl die Technologie noch in den Kinderschuhen steckt, sind wir stolz darauf, dass es mit Numbers Protocol möglich ist, ein saubereres, vertrauenswürdigeres Internet zu schaffen.

Über Numbers Protocol
Numbers baut ein dezentrales Fotonetzwerk auf, um Gemeinschaft, Wert und Vertrauen in digitale Medien zu schaffen. Das Numbers Protocol definiert die Natur digitaler visueller Medien als Assets neu und ist das Rückgrat einer Reihe von Tools zum Registrieren und Abrufen von Fotos und Videos im Numbers-Netzwerk - die Capture-App, Seal API und Trace-Website - sowie der CaptureClub-Marktplatz und eine proprietäre NFT-Suchmaschine. Numbers setzt sich für die Reinheit digitaler Medien ein und ermöglicht es den Menschen, kritischer über die Wechselwirkungen zwischen unseren Bildern und der Welt um uns herum nachzudenken.

**Comment by sofiayan0523** [comment]
@lennartvanEeden Seems it's the translation of <Numbers Protocol Asset & Deflationary Token Economy> ^^"

The translation is approved and pushed to the main article with your name, please check here: https://hackmd.io/hkxEHYdOS6K3BV63wCKTyg?view#German
Thank you for your contribution, please [fill out the form](https://airtable.com/shrHsGWu0uN1r2sYj) to claim the reward :)
