### ISSUE TITLE
[Translation demand - Arabic] Numbers Protocol Asset & Deflationary Token Economy

### ISSUE THREAD

**Issue by sofiayan0523** [numbersprotocol/community-support#51]
Looking for Arabic translators to translate [<Numbers Protocol Asset & Deflationary Token Economy>](https://medium.com/numbers-protocol/numbers-protocol-asset-deflationary-token-economy-aeb0336e3711)

Leave your translation in this issue comment to become our Tier 1 Ambassador!

--
- How to participate
> - Translate **at least one paragraph of the selected article**.
> - **The translation should be done as the Github issue comment.**
> - **Share the link of the comment in the local community and get at least 3 likes on Github**.
> - If there are two comments linked to the same paragraph and both collect 3 likes, the earlier one wins.
> - The translation needs to be fluent and factually correct and should not be copied directly from Google translate or similar apps (any attempt to copy-paste directly from Google Translate will result in your dismissal from the Ambassador Program).

- Rewards
> - `10 NUM` per paragraph per language
> - Bounty-based, the selected article will be announced every Friday

**Comment by Cryptoguy86** [comment]
اصل Numbers Protocol والاقتصاد الرمزي الانكماشي
 
شبكة الصور اللامركزية Numbers
يقوم Numbers على انشاء شبكة من الصور الامركزية لتوفير الفائدة القيمة والثقة المجتمعية في الوسط الاعلامي الرقمي. حيث يقوم Numbers Protocol بحد ذاته على اعادة التعريف للوسائط المرئية الرقمية لمجموعة من الادوات كتسجيل واسترجاع الصور والفيديوهات مثل العامود الفقري في شبكة Numbers . ويشمل:
Capture app : هي اول كاميرا في العالم حيث يمكن للمستخدم تسجيل الصور بسهولة واستخدام تطبيقات Web 3.0
- Seal API: يمكن لاصحاب المؤسسات والمستثمرين من استخدام Numbers API لتسجيل الصور الخاصة بهم والاستفادة من Web3.0 لادخال عناوينهم وشهاداتهم.
- Certificates: وتحتوي على شهادات مصدقة من اصل المنشأ.
- CaptureClub: وهو السوق المحلي NFT والذي يتيح لمبتكروا الصور من بيع ومشاركة اعمالهم .
- محرك البحث NFT: Web3.0 NFT وهو اول محرك بحث يقوم بمساعدة المستخدمين بالتحقق من ماضي ال NFTs  والتجنب من اي عملية نصب يمكن ان تحدث.
 
يقوم Numbers بدعم نزاهة الوسائط الرقمية ويتيح الفرصة  للناس للتفكير العميق بشكل نقدي اكثر تجاه التفاعلات الحاصلة بين صورتنا وبين العالم من حولنا. ان الهدف الاساسي منNumbers هو توثيق الصور المصدقة  (بما في ذلك الصور والفيديوهات) لانشاء شبكة من الصور اللامركزية في Web3.0. ولكي يتحقق هذا الهدف بشكل كامل, نحن نعمل على تقديم الاقتصاد الرمزي الانكماشي – وهو عبارة عن نظام ينفذ كل ثلاثة اشهر لمعاينة رسوم الخدمات واعادة حساب عدد الرموز التي تم اعادة شرائها وحرقها

**Comment by Cryptoguy86** [comment]
Web 3.0 اصول الاقتصاد
يحقق الانتقال من Web2.0 ال Web3.0 الى تغيير حيوي بكيفية عرض الاصول وتنفيذ خدمات الصور. يتم تسجيل الاصول في Web3.0 وتكون لها سجل ملكية واضحة. يتيح هذا التمييز للاصول ان يكون ذات اهمية وذات قدرة على تقديم فكرة عن اصل الاقتصاد. كما انه يتيح فرصة  لاستعراض اشكال جديدة من خدمات الصور في مجال Web3.0 .
 
قد تم بالفعل انشاء ادوات وخدمات خاصة لتزويد المستخدم بها لكي يقوم بتسجيل الاصول في Web3.0 وكذلك شبكة الرموز المحلية و NUM وشبكة الصور Numbers التي قد تم تجهيزها باقتدار لدعم Web3.0 اصول الاقتصاد.
 
يوضح الجدول الاتي رسوم الخدمات للشبكة الاساسية في الربع الاول من عام 2022 . ويستند هيكل الرسوم على ان يو ام و تعدل الرسوم كل ثلاثة اشهر لضمان استفادة المستخدم من اعمال الشبكة ضمن اسعار ثابتة.
 
0.5 NUM
التسجيل (لكل اصل جديد)
1 NUM
Gift Capture NFT (يتضمن السك والتحويل)
1 NUM
السك واللائحة NFT على CaptureClub
0.5% من اجمال رسوم الخدمات
Ecosystem Apps
 
يمكن ان يتم الاعلان عن المزيد من رسوم الخدمات وفق خارطة الطريق و تقدم التنمية.
ويمكن لاصحاب المؤسسات والمستثمرين الاستفادة بشكل فعال من خدمات Numbers (Seal API) من تسجيل وادخال الصور والعناوين والشهادات بالاضافة الى استرجاعها من المصدر, Web3.0. بالمشابهه مع خدمات المستخدم, حيث يتم تعديل الرسوم  كل ثلاثة اشهر لضمان المستخدم API على حصوله على رسوم ثابت.

**Comment by Cryptoguy86** [comment]
NUMBERSDAO
من القيم الاساسية ل Numbers Protocol هو تركيز المجتمع واللامركزية. انعكاسا لقيمنا نامل في خلق مساحة شفافة وديمقراطية لمجتمعنا من خلال الحكم اللامركزي. ان خطوتنا الاولى هي انشاء منظمة مستقلة لامركزية وذلك لانشاء مساحة واسعة لنا لسماع الاصوات والمداخلات من مجتمعنا بالاضافة الى تمكين اعضاء (DAO) من خلال اتخاذ القرارات المهمة لمتابعة الاهداف المشتركة بينهم نحو مستقبل افضل لشبكة Numbers.
يوم غد صباحا الموافق (14 يناير 2022) سوف يبدأ مراجعة المجتمع لخطة اقتصاد العملة الانكماشية والاصول لغاية 13 فبراير 2022. سوف تعتبر الملاحظات والاقتراحات المتداولة من المجتمع على انها تحسينات مستقبلية محتملة وسيتم النظر بها بعناية بالاضافة الى التصويت عليها من قبل NUMBERSDAO.
تم اعادة النظر في قواعد الادارة الاساسية ل NUMBERSDAO من قبل المجتمع في شهر ديسيمبر. وسوف يتم الاعلان عن التفاصيل اكثر عن اول استبيان في شهر يناير من عام 2022.
 
عن Numbers Protocol
يقوم Numbers على بناء شبكة من الصور اللامركزية لاقامة المجتمعية والفائدة والثقة في وسائل الاعلام الرقمي. يعيد Numbers Protocol تحديد طبيعة وسائل الاعلام المرئية كاصول وعامود فقري لمجموعة من ادوات التسجيل واسترجاع الصور والفيديوهات في شبكة Numbers والتي تشمل Capture App, Seal API و Trace website بالاضافة الى سوق CaptureClub و الملكية NFT محرك البحث. ان Numbers يدعم ويؤيد بوجود قيم النزاهة في وسائل الاعلام الرقمي ويمكِن الناس على  التفكير بشكل أدق نحو التفاعلات الحاصلة بين صورتنا وبين العالم من حولنا.

**Comment by sofiayan0523** [comment]
@Cryptoguy86 the translation is approved and pushed to the main article with your name, please check here: https://hackmd.io/hkxEHYdOS6K3BV63wCKTyg?view#Arabic

Thank you for your contribution, please [fill out the form](https://airtable.com/shrHsGWu0uN1r2sYj) to claim the reward :)
