### ISSUE TITLE
[Translation demand - Viet Nam] Numbers Protocol Asset & Deflationary Token Economy

### ISSUE THREAD

**Issue by nnnanji** [numbersprotocol/community-support#53]
Mạng ảnh phi tập trung Numbers

Numbers đang xây dựng một mạng lưới ảnh phi tập trung nhằm mục đích tạo ra cộng đồng, giá trị và niềm tin trong các phương tiện kỹ thuật số. Giao thức Numbers xác định lại phương tiện trực quan kỹ thuật số là tài sản và là xương sống của bộ công cụ để đăng ký và truy xuất hình ảnh và video trong mạng Numbers. Bao gồm các:

- Capture App: Máy ảnh blockchain đầu tiên trên thế giới. Người dùng có thể sử dụng nó để chụp ảnh, đăng ký hình ảnh và sử dụng hình ảnh đó trên các ứng dụng Web 3.0
- Seal API: Công cụ dành cho nhà phát triển để niêm phong và truy xuất ảnh trong mạng.
- Giấy chứng nhận: Giấy chứng nhận xác thực nội dung với xuất xứ trên chuỗi.
- CaptureClub: Native NFT marketplace cho ảnh được tạo thông qua Numbers Protocol. Người dùng có thể chọn liệt kê NFT của họ tại đây hoặc các thị trường khác trong hệ sinh thái.
- NFT search engine: Công cụ tìm kiếm Web 3.0 NFT đầu tiên giúp người dùng tìm thấy lịch sử NFT được liên kết với nội dung ảnh và giúp NFT marketplaces thực hiện phát hiện trộm cắp.

Numbers bảo vệ sự thuần khiết của phương tiện kỹ thuật số và cho phép mọi người suy nghĩ chín chắn hơn về sự tương tác giữa hình ảnh của chúng ta và thế giới xung quanh. Mục tiêu của Numbers là mã hóa những bức ảnh mang tính xác thực (bao gồm cả hình ảnh và video) để tạo ra một mạng lưới ảnh phi tập trung trong Web 3.0. Để thực hiện đầy đủ mục tiêu này, chúng tôi đang giới thiệu Deflationary Token & Asset Economy (nền kinh tế tài sản & mã thông báo giảm phát)- một hệ thống được thực hiện hàng quý để xác định phí dịch vụ và tính toán số lượng mã thông báo được mua lại và đốt.

**Comment by sofiayan0523** [comment]
Hi @nnnanji  thank you for submitting the Viet Nam translation, but for the ambassador translation task, the demand should be opened by the team. 

Still thank you for the work, since you get over 3 likes, we will use this paragraph on the main article, and give you the paragraph reward, please [fill out the form](https://airtable.com/shrHsGWu0uN1r2sYj) to claim the reward :)

**Comment by nnnanji** [comment]
Thank you so much :)
