### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by rezahastam** [numbersprotocol/community-support#61]
I have some suggestions for capture app if you accept:

1. it would be better if we can search other's username and open their profile and see their NFTs from their page (like "instagram") and then message them for price and then they put it on the market or sell directly to that person.

2. use more languages in settings.

3. categorize NFTs at the first place by user: like nature, buildings, animals, Technology, ....

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248802389449) by [Unito](https://www.unito.io)

**Comment by ethanwu155** [comment]
Hi. Thank you for taking the team to submit a Feature Request. We are pleased to inform you that we have addressed your requests already!

1) Capture Cam asset page now displays the creator name. This creator name can be clicked and can display user profile. User Profile displays full list of listed products as well as collected products. You can follow and unfollow as well.

2) Our products current support English and Chinese settings. If there are any other languages that you wish to be supported let us know.

3) Capture Cam and Dashboard both can add tags and items can be filtered in via tags. 

Appreciate your patience and continued support. If you have any other issues or request feel free to let us know. Thanks!
