### ISSUE TITLE
[Translation demand - Hindi] Numbers Protocol Asset & Deflationary Token Economy

### ISSUE THREAD

**Issue by sofiayan0523** [numbersprotocol/community-support#63]
Looking for Hindi translators to translate [Numbers Protocol Asset & Deflationary Token Economy](https://medium.com/numbers-protocol/numbers-protocol-asset-deflationary-token-economy-aeb0336e3711)
Leave your translation in this issue comment to become our Tier 1 Ambassador!
--
- How to participate
> - Translate at least one paragraph of the selected article.
> - The translation should be done as the Github issue comment.
> - Share the link of the comment in the local community and get at least 3 likes on Github.
> - If there are two comments linked to the same paragraph and both collect 3 likes, the earlier one wins.
> - The translation needs to be fluent and factually correct and should not be copied directly from Google translate or similar apps (any attempt to copy-paste directly from Google Translate will result in your dismissal from the Ambassador Program).
- Rewards
> - 10 NUM per paragraph per language

**Comment by Enjoybro** [comment]
Numbers Decentralized फोटो नेटवर्क :-
Numbers एक ऐसा Decentralized फोटो नेटवर्क बना रहे है, जो सभी लोगों को डिजिटल मीडिया के प्रति आकर्षित करेगा  तथा उन्हे डिजिटल मीडिया के महत्व  को समझने मे मदद करेगा ,तथा डिजिटल मीडिया के प्रति लोगो के विश्वास मजबूत करेगा।
Numbers Protocol डिजिटल विजुअल मीडिया (फोटो और वीडियो) को हमारे सामने एक Asset के रूप मे पेश करता है, जिसे हम खरीद और बेच सकते है। 
Numbers Protocol हमारे द्वारा ली गई  तस्वीरो और वीडियो को रजिस्टर करने और उन्हें पुनः प्राप्त करने के लिए  कुछ उपयुक्त app और उपकरण पेश करता है जो निम्न है :- 
1) Capture App :- यह दुनिया का पहला ऐसा Web 3.0 app तथा ब्लॉकचैन कैमरा है जो Users के द्वारा ली गयी तस्वीरो और वीडियो को  ब्लॉकचैन पर सहजता से रजिस्टर करता है, इसे उपयोग करना बिल्कुल आसान है।
2) Seal API :- Seal API number का उपयोग करके फोटोग्राफर तथा निवेशक अपने द्वारा खींची गई फोटो को ब्लॉकचैन पर रजिस्टर करके  उसे अपने WEB3.0 के address से जोड़ सकते है, तथा इसका प्रमाणपत्र प्राप्त कर सकते है।

3) प्रमाण पत्र (Certificate) :- आपके द्वारा ली गई फोटो के ब्लॉकचैन पर होने का प्रमाण पत्र इस प्रमाण पत्र मे इस फोटो की संपूर्ण जानकारी और फोटो लेने वाले की जनकारी होती है।।

4) CaptureClub Marketplace :- यहा पर हमारे द्वारा ली गई तस्वीरो के NFT रूपांतरण को बेचा तथा दुसरे के द्वारा ली गयी तस्वीर के NFT रूपांतरण को खरीदा जाता है।

5) NFT Search Engine :- यह Web 3.0 का पहला Search Engine है, जिसकी सहायता से हम NFT खरीदने से पहले उसकी संपूर्ण जानकारी लेकर अपने साथ होने वाली धोखाधड़ी से बच सकते है।

**Comment by sofiayan0523** [comment]
@Enjoybro the translation is approved and pushed to the main article with your name, please check here: https://hackmd.io/hkxEHYdOS6K3BV63wCKTyg?both#Hindi

Thank you for your contribution, please [fill out the form](https://airtable.com/shrHsGWu0uN1r2sYj) to claim the reward :)

**Comment by sofiayan0523** [comment]
The Hindi translation still has some paragraphs missing! Looking for ambassador to finish it!

**Comment by Enjoybro** [comment]
Numbers एक ऐसा उच्च कोटि का डिजिटल मीडिया प्लेटफॉर्म है जो हमे और हमारे आस पास के वातावरण , रहन सहन और वेशभूषा की जानकारी विश्व के सभी लोगो को हमारे द्वारा ली गई तस्वीरो के माध्यम से देता है, और उन्हे हमारे बारे मे जानने की उत्सुकता को बढ़ावा देता है। 
Number प्लेटफॉर्म का लक्ष्य WEB 3.0 मे एक Decentralized फोटो नेटवर्क को बनाना है, इसके लिए number हमारे द्वारा ली गई तस्वीरो को NFT या टोकन मे बदलते है । 
इस लक्ष्य को पूर्ण करने के लिए, Numbers एक टोकन और Asset Econommy को पेश करते है जो हमे हमारे द्वारा ली गयी तस्वीरो को  बेचने मे और  दुसरो के द्वारा ली गई तस्वीरो को खरीदने मे हमारी मदद करता है, टोकन की संख्या को कम करने के लिए इसमे से कुछ टोकन हर तीसरे महीने burn कर दिये जाते है।।

Web 3.0 Asset Economy :- 

किसी भी Asset (फोटो या विडियो) को web 2.0 से web 3.0 मे बदलने पर उसमे कुछ मूलभूत परिवर्तन भी आते है, जैसे - Asset (फोटो या वीडियो) के दिखने का तरीका  तथा फोटो सर्विस के operate होने का तरीका। 
Web 3.0 मे सभी Asset (फोटो या वीडियो) किसी व्यक्ति विशेष के नाम पर पंजीकृत होते है  तथा अपने स्वामित्व का संपूर्ण एवं स्पष्ट रिकॉर्ड रखते हैं।

यही अंतर Asset की वैल्यू को दर्शाता है तथा इसे एक Asset Economy के रूप मे प्रदर्शित करता है, तथा यह फोटोग्राफरों के लिए web 3.0 मे फोटोग्राफी के लिए नये दरवाजे खोलता है तथा इसके लिए उन्हे प्रेरित करता है। 
हमने इसके लिये पहले से ही कुछ टूल्स बना रखे है जो उपयोगकर्ता को web 3.0 मे अपने Asset (फोटो या विडियो)को रजिस्टर करने मे मदद करते है,
हमारे Numbers Protocol का एक टोकन $Num है जो Numbers Photo Network को Asset Economy बनाने मे मदद करता हैं।
Q1 2022 के लिए नेटवर्क शुल्क को नीचे दी गई sheet मे स्पष्ट रूप से देखा जा सकता है 
उपयोगकर्ता के लाभ तथा $num के मुल्य को ध्यान मे रखते हुए नेटवर्क शुल्क को प्रत्येक तिमाही मे समायोजित जायेगा ।


डेवलपर्स और उद्यम (फोटोग्राफी संस्था) भी अपने फोटो और  वीडियो को रजिस्टर करने , उसके ब्लॉकचैन पर होने  के स्रोत ,प्रमाण पत्र प्राप्त करने तथा उसे अपने Web 3.0 के ब्लॉकचैन पते पर जोड़ने आदि , के लिए numbers service (Seal API ) का उपयोग कर सकते है।
अन्य उपयोगकर्ता के ही समान, API उपयोगकर्ता के लिए भी प्रत्येक तिमाही फीस को समायोजित किया जायेगा जिससेे शुल्क की स्थिरता बनी रहे।
डेवलपर्स और उद्यम (फोटोग्राफी संस्था) भी अपने फोटो और  वीडियो को रजिस्टर करने , उसके ब्लॉकचैन पर होने  के स्रोत ,प्रमाण पत्र प्राप्त करने तथा उसे अपने Web 3.0 के ब्लॉकचैन पते पर जोड़ने आदि , के लिए numbers service (Seal API ) का उपयोग कर सकते है।
अन्य उपयोगकर्ता के ही समान, API उपयोगकर्ता के लिए भी प्रत्येक तिमाही फीस को समायोजित किया जायेगा जिससेे शुल्क मे स्थिरता बनी रहे।

**Comment by dsbanna13** [comment]
Ecosystem ऐप्स 

वेब 2.0 की सर्विस में जैसे इंस्टाग्राम एवं अन्य सोशल मीडिया प्लेटफार्म पर अपलोड किए गए फोटो की उत्पत्ति , निर्माणकर्ता के हस्ताक्षर, स्थानांतरण इतिहास व प्रोडक्ट के असली मालिक का पता लगाना मुश्किल ही नहीं, ना मुमकिन होता था ।
 लेकिन अब numbers decentralized वेब 3.0 की मदद से   फोटो का रिकॉर्ड रखना अब बहुत आसान हो गया है।

Numbers नेटवर्क ऑरिजनल सामग्री को blockchain प्रोटोकाल के रूप में, Numbers प्रोटोकॉल ओरिजिनल प्रोडक्ट की शुद्धता और पता लगाने के लिए वेब 3.0 की लेटेस्ट तकनीक का उपयोग करता है।
एक बार सामग्री की authenticity सिद्ध हो जाने के बाद, यह थर्ड-पार्टी इनोवेटिव फोटो सर्विस प्रदान करने का रास्ता खोल देती है , ताकि यूजर्स अपने फोटो को वेब3.0 पर अपलोड करके रजिस्ट्रेशन व मोनेटाइजेशन करके इनकम जनरेट कर सके।

हम इन थर्ड-पार्टी सर्विस को इकोसिस्टम (ecosystem apps)  ऐप कहते हैं जिनमे एनएफटी, मार्केटप्लेस, वेब3.0 स्टोरेज, सोशल मीडिया प्लेटफार्म, और स्टॉक फोटो/वीडियो सेवा शामिल है ।( लेकिन ये सर्विस इन्हीं तक सीमित नहीं है )
Ecosystem apps के नेटवर्क  को  दीर्घकालीन समय तक चलाने के लिऐ हम कुल पेमेंट का 0.5% हम फीस के रूप में चार्ज करेंगे। यदि इकोसिस्टम एप्स फ्री-टू-यूज है तब भी एक बेस पेमेंट उन यूजर्स से लिया जाएगा जो  numbers प्रोटोकॉल में  इकोसिस्टम एप्स का उपयोग करेंगे।

पिछले 2 महीनो में घोषित हमारी पार्टनरशिप की जानकारी यहां दी गई है जिन्होंने  numbers प्रोटोकॉल को अपनाया है । यही हमारी उन्नति को रिप्रेजेंट करती है।

**Comment by dsbanna13** [comment]
NUMBERS प्रोटोकॉल के बारे में

Numbers एक ऐसा Decentralized फोटो नेटवर्क बना रहे है, जो सभी लोगों को डिजिटल मीडिया के प्रति आकर्षित करेगा तथा उन्हे डिजिटल मीडिया के महत्व को समझने मे मदद करेगा ,तथा डिजिटल मीडिया के प्रति लोगो के विश्वास मजबूत करेगा।
Numbers Protocol डिजिटल विजुअल मीडिया (फोटो और वीडियो) को हमारे सामने एक Asset के रूप मे पेश करता है, जिसे हम खरीद और बेच सकते है।
The capture app, SEAL API, तथा ट्रेस वेबसाइट + the CaptureClub Marketplace एवं 
Proprietary एनएफटी सर्च इंजन 
NUMBERS डिजिटल मीडिया की शुद्धता की हिमायत करते हैं
और लोगो को हमारी इमेज एवं आसपास की दुनिया के बीच बातचीत के बारे में अधिक गंभीर होकर सोचने में सक्षम बनाते है।

[वेबसाइट](https://numbersprotocol.io/) ।  [ट्वीटर](https://twitter.com/numbersprotocol?t=Zni0ZPb3SRmNk22hwaMCqA&s=09) । [टेलीग्राम](https://t.me/numbersprotocol) । [डिसकार्ड](https://link.numbersprotocol.io/discord) । [मिडियम](https://medium.com/numbers-protocol)  ।

**Comment by sofiayan0523** [comment]
@Enjoybro  the second paragraph translation is approved and pushed to the main article with your name, please check here: https://hackmd.io/hkxEHYdOS6K3BV63wCKTyg?both#Hindi

Thank you for your contribution, please [fill out the form](https://airtable.com/shrHsGWu0uN1r2sYj) to claim the reward :)

**Comment by sofiayan0523** [comment]
@dsbanna13  your translation is approved and pushed to the main article with your name, please check here: https://hackmd.io/hkxEHYdOS6K3BV63wCKTyg?both#Hindi

Thank you for your contribution, please [fill out the form](https://airtable.com/shrHsGWu0uN1r2sYj) to claim the reward :)
