### ISSUE TITLE
[Translation demand - French] CAPTCH-A Staking Program Goes Live! Hold $NUM and Acquire Your Robi Pal Now!

### ISSUE THREAD

**Issue by sofiayan0523** [numbersprotocol/community-support#69]
Looking for French translators to translate [<CAPTCH-A Staking Program Goes Live! Hold $NUM and Acquire Your Robi Pal Now!>](https://medium.com/numbers-protocol/captch-a-staking-program-goes-live-hold-num-and-acquire-your-robi-pal-now-48c60d8690b8)

Leave your translation in this issue comment to become our Tier 1 Ambassador!

--
- How to participate
> - Translate **at least one paragraph of the selected article**.
> - **The translation should be done as the Github issue comment.**
> - **Share the link of the comment in the local community and get at least 3 likes on Github**.
> - If there are two comments linked to the same paragraph and both collect 3 likes, the earlier one wins.
> - The translation needs to be fluent and factually correct and should not be copied directly from Google translate or similar apps (any attempt to copy-paste directly from Google Translate will result in your dismissal from the Ambassador Program).

- Rewards
> - `10 NUM` per paragraph per language
> - Bounty-based, the selected article will be announced when it gets 3 likes.

**Comment by Frenchland42580** [comment]
hi sofiayan,

just wondering if you were looking for a french translator that you can trust and who loves number protocol. i have done all three translation so far. 2 have been approved and i'm sure this one will be too. it is my job here in France to translate english into french and vice versa. don't hesitate to contact me if you need more. i love the NUM reward. i'm staking it for the long run. cheers

**Comment by sofiayan0523** [comment]
@Frenchland42580  will you consider submitting our Tier 2 ambassador?
We have **Position C: Designated Article Translator** open for submission, it will be a monthly based position, and be our official designated translator :)

Check out the duty and reward here ↓
https://github.com/numbersprotocol/community-support/wiki/14.-Ambassador-and-Social-Bounty-Programs#position-c-designated-article-translator-maximum-1-per-language

**Comment by Frenchland42580** [comment]
hi @sofiayan0523

this is exactly what i would like to do. how can I do it? what are the steps I need to do. I have an account on MEDIUM so I would be glad and honored to be part of the TIER2 ambassador program. let me now.
jlehv

**Comment by sofiayan0523** [comment]
@Frenchland42580  Fill out the application:  https://link.numbersprotocol.io/Am2
Once pass the review, you will officially co-work with the team :)

**Comment by Frenchland42580** [comment]
hello sofiayan, I was just wondering if you received my application? how long does it usually take to pass the review? thx for everything. jlehv

**Comment by sofiayan0523** [comment]
@Frenchland42580  the translation is approved and pushed to the main article with your name, please check here: https://hackmd.io/8w9-ZTm7R7CLkhtmkRuqxg#French

Thank you for your contribution, please [fill out the form](https://airtable.com/shrHsGWu0uN1r2sYj) to claim the reward :)

And welcome to become our designated French translator!
