### ISSUE TITLE
Automating 3rd party verification of my images?

### ISSUE THREAD

**Issue by Nassan12** [numbersprotocol/community-support#7]
I'm trying to understand how this technology would be used by a third party. For instance, let's say I mint an NFT of a digital asset, but then someone else copies my image and mints an NFT after my own. How easily could a third party arbiter verify the authenticity of my image?

A huge part of your tech is that it gives an accurate picture of the history of an image, so, ostensibly, if the fraud were to mint a copy of my image (maybe altered slightly) the third party could just review the time that each was minted and verify mine.

However, could this process be automated? i.e. could the 3rd party verify authenticity immediately via some sort of API that could connect them to the history of my image and the copy?

**Select label**
NFT Search Engine

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248723052590) by [Unito](https://www.unito.io)

**Comment by tammyyang** [comment]
There are CAI injection and on-chain provenance for the 3rd-party service to use. This article explains the basic function of how it works, hope this explains https://medium.com/numbers-protocol/how-to-claim-copyright-with-numbers-protocol-c114e497f574

If there is more questions/discussions, please feel free to continue the conversation here!

**Comment by kennyhungQA** [comment]
This issue is no longer to be used, close it.
Currently, our NFT Search Engine is pivoting to a verification site.
