### ISSUE TITLE
[Translation demand - Hindi] CAPTCH-A Staking Program Goes Live! Hold $NUM and Acquire Your Robi Pal Now!

### ISSUE THREAD

**Issue by sofiayan0523** [numbersprotocol/community-support#71]
Looking for Hindi translators to translate [<CAPTCH-A Staking Program Goes Live! Hold $NUM and Acquire Your Robi Pal Now!>](https://medium.com/numbers-protocol/captch-a-staking-program-goes-live-hold-num-and-acquire-your-robi-pal-now-48c60d8690b8)

Leave your translation in this issue comment to become our Tier 1 Ambassador!

--
- How to participate
> - Translate **at least one paragraph of the selected article**.
> - **The translation should be done as the Github issue comment.**
> - **Share the link of the comment in the local community and get at least 3 likes on Github**.
> - If there are two comments linked to the same paragraph and both collect 3 likes, the earlier one wins.
> - The translation needs to be fluent and factually correct and should not be copied directly from Google translate or similar apps (any attempt to copy-paste directly from Google Translate will result in your dismissal from the Ambassador Program).

- Rewards
> - `10 NUM` per paragraph per language
> - Bounty-based, the selected article will be announced when it gets 3 likes.

**Comment by dsbanna13** [comment]
**Empower CAPTCH-A NFT:** staking प्रोग्राम
पिछले 2महीनो में NUMBERS टीम ने बहुत सारे staking प्रोग्राम लांच किए है। हमे ये बताते हुए बहुत खुशी हो रही है कि हम एक नया staking प्रोग्राम CAPTCH-A staking प्रोग्राम को लॉन्च कर रहे है, **यह प्रोगाम बिलकुल नया है,** जो NUM होल्डर को सामान्य कमाई के अतिरिक्त विशेष  community privileges प्रदान करेगा।
जानिए क्यों  CAPTCH-A staking प्रोग्राम आपके लिऐ बेहतर साबित हो सकता है?
NUMBERS कम्युनिटी में NUM टोकन [Utility, staking and governance] < (https://github.com/numbersprotocol/community-support/wiki/07.-NUM-Token#utility-staking-and-governance) > के तहत सारे महत्वपूर्ण चरण 4/phase4 [governance vote] बिना CAPTCH-A वाले के लिऐ लॉक रहेगा। इसका मतलब जिसके पास CAPTCH-A NFT है तथा  गवर्नेंस वोटिंग अवधि के लिए NUM टोकन hold रखेगे उनको phase4 में (**वास्तविक वोट**)  गवर्नेंस वोटिंग में भाग ले सकते हैं तथा NUMBERS नेटवर्क को सही दिशा में ले जाने में मदद कर सकते है।
NUMBERS नेटवर्क के गवर्नेस के बारे में अधिक जानकारी के लिए Numbers कम्युनिटी wiki में [आधिकारिक दस्तावेज] <(https://github.com/numbersprotocol/community-support/wiki/07.-NUM-Token#utility-staking-and-governance) > देखे। नीचे Numbers गवर्नेंस में CAPTCH-A व Staking play की भूमिका के बारे में संक्षेप में दी गई हैं:
CAPTCH-A प्राप्त करने के लिए आपकों 2000 $NUM टोकन कम से कम 14 दिन के लिए होल्ड करने पढ़ेंगे।

- CAPTCH-A: Numbers प्रोटोकॉल नेटवर्क के साथ आधिकारिक मेंबरशिप
- Staking करके CAPTCH-A को सक्रिय करे: विशिष्ट गवर्नेंस टिकिट प्राप्त करने के लिए , आप सक्रिय मेंबर हो , यह प्रदर्शित करना ।
- तो आप CAPTCH-A केसे हासिल कर सकते हो ?
1. नवंबर 2020 की शुरुआत में हुए प्री-लिस्टिंग प्रोगाम के माध्यम से(नोट: CAPTCH-A के उस इवेंट को NUMBERS नेटवर्क मे से  burn कर दिया गया, अब आपको इसे दूसरे तरीकों से फिर से  करना पड़ेगा।)
2. **CAPTCH-A के Staking प्रोग्राम** के माध्यम से।
3. CAPTCH-A को प्राप्त करने के लिए $Num टोकन burn करे( इसके बारे में जानकारी बाद में दी जाएगी)
4.

**Comment by dsbanna13** [comment]
Empower CAPTCH-A NFT: staking प्रोग्राम
पिछले 2महीनो में NUMBERS टीम ने बहुत सारे staking प्रोग्राम लांच किए है। हमे ये बताते हुए बहुत खुशी हो रही है कि हम एक नया staking प्रोग्राम CAPTCH-A staking प्रोग्राम को लॉन्च कर रहे है, यह प्रोगाम बिलकुल नया है, जो NUM होल्डर को सामान्य कमाई के अतिरिक्त विशेष community privileges प्रदान करेगा।
जानिए क्यों CAPTCH-A staking प्रोग्राम आपके लिऐ बेहतर साबित हो सकता है?
NUMBERS कम्युनिटी में NUM टोकन [Utility, staking and governance] < (https://github.com/numbersprotocol/community-support/wiki/07.-NUM-Token#utility-staking-and-governance) > के तहत सारे महत्वपूर्ण चरण 4/phase4 [governance vote] बिना CAPTCH-A वाले के लिऐ लॉक रहेगा। इसका मतलब जिसके पास CAPTCH-A NFT है तथा गवर्नेंस वोटिंग अवधि के लिए NUM टोकन hold रखेगे उनको phase4 में (वास्तविक वोट) गवर्नेंस वोटिंग में भाग ले सकते हैं तथा NUMBERS नेटवर्क को सही दिशा में ले जाने में मदद कर सकते है।
NUMBERS नेटवर्क के गवर्नेस के बारे में अधिक जानकारी के लिए Numbers कम्युनिटी wiki में [आधिकारिक दस्तावेज] <(https://github.com/numbersprotocol/community-support/wiki/07.-NUM-Token#utility-staking-and-governance) > देखे। नीचे Numbers गवर्नेंस में CAPTCH-A व Staking play की भूमिका के बारे में संक्षेप में दी गई हैं:
CAPTCH-A प्राप्त करने के लिए आपकों 2000 $NUM टोकन कम से कम 14 दिन के लिए होल्ड करने पढ़ेंगे।

CAPTCH-A: Numbers प्रोटोकॉल नेटवर्क के साथ आधिकारिक मेंबरशिप
Staking करके CAPTCH-A को सक्रिय करे: विशिष्ट गवर्नेंस टिकिट प्राप्त करने के लिए , आप सक्रिय मेंबर हो , यह प्रदर्शित करना ।
तो आप CAPTCH-A केसे हासिल कर सकते हो ?
नवंबर 2020 की शुरुआत में हुए प्री-लिस्टिंग प्रोगाम के माध्यम से(नोट: CAPTCH-A के उस इवेंट को NUMBERS नेटवर्क मे से burn कर दिया गया, अब आपको इसे दूसरे तरीकों से फिर से करना पड़ेगा।)
CAPTCH-A के Staking प्रोग्राम के माध्यम से।
CAPTCH-A को प्राप्त करने के लिए $Num टोकन burn करे( इसके बारे में जानकारी बाद में दी जाएगी

**Comment by dsbanna13** [comment]
**White CAPTCH-A released !**

**White CAPTCH-A केसे प्राप्त करे?**
1. [फॉर्म](https://airtable.com/shrfv7P7q5aY61Wri) भरे।
2. 14 फरवरी 2022 को 13:00UTC से पहले अपने Non Custodial वॉलेट में कम से कम 2000 $NUM टोकन deposit करे।
3. NUM को 30 दिन तक उसी वॉलेट में hold रखे । (12:59utc 15 मार्च 2022तक)
4. ताला! अपने White CAPTCH-A को क्लेम करे व अपने फर्स्ट गवर्नेस में वोट करें।

**Comment by dsbanna13** [comment]
**यदि आप पहले से gray CAPTCH-A होल्डर है, तो आपके पास CAPTCH-A अपग्रेड करने के लिए 2 विकल्प हैं**
1. 3D grey CAPTCH-A में अपग्रेड करे,  [फॉर्म](https://airtable.com/shrCItDFZIrdWnYPm) भरे और एक  नया 3D CAPTCH-A निशुल्क प्राप्त करें।

2. व्हाइट CAPTCH-A में अपग्रेड करें और विशेष ऑफर में गवर्नेंस वोटिंग विशेषाधिकार प्राप्त करें।
- [फॉर्म](https://airtable.com/shrCItDFZIrdWnYPm) भरे।
- कम से कम 1600 $NUM टोकन   (20% off for early holder) अपने Non Custodial वॉलेट में (13:00UTC 14फरवरी2022 से पहले) stake करे।
 - ताला! अपना White CAPTCH-A क्लेम करे और first गवर्नेस मीटिंग में वोट करे।

**Comment by sofiayan0523** [comment]
@dsbanna13 the translation is approved and pushed to the main article with your name, please check here: https://hackmd.io/8w9-ZTm7R7CLkhtmkRuqxg#Hindi

Thank you for your contribution, please [fill out the form](https://airtable.com/shrHsGWu0uN1r2sYj) to claim the reward :)
