### ISSUE TITLE
[Translation demand - Portuguese] CAPTCH-A Staking Program Goes Live! Hold $NUM and Acquire Your Robi Pal Now!

### ISSUE THREAD

**Issue by sofiayan0523** [numbersprotocol/community-support#78]
Looking for Portuguese translators to translate [<CAPTCH-A Staking Program Goes Live! Hold $NUM and Acquire Your Robi Pal Now!>](https://medium.com/numbers-protocol/captch-a-staking-program-goes-live-hold-num-and-acquire-your-robi-pal-now-48c60d8690b8)

Leave your translation in this issue comment to become our Tier 1 Ambassador!

--
- How to participate
> - Translate **at least one paragraph of the selected article**.
> - **The translation should be done as the Github issue comment.**
> - **Share the link of the comment in the local community and get at least 3 likes on Github**.
> - If there are two comments linked to the same paragraph and both collect 3 likes, the earlier one wins.
> - The translation needs to be fluent and factually correct and should not be copied directly from Google translate or similar apps (any attempt to copy-paste directly from Google Translate will result in your dismissal from the Ambassador Program).

- Rewards
> - `10 NUM` per paragraph per language
> - Bounty-based, the selected article will be announced when it gets 3 likes.

**Comment by TcheloFreitas** [comment]
Over the past 2 months, the Numbers team has launched various [staking programs](https://num.numbersprotocol.io/). We are especially excited to announce our CAPTCH-A Staking Program, a whole NEW program that allows NUM holders to unlock additional community privileges on top of your normal earnings.

Portuguese

Nos últimos 2 meses, o time da _Numbers_ lançou diversos programas de _Staking_. Mas Agora nós estamos realmente animados em anunciar o nosso programa de _Staking CAPTCH-A_. Um Programa totalmente novo que permite aos proprietários de NUM desbloquearem direitos adicionais na comunidade além dos ganhos normais que eles já possuem.

**Comment by TcheloFreitas** [comment]
**NUMBERSDAO: Participate and Vote in Numbers Network’s First Governance Meeting**
Community-focused and decentralized are core values of Numbers Protocol. As a reflection of our values, we hope to create a transparent and democratic space for our community through decentralized governance. Establishing a Decentralized Autonomous Organization (DAO) is our first step to creating an open space for us to hear voices and input from our community as well as empowering DAO members with decision-making power to pursue common goals for the future of Numbers network.

Portuguese

**NUMBERSDAO: Particie e vote na primeira reunião de Governança da Numebers**

Foco na comunidade e Descentralização são os principais valores da _Numbers Protocol_. E para fazer jus aos nossos valores, nós esperamos criar um espação transparente e democrático para a nossa comunidade através da Governança Decentralizada.

Criar uma _DAO_(Organização Autônoma Decentralizada) é o primeiro passo para cirar um espaço aberto para nós ouvir os desejos  da nossa comunidade, como tambem capacitar os Membros DAO com poder de tomada de decisão para buscar os objetivos comuns para o futuro da Rede _Numbers_.

**Comment by sofiayan0523** [comment]
@TcheloFreitas  your first paragraph translation is approved, but since only a partial paragraph has been translated, not enough contents are available for us to publish it. Encourage you to ask the Portuguese community's help to vote to your rest paragraph and helping us to finish the publication.

Thank you for your contribution, please [fill out the form](https://airtable.com/shrHsGWu0uN1r2sYj) to claim the reward :)
