### ISSUE TITLE
[Translation demand - Dutch] CAPTCH-A Staking Program Goes Live! Hold $NUM and Acquire Your Robi Pal Now!

### ISSUE THREAD

**Issue by sofiayan0523** [numbersprotocol/community-support#79]
Looking for Dutch translators to translate [<CAPTCH-A Staking Program Goes Live! Hold $NUM and Acquire Your Robi Pal Now!>](https://medium.com/numbers-protocol/captch-a-staking-program-goes-live-hold-num-and-acquire-your-robi-pal-now-48c60d8690b8)

Leave your translation in this issue comment to become our Tier 1 Ambassador!

--
- How to participate
> - Translate **at least one paragraph of the selected article**.
> - **The translation should be done as the Github issue comment.**
> - **Share the link of the comment in the local community and get at least 3 likes on Github**.
> - If there are two comments linked to the same paragraph and both collect 3 likes, the earlier one wins.
> - The translation needs to be fluent and factually correct and should not be copied directly from Google translate or similar apps (any attempt to copy-paste directly from Google Translate will result in your dismissal from the Ambassador Program).

- Rewards
> - `10 NUM` per paragraph per language
> - Bounty-based, the selected article will be announced when it gets 3 likes.

**Comment by lennartvanEeden** [comment]
CAPTCH-A Staking programma gaat live! Hou $NUM vast en verkrijg nu uw Robi Pal!

Verwerf uw witte CAPTCH-A en kwalificeer u om te stemmen in de eerste NUMBERSDAO bestuursvergadering.

CAPTCH-A NFT werd voor het eerst geïntroduceerd in november 2021 als een verzameling van robots die dienen als een poort naar verhalen en expressie. CAPTCH-A is dynamisch van aard en verandert naargelang de Capture-foto's die ze tonen. Dit betekent dat een enkele avatar een veelheid aan opwindende unieke expressievormen kan produceren.

Over CAPTCH-A: <Introducing CAPTCH-A Robis, Your Pals in the Numbers Metaverse>

CAPTCH-A NFT versterken: Stake Programma
De afgelopen 2 maanden heeft het Numbers team verschillende staking programma's gelanceerd. We zijn vooral enthousiast om ons CAPTCH-A Staking Program aan te kondigen, een geheel NIEUW programma waarmee NUM houders extra community privileges kunnen ontgrendelen bovenop je normale verdiensten.
Waarom zou u zich zorgen maken over het ontgrendelen van community privileges via CAPTCH-A Staking Program?
Onder NUM Token <Utility, Staking and Governance> in de Numbers Community Wiki, is de ALLERBELANGRIJKSTE Fase 4 [Governance Vote] vergrendeld achter staking en het bezit van een "actieve" CAPTCH-A. Dit betekent dat alleen diegenen die een CAPTCH-A NFT hebben aangeschaft en NUM tokens bezitten voor een bepaalde periode in de aanloop naar de bestuursstemming, kunnen deelnemen aan Fase 4 (de daadwerkelijke stemming) en direct invloed kunnen uitoefenen op de richting van het Numbers netwerk.
Om meer te leren over governance in het Numbers-netwerk, bekijk je de <official documentation> in de Numbers Community Wiki. Kort samengevat spelen CAPTCH-A en Staking de volgende rol in het bestuur van Numbers:
- CAPTCH-A: officieel lidmaatschap van het Numbers-protocolnetwerk
- Staking om CAPTCH-A te activeren: aantonen dat u een actief lid bent om een ticket te ontvangen voor een specifieke governance call.
Hoe komt u aan CAPTCH-A?
Via de pre-listing campagne die begin november 2020 heeft plaatsgevonden (let op: CAPTCH-A die als onderdeel van dit evenement is gebrand, bestaat niet meer in het Numbers netwerk en zal op de tweede manier opnieuw moeten worden verworven).
Via CAPTCH-A Staking Program!
Verbrand $NUM tokens om CAPTCH-A te verwerven (details worden in de nabije toekomst bekendgemaakt)
Houders van $NUM kunnen 2.000 $NUM aanhouden voor een periode van minstens 14 dagen om een CAPTCH-A te verwerven. Degenen die besloten hebben om in het begin langere periodes aan te houden, kunnen geavanceerde CAPTCH-A verwerven om visueel de loyaliteit van het netwerk weer te geven. ZWARTE en WITTE vormen van CAPTCH-A verhogen het stemvermogen van houders in de bestuursvergaderingen.
Zie de volgende grafiek voor CAPTCH-A staking uitsplitsing:

Grijze CAPTCH-A: Officieel lid van het Nummers Netwerk, kan deelnemen aan het bestuur als CAPTCH-A geactiveerd is.

Witte CAPTCH-A: Bestuursgewicht: 2, Voorwaarden: Moet voortdurend inzetten om WIT te blijven. Als u op enig moment niet inzet zal het degraderen naar Grijze CAPTCH-A.

Zwarte CAPTCH-A: Bestuursgewicht: 3, Voorwaarden: U moet voortdurend inzetten om de ZWARTE vorm te behouden. Als het op enig moment niet wordt ingezet zal het degraderen naar Grijze CAPTCH-A.

Witte CAPTCH-A vrijgegeven!
Hoe verkrijgt u WHITE CAPTCH-A?
Vul het formulier in
Stort minstens 2.000 $NUM in uw non-custodial vóór 13:00 UTC, 14 feb, 2022
Houd de NUM 30 dagen in dezelfde portemonnee (tot 12:59 UTC, 15 maart, 2022)
Tala! Claim uw witte CAPTCH-A en stem in onze eerste bestuursvergadering!
Als u al een grijze CAPTCH-A houder bent, zijn er 2 opties voor u om uw CAPTCH-A te upgraden.
Upgrade naar 3D Grijze CAPTCH-A
- Vul het formulier in en ontvang gratis een nieuwe 3D Grijze CAPTCH-A
Upgrade naar WHITE CAPTCH-A en krijg het bestuur stemrecht in speciale aanbieding
- Vul het formulier in
- Stake minstens 1.600 NUM (20% korting, speciale aanbieding voor vroege houder) in uw non-custodial voor 13:00 UTC, 14 feb, 2022
- Houd de NUM 30 dagen in dezelfde portefeuille (tot 12:59 UTC, 15 maart, 2022)
- Tala! Claim uw witte CAPTCH-A en stem in onze eerste bestuursvergadering!

NUMBERSDAO: Neem deel aan en stem op de eerste bestuursvergadering van Numbers Network
Gemeenschapsgericht en gedecentraliseerd zijn kernwaarden van het Numbers-protocol. Als een weerspiegeling van onze waarden hopen we een transparante en democratische ruimte te creëren voor onze gemeenschap door middel van gedecentraliseerd bestuur. Het oprichten van een Decentrale Autonome Organisatie (DAO) is onze eerste stap in het creëren van een open ruimte voor ons om stemmen en input van onze gemeenschap te horen en om DAO-leden beslissingsbevoegdheid te geven om gemeenschappelijke doelen na te streven voor de toekomst van Numbers network.
De EERSTE Numbers Network Governance Meeting is gepland!
Onderwerp: Eerste stemming van de gemeenschap voor de token-swap van het ecosysteem
Tijd: 25 maart, 2022
Geschiktheid:
- Deelnemen aan discussie - Communityleden die in het bezit zijn van actieve Grijze CAPTCH-A (deelnemer dient minimaal 2.000 NUM in bezit te hebben voor de bijeenkomst om CAPTCH-A te activeren)
- Deelnemen en stemmen - leden van de gemeenschap die in het bezit zijn van een actieve witte CAPTCH-A (deelnemers moeten minstens 2000 NUM bezitten voor de vergadering om CAPTCH-A te activeren)
Aanvullende informatie zal in maart bekend worden gemaakt.
Houd $NUM vast en verkrijg nu uw Robi Pal!

Over Numbers Protocol
Numbers bouwt aan een gedecentraliseerd fotonetwerk voor het creëren van gemeenschap, waarde en vertrouwen in digitale media. Het Numbers-protocol herdefinieert digitale visuele media als activa en vormt de ruggengraat van een reeks tools voor het registreren en terugvinden van afbeeldingen en video's in het Numbers-netwerk.
Deze omvatten:
* Capture app: De eerste blockchain camera ter wereld waarmee gebruikers eenvoudig foto's kunnen registreren en Web 3.0 toepassingen kunnen gebruiken.
* Seal API: Ontwikkelaars en ondernemingen kunnen Numbers API implementeren om foto's te registreren en toegang te krijgen tot hun Web3.0 adressen en certificaten.
* Certificaten: inhoud authenticiteit certificaten met on-chain herkomst
* CaptureClub marktplaats: Native NFT marktplaats waarmee fotogeneratoren hun creaties kunnen verkopen en inzetten.
* NFT Search Engine: De eerste Web 3.0 NFT zoekmachine die gebruikers helpt de geschiedenis van NFT's te verifiëren en mogelijke NFT fraude te voorkomen.
Numbers komt op voor de zuiverheid van digitale media en stelt mensen in staat kritischer na te denken over de interacties tussen onze beelden en de wereld om ons heen. Het doel van Numbers is om authentieke foto's (inclusief afbeeldingen en video's) te tokeniseren om een gedecentraliseerd fotonetwerk in Web 3.0 te creëren.
