### ISSUE TITLE
Features and technology

### ISSUE THREAD

**Issue by Poemkit** [numbersprotocol/community-support#8]
1/ You need to add more filters to the App, the purpose is to make the photos more beautiful and increase the App interaction of the users.

2/ Add social media integration.

3/ Need to refresh other interface, more thoughtful and more stylish, in general UX/UI needs to be upgraded.

4/ In addition, integrating  cameras linked to the app, for example, when I take a photo with my main camera, it immediately saves itself to the Capture App instead of opening the App to take a photo, using an additional algorithm  "Online prediction", an algorithm can make predictions in real time (like when you write in Google Translate, Google Translate translates after you write).

Thank you.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248805406648) by [Unito](https://www.unito.io)

**Comment by tammyyang** [comment]
![photo_2021-12-18_00-32-38](https://user-images.githubusercontent.com/5687908/146579077-f8745dde-9648-4218-8fa1-aa53e64e340f.jpg)

Image related to this discussion

**Comment by tammyyang** [comment]
Related discussion:

@jpmarlin
so you are exactly spot on... Numbers should provide the information that empowers user to make an educated well rounded decision. So when I took a snapshot you should find closest match including history and variations of it

@tammy_numbers
I think this is a good suggestion. Maybe search engine should return two results.

"Exact match" and "Similar result". I think we can do that

**Comment by willcoursen** [comment]
@tammyyang exactly something like this. Maybe start with 4 images for broad 2-3 for close and 1 for exact)
![image](https://user-images.githubusercontent.com/17142178/146581038-ea0910c0-840e-41bc-b3f7-07b524ec151d.png)

**Comment by kennyhungQA** [comment]
This issue is no longer to be used; close it.
Currently, our NFT Search Engine is pivoting to a verification site.
