### ISSUE TITLE
[Translation demand - German] CAPTCH-A Staking Program Goes Live! Hold $NUM and Acquire Your Robi Pal Now!

### ISSUE THREAD

**Issue by sofiayan0523** [numbersprotocol/community-support#80]
Looking for German translators to translate [<CAPTCH-A Staking Program Goes Live! Hold $NUM and Acquire Your Robi Pal Now!>](https://medium.com/numbers-protocol/captch-a-staking-program-goes-live-hold-num-and-acquire-your-robi-pal-now-48c60d8690b8)

Leave your translation in this issue comment to become our Tier 1 Ambassador!

--
- How to participate
> - Translate **at least one paragraph of the selected article**.
> - **The translation should be done as the Github issue comment.**
> - **Share the link of the comment in the local community and get at least 3 likes on Github**.
> - If there are two comments linked to the same paragraph and both collect 3 likes, the earlier one wins.
> - The translation needs to be fluent and factually correct and should not be copied directly from Google translate or similar apps (any attempt to copy-paste directly from Google Translate will result in your dismissal from the Ambassador Program).

- Rewards
> - `10 NUM` per paragraph per language
> - Bounty-based, the selected article will be announced when it gets 3 likes.

**Comment by lennartvanEeden** [comment]
CAPTCH-A Staking Programm geht live! Halten Sie $NUM und erwerben Sie jetzt Ihren Robi Pal!

Erwerben Sie Ihr weißes CAPTCH-A und qualifizieren Sie sich für die Teilnahme an der ersten NUMBERSDAO Governance-Sitzung.

CAPTCH-A NFT wurde erstmals im November 2021 als eine Sammlung von Robotern vorgestellt, die als Tor zu Geschichten und Ausdrucksmöglichkeiten dienen. CAPTCH-A ist von Natur aus dynamisch und verändert sich je nach den gezeigten Capture-Fotos. Das bedeutet, dass ein einziger Avatar eine Vielzahl von aufregenden, einzigartigen Ausdrucksformen hervorbringen kann.

Über CAPTCH-A: <Introducing CAPTCH-A Robis, Your Pals in the Numbers Metaverse>

CAPTCH-A NFT ermächtigen: Einsatzprogramm
In den letzten 2 Monaten hat das Numbers-Team verschiedene Staking-Programme gestartet. Wir freuen uns ganz besonders, unser CAPTCH-A Staking Program ankündigen zu können, ein völlig NEUES Programm, das es NUM-Inhabern ermöglicht, zusätzlich zu ihrem normalen Verdienst weitere Community-Privilegien freizuschalten.
Warum sollten Sie sich für die Freischaltung von Community-Privilegien durch das CAPTCH-A Staking Program interessieren?
Unter NUM Token <Bedienung, Einsatz und Governance> im Numbers Community Wiki ist die ALLWICHTIGE Phase 4 [Governance Vote] an den Einsatz und den Besitz eines "aktiven" CAPTCH-A gebunden. Das bedeutet, dass nur diejenigen, die ein CAPTCH-A NFT erworben haben und die NUM-Tokens für einen bestimmten Zeitraum vor der Governance-Abstimmung halten, an Phase 4 (der eigentlichen Abstimmung) teilnehmen können und ein direktes Mitspracherecht bei der Ausrichtung des Numbers-Netzwerks haben.
Um mehr über die Governance im Numbers Netzwerk zu erfahren, lesen Sie die <offizielle Dokumentation> im Numbers Community Wiki. Zusammenfassend lässt sich sagen, dass CAPTCH-A und Staking in der Numbers Governance die folgenden Rollen spielen:
- CAPTCH-A: Offizielle Mitgliedschaft im Numbers Protocol Network
- Staking zur Aktivierung von CAPTCH-A: Nachweis, dass Sie ein aktives Mitglied sind, um ein Ticket für einen bestimmten Governance Call zu erhalten.
Wie erwirbt man also CAPTCH-A?
Durch die Pre-Listing-Kampagne, die Anfang November 2020 stattfand (Hinweis: CAPTCH-A, das im Rahmen dieser Veranstaltung verbrannt wurde, existiert nicht mehr im Numbers-Netzwerk und muss auf dem zweiten Weg neu erworben werden).
Durch CAPTCH-A Staking Program!
Verbrennen Sie $NUM-Token, um CAPTCH-A zu erwerben (Details werden in der nächsten Zeit bekannt gegeben)
Inhaber von $NUM können 2.000 $NUM für einen Zeitraum von mindestens 14 Tagen halten, um ein CAPTCH-A zu erwerben. Diejenigen, die sich zu Beginn für einen längeren Zeitraum entschieden haben, können ein fortgeschrittenes CAPTCH-A erwerben, um die Loyalität zum Netzwerk visuell darzustellen. SCHWARZE und WEISSE Formen des CAPTCH-A erhöhen das Stimmrecht der Inhaber in den Governance-Meetings.
Die folgende Tabelle zeigt die Aufteilung des CAPTCH-A-Einsatzes:

Graues CAPTCH-A: Offizielles Mitglied des Numbers Network, kann an der Governance teilnehmen, wenn CAPTCH-A aktiviert ist

Weißes CAPTCH-A: Governance-Gewichtung: 2, Bedingungen: Muss kontinuierlich eingesetzt werden, um die WEISSE Form zu erhalten. Wenn der Einsatz zu irgendeinem Zeitpunkt aufgehoben wird, wird er zu Gray CAPTCH-A zurückgestuft.

Schwarzes CAPTCH-A: Governance-Gewichtung: 3, Bedingungen: Es muss kontinuierlich eingesetzt werden, um die SCHWARZE Form zu erhalten. Wird der Einsatz zu irgendeinem Zeitpunkt aufgehoben, wird es zu Gray CAPTCH-A herabgestuft.

Weißes CAPTCH-A Freigegeben!
Wie kann man WHITE CAPTCH-A erwerben?
Füllen Sie das Formular aus
Zahlen Sie mindestens 2.000 $NUM vor 13:00 UTC, Feb 14, 2022, in Ihre nicht-pfändbare Geldbörse ein.
Halten Sie die NUM in der gleichen Brieftasche für 30 Tage (bis 12:59 UTC, 15. März 2022)
Tala! Beanspruche dein weißes CAPTCH-A und stimme in unserer ersten Regierungssitzung ab!
Wenn Sie bereits ein Gray CAPTCH-A besitzen, haben Sie 2 Möglichkeiten, Ihr CAPTCH-A zu aktualisieren.
Upgrade auf 3D Gray CAPTCH-A
- Füllen Sie das Formular aus und erhalten Sie kostenlos ein neues 3D Gray CAPTCH-A
Upgrade auf WHITE CAPTCH-A und Sie erhalten das Governance-Voting-Privileg im Sonderangebot
- Füllen Sie das Formular aus
- Setze mindestens 1.600 NUM (20 % Rabatt, Sonderangebot für frühe Inhaber) in deinem nicht-vertraulichen Wallet vor 13:00 UTC, 14. Februar 2022
- Behalten Sie die NUM für 30 Tage in der gleichen Geldbörse (bis 12:59 UTC, 15. März 2022)
- Tala! Beanspruche dein weißes CAPTCH-A und stimme in unserer ersten Regierungssitzung ab!

NUMBERSDAO: Nehmen Sie an der ersten Governance-Sitzung des Numbers Network teil und stimmen Sie ab
Gemeinschaftsorientierung und Dezentralität sind zentrale Werte des Numbers Protokolls. Als Ausdruck unserer Werte hoffen wir, durch eine dezentrale Verwaltung einen transparenten und demokratischen Raum für unsere Gemeinschaft zu schaffen. Die Gründung einer Dezentralen Autonomen Organisation (DAO) ist unser erster Schritt, um einen offenen Raum zu schaffen, in dem wir die Stimmen und Beiträge unserer Community hören und den DAO-Mitgliedern Entscheidungsbefugnisse einräumen können, um gemeinsame Ziele für die Zukunft des Numbers-Netzwerks zu verfolgen.
Das ERSTE Numbers Network Governance Meeting ist geplant!
Thema: Erste Abstimmung der Community über den Token-Swap für das Ökosystem
Zeit: 25. März 2022
Teilnahmeberechtigung:
- Teilnahme an der Diskussion - Community-Mitglieder, die ein aktives Gray CAPTCH-A besitzen (Teilnehmer sollten vor dem Treffen mindestens 2.000 NUM besitzen, um das CAPTCH-A zu aktivieren)
- Teilnahme und Abstimmung - Community-Mitglieder mit aktivem weißem CAPTCH-A (Teilnehmer sollten mindestens 2.000 NUM vor dem Treffen besitzen, um CAPTCH-A zu aktivieren)
Weitere Informationen werden im März bekannt gegeben.
Halten Sie $NUM und erwerben Sie jetzt Ihren Robi Pal!
