### ISSUE TITLE
[Translation demand - Chinese] CAPTCH-A Staking Program Goes Live! Hold $NUM and Acquire Your Robi Pal Now!

### ISSUE THREAD

**Issue by sofiayan0523** [numbersprotocol/community-support#81]
Looking for Chinese translators to translate [<CAPTCH-A Staking Program Goes Live! Hold $NUM and Acquire Your Robi Pal Now!>](https://medium.com/numbers-protocol/captch-a-staking-program-goes-live-hold-num-and-acquire-your-robi-pal-now-48c60d8690b8)

Leave your translation in this issue comment to become our Tier 1 Ambassador!

--
- How to participate
> - Translate **at least one paragraph of the selected article**.
> - **The translation should be done as the Github issue comment.**
> - **Share the link of the comment in the local community and get at least 3 likes on Github**.
> - If there are two comments linked to the same paragraph and both collect 3 likes, the earlier one wins.
> - The translation needs to be fluent and factually correct and should not be copied directly from Google translate or similar apps (any attempt to copy-paste directly from Google Translate will result in your dismissal from the Ambassador Program).

- Rewards
> - `10 NUM` per paragraph per language
> - Bounty-based, the selected article will be announced when it gets 3 likes.

**Comment by Cryptochunshui** [comment]
EmpowerCAPTCH-ANFT:质押计划
在过去两个月里，Numbers团队推出了多样质押计划。我们很高兴宣布我们的CAPTCH-A质押计划，这是一个全新不同于之前的计划，允许NUM持有者在本身的正常收入之外解锁额外的社区特权。
为什么要关注通过CAPTCH-A Staking Program解锁社区特权?在Numbers社区Wiki中的NUM代币<实用程序、质押和治理＞下，非常重要的第4阶段[治理投票]被锁定在质押和拥有“活跃”的 CAPTCH-A之后。这表明着只有一些在治理投票前获得CAPTCH- ANFT且在一段时间内持有NUM代币的人才可以参与第4阶段(实际投票)还可以在Numbers网络的方向上有直接发言权。
要想了解更多有关Numbers网络治理的信息，请查看Numbers社区 Wiki中的<官方文档>。总的来说，CAPTCH-A和Staking在 Numbers治理中的作用如下:
-CAPTCH-A:数字协议网络的正式成员
-质押激活CAPTCH-A:证明您是活跃成员，以便于具体治理的发言权。
那怎么去得到CAPTCH-A呢?
通过2020年11月上旬进行的预上市活动(释义:作为此事件的一部分而被销毁的CAPTCH-A已经不再存在于Numbers网络中，务必要以第二种方式再次开始去获得)。通过CAPTCH-A质押计划!
销毁$NUM代币来获取CAPTCH- A(详细会在之后发布)
$NUM持有人能够持2000$NUM至少14天，来拿到CAPTCH-A。一部分起初就决定持有较久时长的人能够收到高级验证码，可明显地表示网络忠诚度。 
CAPTCH-A的黑白形式增加了持有人在治理会议中的投票权。
更多关于CAPTCH-A质押详细，请参考下表:
黑色CAPTCH-A:Numbers Network正式会员，激活CAPTCH-A就能够参与治理
白色CAPTCH-A:治理权益:2，条件:需要不断质押以保证白色形式。如果在任何时候取消抵押，那么将降级为黑色CAPTCH- A。
黑色CAPTCH-A:治理权益:3，条件:需要不断质押以保持黑色形式。如果在任何时候取消抵押，那么就会降级为黑色CAPTCH- A。

**Comment by Crypto0xAugust** [comment]
### CAPTCH-A 质押计划上线！持有 $NUM 即可获得属于您的朋友 Robi！
获取你的白色 CAPTCH-A 并有资格在第一次 NUMBERSDAO 治理会议中投票。
CAPTCH-A NFT 于 2021 年 11 月首次推出，这一系列的机器人是作为Numers网络中大家叙事和表达的窗口。CAPTCH-A 本质上是动态的，它会根据显示的照片的不同而变化。这意味着单个机体可以产生多种令人兴奋而又独特呈现形式。
> 关于 CAPTCH-A：[<介绍 CAPTCH-A Robis，你在 Numbers 元宇宙中的好朋友>](https://medium.com/numbers-protocol/introducing-captch-a-robis-your-pals-in-the-numbers-metaverse-219607755913)


### 授权 CAPTCH-A NFT：质押计划
在过去的 2 个月里，Numbers 团队推出了各种质押计划。现在我们特别高兴地宣布我们的 CAPTCH-A 质押计划，这是一个全新的计划，允许 $NUM 的持有者在常规收益之外解锁额外的社区特权。

为什么你应该关心通过 CAPTCH-A 质押计划解锁社区特权？

Numbers 的社区百科中有一篇 NUM 代币文章，其中[ <效用、质押和治理> ](https://github.com/numbersprotocol/community-support/wiki/07.-NUM-Token#utility-staking-and-governance)的章节里提到了至关重要的 第4阶段【**治理投票**】的部分，这一切都是基于锁仓质押和拥有一个“激活状态”的 CAPTCH-A。换句话说，只有那些在治理投票前，已经获得 CAPTCH-A NFT 并持有 NUM 代币一定时间的人才能参与第4阶段 — 治理投票（实际投票），还可以在 Numbers 网络的发展方向上有发言权。

要了解更多有关 Numbers网络治理的信息，请查看 Numbers 社区百科中的 [[官方文档](https://github.com/numbersprotocol/community-support/wiki/07.-NUM-Token#utility-staking-and-governance)]。总而言之，CAPTCH-A和质押在 Numbers 的治理中起到的作用如下：

> - CAPTCH-A：Numbers网络的正式成员
> - 质押激活 CAPTCH-A：证明您是活跃成员，以便收到治理的电话会议的通知。

### 那么如何获得 CAPTCH-A 呢？
1、通过 2020 年 11 月上旬进行的预上市活动（注意：作为此事件的一部分而被烧毁的 CAPTCH-A 已不再存在于 Numbers 网络中，所以必须以第二种方式重新获得）。
2、通过CAPTCH-A 质押计划！
3、烧毁 $NUM 代币以获取 CAPTCH-A（详情将在未来公布）

$NUM 持有者可以持有2,000 $NUM至少 14 天来获得 CAPTCH-A。那些一开始就决定持有较长时间的人可以获得高级CAPTCH-A，可以更直观地彰显他们对Numbers网络忠诚度。黑白配色的CAPTCH-A 可以增加了持有人在治理会议中的投票影响力。
有关 CAPTCH-A 质押明细，请参见下表：
- 灰色 CAPTCH-A：Numbers Network 正式会员，激活 CAPTCH-A 即可参与治理
- 白色 CAPTCH-A：治理权重：2   条款：需要持续质押以维持WHITE形式。如果在任何时候取消抵押，它将降级为灰色 CAPTCH-A。
- 黑色 CAPTCH-A：治理权重：3   条款：需要持续质押以保持黑色形式。如果在任何时候取消抵押，它将降级为灰色 CAPTCH-A。

### 白色 CAPTCH-A 已发布！ 
### 如何获得白色 CAPTCH-A？
1、填写[表格](https://airtable.com/shrfv7P7q5aY61Wri)
2、在 2022 年 2 月 14 日 13:00 UTC 之前将至少 2,000 个 NUM 存入你的钱包
3、将 $NUM 在同一个钱包中保存 30 天（截至 2022 年 3 月 15 日 12:59 UTC）
4、Tala! 领取您的白色CAPTCH-A并在我们的第一次治理会议上投票！
**如果您已经是灰色CAPTCH-A 持有者，你有 2 个选项可以升级你的 CAPTCH-A。**
1、升级到 3D Gray CAPTCH-A

- 填写[表格](https://airtable.com/shrCItDFZIrdWnYPm)并免费获得新的 3D Gray CAPTCH-A

2、升级到 白色 CAPTCH-A 并在特别优惠中获得治理投票特权 

- 填写[表格](https://airtable.com/shrCItDFZIrdWnYPm) - 在2022年2 月14 日 13:00 UTC 之前在你的钱包中至少质押 1,600 NUM（20% 折扣，早期持有者特别优惠）
- 将 NUM 在同一个钱包中保存 30 天（至 2022 年 3 月 15 日 12:59 UTC） 
- Tala! 领取您的白色验证码并在我们的第一次治理会议上投票！



### NUMBERSDAO：参与 Numbers Network 的第一次治理会议并投票
以社区为中心和去中心化是 Numbers 协议的核心价值观。作为我们价值观的体现，我们希望通过去中心化治理为我们的社区创造一个透明和民主的空间。建立去中心化自治组织 (DAO) 是我们的第一步，去创建开放空间来听到社区声音和意见，并赋予 DAO 成员决策权，一同追寻 Numbers 网络未来的共同目标。
首次 Numbers网络 治理会议已经安排好了！

- 主题：生态系统代币交换的首次社区投票
- 时间：2022年3月25日
- 资格： 
参与讨论 - 持有激活状态的灰色 CAPTCH-A 的社区成员（参与者应在会议前至少持有 2,000 NUM 以激活 CAPTCH-A） 
参与并投票 - 持有激活状态白色 CAPTCH-A 的社区成员（参与者应在会议前至少持有 2,000 NUM 以激活 CAPTCH-A）

更多信息将在三月份公布。

持有 $NUM 并立即获取你的 Robi 朋友！


### 关于 Numbers 协议
Numbers 正在构建一个去中心化的照片网络，旨在数字媒介中创造社区、价值和信任。其 Numbers 协议将数字视觉媒体重新定义为资产，并且该协议还是Numbers 网络中一整套用于注册、检索图像和视频的工具的主干。
这些包括：

- Capture app：全球首款区块链相机，用户可以轻松注册照片并使用Web 3.0应用程序。
- Seal API：开发者和企业可以实现Numbers API来注册照片并访问他们的Web3.0地址和证书。
- 证书：具有链上来源的内容真实性证书
- CaptureClub 市场：本地 NFT 市场，允许照片生成器出售和质押他们的作品。
- NFT 搜索引擎：第一个 Web 3.0 NFT 搜索引擎，帮助用户验证 NFT 的历史并防止潜在的 NFT 欺诈。

Numbers 捍卫数字媒体的纯粹性，使人们能够更批判性地思考我们的图像与我们周围世界之间的相互作用。Numbers 的目标是对真实照片（包括图像和视频）进行通证化，以在 Web 3.0 中创建一个去中心化的照片网络。

**Comment by sofiayan0523** [comment]
@Cryptochunshui  Sorry your translation paragraph didn't get enough emoji votes, welcome to join the next translation task and get 3 likes on your comment to win the reward :)

**Comment by sofiayan0523** [comment]
@Crypto0xAugust the translation is approved and pushed to the main article with your name, please check here: https://hackmd.io/8w9-ZTm7R7CLkhtmkRuqxg#Chinese

Thank you for your contribution, please [fill out the form](https://airtable.com/shrHsGWu0uN1r2sYj) to claim the reward :)
