### ISSUE TITLE
Changing the price tag after listing in capture app

### ISSUE THREAD

**Issue by Cryptoguy86** [numbersprotocol/community-support#83]
**Is your feature request related to a problem? Please describe.**

**Describe the your user story**
Share your user story. If you are not clear about what user story is, please take a look of https://en.wikipedia.org/wiki/User_story

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Select label**
Based on the issue category, please select a label from General/Capture App/NFT Search Engine/CaptureClub

**Additional context**

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248718329918) by [Unito](https://www.unito.io)

**Comment by Cryptoguy86** [comment]
Dear NUM team, up to my knowledge regarding the changing tag price after listed in capture app, this feature it's not existing "I think".

What do you think to add this feature to be able to change the price tag, without us doing it by canceling the photo and remove it then we add it again in capture app with new price tag .

Thanks

**Comment by kennyhungQA** [comment]
Merge with https://github.com/numbersprotocol/community-support/issues/275
