### ISSUE TITLE
Fail Listing a photo in capture club

### ISSUE THREAD

**Issue by Cryptoguy86** [numbersprotocol/community-support#84]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Capture App (please complete the following information):**

**Select label**
Based on the issue category, please select a label from General/Capture App/NFT Search Engine/CaptureClub

**Additional context**

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248744772653) by [Unito](https://www.unito.io)

**Comment by Cryptoguy86** [comment]
I got same issue before, but I wasn't sure about.
The bug is, when you want to list a photo to capture club and you do pay for the listing fee and gas fee, the process will deduct the amount but without completing the listing in the capture club. You have to do the process again and another deduction to be able listing the photo again in capture club.

**Comment by kennyhungQA** [comment]
CaptureClub is no longer supported. We welcome you to continue experiencing the seamless Web3 experience provided by Numbers Protocolo through [Capture Dashboard](https://dashboard.captureapp.xyz/). Close this issue.
