### ISSUE TITLE
[FR] Photo could add frames

### ISSUE THREAD

**Issue by Cryptoguy86** [numbersprotocol/community-support#89]
**Hope feature**
When user take a photo, they could choose some frames simple to add on it.

**User story**
As a capture app user, I want to add frame on my photo so that I could add them let the photo changed.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248744084297) by [Unito](https://www.unito.io)

**Comment by Cryptoguy86** [comment]
Dear team, I have a suggestion regarding the photos in capture app and in capture club, to have options of variety of photo frames we can buy it or u decide the method of having it, or even u make them as NFT to buy and connect it to our photos, and we can sell our photo with or without the Frame. So the idea is to have feature of photo frames and you can have many way of using it .

**Comment by tammyyang** [comment]
This idea is great. We will have something shared with the community soon :).

**Comment by ethanwu155** [comment]
Hi. Thank you for taking the time to submit this Feature Request. After careful consideration from the team, we have decided that this feature falls outside the scope of our Capture products. Capture Cam and Dashboard are tools for creating traceable and verifiable digital assets with on-chain records. Providing users with filters or frames unfortunately fall outside the scope of the application.

That being said, if there is a strong demand for such a feature from the community and can positively benefit the Capture ecosystem in the form of users than our team will definitely reconsider. 

Thanks again!
