### ISSUE TITLE
Numbers Search Beta - Additional Summary Results 

### ISSUE THREAD

**Issue by willcoursen** [numbersprotocol/community-support#9]
Include additional information RE: NFT such as transaction volume. Please see the wireframe/mockup below. Included a time step as well. 

![Total Transactions - Search Results](https://user-images.githubusercontent.com/17142178/146578784-23404504-fad9-44cd-82df-0b1eb9414cf7.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248749176211) by [Unito](https://www.unito.io)

**Comment by willcoursen** [comment]
you can further refine searches to populate fewer results once you add selection criteria (e.g., art, music, collectibles, metaverse, land, etc.) 

Macro view - I understand your mission is to create a true photo network. But the utility of this search can encompass that ethos based on what i said above, "creative evaluation". I would not lose sight of being the first layer 2 to organize "all" Web3 information and make it universally accessible, useful and true.

**Comment by willcoursen** [comment]
Should also include a count of creators** (this would just be a unique count of creator addresses) See the image below, initially, you would think there are multiple creators but there is not just minted the same art multiple times. 

![image](https://user-images.githubusercontent.com/17142178/146586363-235e0faa-ad38-4ada-a344-b95fadae8b29.png)

**Comment by kennyhungQA** [comment]
This issue is no longer to be used; close it.
Currently, our NFT Search Engine is pivoting to a verification site.
