### ISSUE TITLE
Some Thoughts About Capture

### ISSUE THREAD

**Issue by Crypto0xAugust** [numbersprotocol/community-support#90]
Dear Numbers Team,

There are some ideas about 'Capture' as followed, 

1\ Add some functions in ’Capture‘, such as ‘Beautifying Function’ and ‘Filter Function’. Because huge mounts of young people around the world, especially girls who are keen on use App to beatify selfie, and then post pics to social media. And therefore this is a huge group, which is worth grasping the opportunity. So we can refer to the early winner in Web2.0, Meitu Inc.

2\ Try to cooperate with grassroots stars and internet celebrities, like Irene or Ghozali. Their success makes us know ordinary people can also issue NFTs, fortunately, which is in your field of expertise. So I think you could make an attempt to create internet celebrities and drive people to join the community with profit.

3\ The UI of capture could be better. At present, it is slightly simple. Compared with the blue-and-white color of capture, I prefer the black-and-white color like official website color, but it is in the early stage now.

Finally, I wanna say ' Capture The Beauty In The Life'.

Best Regards

--------------------------------------

亲爱的Numbers团队，

我有一些关于'Capture'的想法，

1、是否可以在Capture中添加美颜、滤镜的功能。在全世界很多年轻人中，尤其是女孩子，非常喜欢拍照然后使用滤镜修图，然后上传到社交媒体中，这是一个巨大的流量群体，值得项目方去抓住。这点可以参考早期的成功者，美图。

2、能否尝试着和像Irena和Ghozali这类的草根明星、网红合作。 他们的成功是我们明白了一件事，普通人也可以发行NFT。这正是你们擅长的领域，我认为你们也可以尝试着创造网红，用利益去驱动普通人加入其中。

3、Capture的UI界面可以进一步提升，目前来看略显质朴，相比Capture的蓝白配色，我更喜欢官网的黑白配色，不过现在处于早期阶段。

最后，我想说，‘捕捉（Capture）美好生活’。

**Comment by tammyyang** [comment]
Hi, 

Just some quick feedback for the "filter" part. As Capture uses the default camera of your mobile phone, it should supports the basic filters already :). For advanced filters such as Meitu, since some of those filters are considered as making "untrue" photos, it may against our vision...

For the UI interface, totally agree. There will be some updates coming soon!

**Comment by Crypto0xAugust** [comment]
Thx for your reply, Tammy 
Best Regards
