### ISSUE TITLE
NFT Description Error on Numberverse

### ISSUE THREAD

**Issue by Serhat86** [numbersprotocol/community-support#92]
Hello Team,
I have realized a bug on 'https://link.numbersprotocol.io/numberverse'
When i go and check the NFT on the wall does not show the description and other NFT details.
<img width="901" alt="image" src="https://user-images.githubusercontent.com/101196107/157259550-a89e983e-e75c-43f7-aa06-aa1d355548dd.png">

The picture is added. Hope you will be taking into account of my time into rewarding process.
Because i really value your project.
Thanks
Serhat

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Capture App (please complete the following information):**

**Select label**
Based on the issue category, please select a label from General/Capture App/NFT Search Engine/CaptureClub

**Additional context**

**Comment by tammyyang** [comment]
I believe this has been fixed. Can you please check again? Thank you!
